import java.io.*;

import javax.servlet.*;
import javax.servlet.http.*;

import com.jdbc.DB;

import java.sql.*;

public class cruisebooking1 extends HttpServlet {

    public void init(ServletConfig config)
    	throws ServletException {
    		super.init(config);
    	}
    public String getContext(String param) {
		ServletContext sc=getServletContext();
		String prop=sc.getInitParameter(param);
		prop=prop!=null&&prop.length()>0?""+prop:"";
		System.out.println("Contex param:"+prop);
		return prop;
	}
     public void doGet(HttpServletRequest request, HttpServletResponse response)
    throws IOException, ServletException
    {
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();
        out.println("<html>");
        out.println("<body>");
        out.println("<head>");
        out.println("<title>Hello World!</title>");
        out.println("</head>");
        out.println("<body>");
        out.println("<h1>Hello World!</h1>");
        out.println("Your request was"+ request.getMethod()+"\n");
        out.println("</body>");
        out.println("</html>");
    }
    public void doPost(HttpServletRequest request, HttpServletResponse response)
    throws IOException, ServletException
    {
        Connection c=null;
        String loginid=request.getParameter("loginid");
        String pswd=request.getParameter("pswd");
  		response.setContentType("text/html");
        PrintWriter out = response.getWriter();
  		try{
   	     	Connection conn=DB.getConnect();
   	     	Statement st=conn.createStatement();
            String query = new String("select * from Customer where loginid='" +loginid+ "'" ); 
            ResultSet rs= st.executeQuery(query);
            if(rs.next())
            {
            	if(!pswd.equals(rs.getString("pswd")))
            	{
            		out.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">");
					out.println("<html>");
					out.println("<head>");
					out.println("<title>Untitled Document</title>");
					out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
					out.println("<SCRIPT>");
					out.println("/*function doClear()");
					out.println("{		 ");
					out.println("document.mainform.loginid.value =\"\"");
					out.println("document.mainform.password.value = \"\";");
					out.println("}*/");
					out.println("function doSubmit()");
					out.println("{");
					out.println("var strErrMsg;");
					out.println("strErrMsg = \"\";			");
					out.println("strErrMsg = doValidations();");
					out.println("if (strErrMsg == \"\" )");
					out.println("{				");
					out.println("document.mainform.action = \"cruisebooking1\";		");
					out.println("document.mainform.submit();");
					out.println("}");
					out.println("else");
					out.println("{alert(strErrMsg);}");
					out.println("}");
					out.println("function doValidations()");
					out.println("{");
					out.println("var ddIndex;");
					out.println("var strTemp;");
					out.println("var strFld;");
					out.println("var frmDoc;");
					out.println("var strErrMsg;");
					out.println("strErrMsg = \"\";");
					out.println("frmDoc = document.mainform;			");
					out.println("strFld = frmDoc.loginid");
					out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"login-id can not be null\\n\";			");
					out.println("strFld = frmDoc.pswd");
					out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"password can not be null\\n\";	");
					out.println("return strErrMsg;");
					out.println("}");
					out.println("</SCRIPT>");
					out.println("<style type=\"text/css\">");
					out.println("<!--");
					out.println(".style11 {color: #FFFFFF}");
					out.println(".style12 {");
					out.println("color: #000000;");
					out.println("font-weight: bold;");
					out.println("}");
					out.println("-->");
					out.println("</style>");
					out.println("</head>");
					out.println("<body>");
					out.println("<FORM name=mainform method=post>");
					out.println("<div align=\"center\">");
					out.println("<center>");
					out.println("<div align=\"center\">");
					out.println("<center>");
					out.println("<TABLE cellSpacing=0 cellPadding=0 width=750 border=0 style=\"border-collapse: collapse\" bordercolor=\"#111111\">");
					out.println("<TBODY>");
					out.println("<TR> ");
					out.println("<TD class=header>              <img src=\"images/frontpage.gif\" width=\"386\" height=\"71\"><img src=\"images/Hdr_AS_Seal.jpg\" width=\"289\" height=\"71\"><img src=\"images/1animated12-thumb[1].gif\" width=\"67\" height=\"50\"></TD>");
					out.println("</TR>");
					out.println("</TBODY>");
					out.println("</TABLE>");
					out.println("</center>");
					out.println("</div>");
					out.println("<p align=\"left\"><font face=\"arial\" size=\"2\"> ");
					out.println("<marquee behavior=\"scroll\" style=\"font-family: Courier New; color: #333300; text-decoration: blink; font-size: 18pt; font-style: italic; font-weight: bold\">");
					out.println("we share a visi<img src=\"images/Animsun.gif\" width=\"60\" height=\"48\">n ");
					out.println("</marquee>");
					out.println("</font></p>");
					out.println("</center>");
					out.println("</div>");
					out.println("<table width=\"97%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr bordercolor=\"#CCCCCC\" bgcolor=\"#000099\"> ");
                    out.println("<td width=\"10%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"home.htm\"><font color=\"#FFFFFF\" size=\"5\">Home</font></a></div></td>");
                    out.println("<td width=\"14%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"services.htm\"><font color=\"#FFFFFF\" size=\"5\">Services</font></a></div></td>");
                    out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"packagefinal.htm\"><font color=\"#FFFFFF\" size=\"5\">Holiday ");
					out.println("Packages </font></a></div></td>");
                    out.println("<td width=\"11%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"faq.htm\"><font color=\"#FFFFFF\" size=\"5\">FAQs</font></a></div></td>");
                    out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"register.htm\"><font color=\"#FFFFFF\" size=\"5\">Register Yourself </font></a></div></td>");
                    out.println("<td width=\"15%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"aboutus.htm\"><font color=\"#FFFFFF\" size=\"5\">About ");
					out.println("Us</font></a></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td colspan=\"6\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr bgcolor=\"#0000CC\"> ");
                    out.println("<td width=\"22%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"acc.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
					out.println("Accommodation</font></a></div></td>");
                    out.println("<td width=\"21%\" bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"travel.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
					out.println("Traveling Means</font></a></div>");
					out.println("<div align=\"center\"></div></td>");
                    out.println("<td width=\"25%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travelguide.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
					out.println("Guide</font></a></div></td>");
                    out.println("<td width=\"32%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travelinsurance.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
					out.println("Insurance</font></a></div></td>");
					out.println("</tr>");
					out.println("</table></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<table width=\"97%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr bgcolor=\"#3333FF\"> ");
                    out.println("<td bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"car.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
					out.println("Car</font></a></div></td>");
                    out.println("<td bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"train.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
					out.println("Train</font></a></div></td>");
                    out.println("<td bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"flight.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
					out.println("Flight</font></a></div></td>");
                    out.println("<td bgcolor=\"3399FF\"> <div align=\"center\"><a href=\"cruise.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
					out.println("Cruises</font></a></div></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<h1 align=\"center\"><font color=\"#660033\">hcutravels Cruise Ships </font></h1>");
					out.println("<table width=\"733\" height=\"304\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
					out.println("<tr> ");
					out.println("<td height=\"33\" colspan=\"2\"><div align=\"center\"><img src=\"images/headingcruises.gif\" width=\"604\" height=\"21\"></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td width=\"145\" height=\"242\" valign=\"top\" bgcolor=\"#0099FF\"> ");
					out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\"><strong><a href=\"new.htm\">New 2 Cruising </a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\"><strong><a href=\"logincruise.htm\">Book Cruises</a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\">            <div align=\"center\" class=\"style12\"></div>            </td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\" class=\"style12\"><a href=\"occasion.htm\">Special Occasions </a></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\"><strong><a href=\"faqc.htm\">FAQ's</a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\"><strong><a href=\"Cruise%20Protection%20Plan.htm\">Cruise Protection Plan </a></strong></div></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<p class=\"style11\"><img src=\"images/celebrity_2.jpg\" width=\"145\" height=\"31\"></p>");
					out.println("<p class=\"style11\"><img src=\"images/carnival_2.jpg\" width=\"144\" height=\"31\"></p></td >");
					out.println("<td width=\"588\"><table width=\"100%\" height=\"278\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"\">");
					out.println("<tr bgcolor=\"#FFCCFF\"> ");
					out.println("<td height=\"49\" colspan=\"2\"> <div align=\"center\">");
					out.println("<p><font color=\"#660033\" size=\"5\">Online ");
					out.println("Cruise Booking </font></p>");
					out.println("<p><strong><font color=\"#660033\" size=\"5\">Invalid Password!!!</font></strong></p>");
					out.println("</div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td width=\"70%\"><table width=\"100%\" height=\"220\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
					out.println("<tr bgcolor=\"#FFCCFF\">");
					out.println("<td colspan=\"2\">");
					out.println("<div align=\"center\"><em><strong><font color=\"#660000\" size=\"5\">Try Again!!! </font></strong></em></div></td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td width=\"51%\"><div align=\"center\"><strong>Login ID</strong></div></td>");
					out.println("<td width=\"49%\"><div align=\"center\">");
					out.println("<input name=\"loginid\" type=\"text\" id=\"loginid3\">");
					out.println("</div></td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td><div align=\"center\"><strong>Password</strong></div></td>");
					out.println("<td><div align=\"center\">");
					out.println("<input name=\"pswd\" type=\"password\" id=\"password\">");
					out.println("</div></td>");
					out.println("</tr>");
					out.println("<tr bgcolor=\"#FFCCFF\">");
					out.println("<td height=\"72\" colspan=\"2\">");
					out.println("<div align=\"center\" >");
					out.println("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"147\" height=\"34\">");
					out.println("<param name=\"BGCOLOR\" value=\"#FFCCFF\">");
					out.println("<param name=\"movie\" value=\"images/loginc.swf\">");
					out.println("<param name=\"quality\" value=\"high\">");
					out.println("<embed src=\"images/loginc.swf\" width=\"147\" height=\"34\" quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" bgcolor=\"#FFCCFF\" ></embed>");
					out.println("</object> ");
					out.println("</div></td>");
					out.println("</tr>");
					out.println("</table></td>");
					out.println("<td width=\"30%\"><img src=\"images/cruises-celebrity.jpg\" width=\"200\" height=\"229\"></td>");
					out.println("</tr>");
					out.println("</table></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<p align=\"center\">&nbsp;</p>");
					out.println("<hr size=1 width=\"70%\">");
                    out.println("<p align=\"center\"> <a href=\"new.htm\">New 2 Cruising</a>| <a href=\"logincruise.htm\">Book Cruises</a>| <a href=\"occasion.htm\">Special Occasions|</a> <a href=\"faq.htm\">FAQ's</a> | <a href=\"Cruise%20Protection%20Plan.htm\">Cruise ProtectionPlan</a> </p>");
					out.println("<div align=\"center\"><FONT face=\"Arial, Helvetica, sans-serif\"><A ");
                    out.println("href=\"home.htm\"><FONT ");
					out.println("size=3>Home</FONT></A></FONT></div>");
					out.println("<hr size=1 width=\"70%\">");
					out.println("<p align=\"center\"><img src=\"images/twisting_cranberry_wht.jpg\" width=\"300\" height=\"30\"></p>");
					out.println("</body>");
					out.println("</html>");
					
            	}
            	else
            	{
            		out.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">");
					out.println("<html>");
					out.println("<head>");
					out.println("<title>Untitled Document</title>");
					out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
					out.println("<SCRIPT>");
					out.println("function doSubmit()");
					out.println("{");
					out.println("var strErrMsg;");
					out.println("strErrMsg = \"\";			");
					out.println("strErrMsg = doValidations();");
					out.println("if (strErrMsg == \"\" )");
					out.println("{				");
					out.println("document.mainform.action = \"cruiseconfirm\";				");
					out.println("document.mainform.submit();");
					out.println("}");
					out.println("else");
					out.println("{alert(strErrMsg);}");
					out.println("}");
					out.println("function doValidations()");
					out.println("{");
					out.println("var ddIndex;");
					out.println("var strTemp;");
					out.println("var strFld;");
					out.println("var frmDoc;");
					out.println("var strErrMsg;");
					out.println("strErrMsg = \"\";");
					out.println("frmDoc = document.mainform;			");
					out.println("strFld = frmDoc.cardno");
					out.println("if (strFld.value == \"\"|| strFld.value.length<4 || strFld.value.length >4 ) 		");
					out.println("strErrMsg = strErrMsg + \" Credit Crad No. is Invalid\\n\";");
					out.println("return strErrMsg;");
					out.println("}");
					out.println("</SCRIPT>");
					out.println("<style type=\"text/css\">");
					out.println("<!--");
					out.println(".style11 {color: #FFFFFF}");
					out.println(".style12 {");
					out.println("color: #000000;");
					out.println("font-weight: bold;");
					out.println("}");
					out.println("-->");
					out.println("</style>");
					out.println("</head>");
					out.println("<body>");
					out.println("<FORM name=mainform method=post>");
					out.println("<div align=\"center\">");
					out.println("<center>");
					out.println("<div align=\"center\">");
					out.println("<center>");
					out.println("<TABLE cellSpacing=0 cellPadding=0 width=750 border=0 style=\"border-collapse: collapse\" bordercolor=\"#111111\">");
					out.println("<TBODY>");
					out.println("<TR> ");
					out.println("<TD class=header>              <img src=\"images/frontpage.gif\" width=\"386\" height=\"71\"><img src=\"images/Hdr_AS_Seal.jpg\" width=\"289\" height=\"71\"><img src=\"images/1animated12-thumb[1].gif\" width=\"67\" height=\"50\"></TD>");
					out.println("</TR>");
					out.println("</TBODY>");
					out.println("</TABLE>");
					out.println("</center>");
					out.println("</div>");
					out.println("<p align=\"left\"><font face=\"arial\" size=\"2\"> ");
					out.println("<marquee behavior=\"scroll\" style=\"font-family: Courier New; color: #333300; text-decoration: blink; font-size: 18pt; font-style: italic; font-weight: bold\">");
					out.println("we share a visi<img src=\"images/Animsun.gif\" width=\"60\" height=\"48\">n ");
					out.println("</marquee>");
					out.println("</font></p>");
					out.println("</center>");
					out.println("</div>");
					out.println("<table width=\"97%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr bordercolor=\"#CCCCCC\" bgcolor=\"#000099\"> ");
                    out.println("<td width=\"10%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"home.htm\"><font color=\"#FFFFFF\" size=\"5\">Home</font></a></div></td>");
                    out.println("<td width=\"14%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"services.htm\"><font color=\"#FFFFFF\" size=\"5\">Services</font></a></div></td>");
                    out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"packagefinal.htm\"><font color=\"#FFFFFF\" size=\"5\">Holiday ");
					out.println("Packages </font></a></div></td>");
                    out.println("<td width=\"11%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"faq.htm\"><font color=\"#FFFFFF\" size=\"5\">FAQs</font></a></div></td>");
                    out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"register.htm\"><font color=\"#FFFFFF\" size=\"5\">Register Yourself </font></a></div></td>");
                    out.println("<td width=\"15%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"aboutus.htm\"><font color=\"#FFFFFF\" size=\"5\">About ");
					out.println("Us</font></a></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td colspan=\"6\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr bgcolor=\"#0000CC\"> ");
                    out.println("<td width=\"22%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"acc.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
					out.println("Accommodation</font></a></div></td>");
                    out.println("<td width=\"21%\" bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"travel.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
					out.println("Traveling Means</font></a></div>");
					out.println("<div align=\"center\"></div></td>");
                    out.println("<td width=\"25%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travelguide.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
					out.println("Guide</font></a></div></td>");
                    out.println("<td width=\"32%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travelinsurance.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
					out.println("Insurance</font></a></div></td>");
					out.println("</tr>");
					out.println("</table></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<table width=\"97%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr bgcolor=\"#3333FF\"> ");
                    out.println("<td bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"car.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
					out.println("Car</font></a></div></td>");
                    out.println("<td bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"train.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
					out.println("Train</font></a></div></td>");
                    out.println("<td bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"flight.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
					out.println("Flight</font></a></div></td>");
                    out.println("<td bgcolor=\"3399FF\"> <div align=\"center\"><a href=\"cruise.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
					out.println("Cruises</font></a></div></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<h1 align=\"center\"><font color=\"#660033\">hcutravels Cruise Ships </font></h1>");
					out.println("<table width=\"733\" height=\"322\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
					out.println("<tr> ");
					out.println("<td height=\"33\" colspan=\"2\"><div align=\"center\"><img src=\"images/headingcruises.gif\" width=\"604\" height=\"21\"></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td width=\"145\" height=\"289\" valign=\"top\" bgcolor=\"#0099FF\"> ");
					out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\"><strong><a href=\"new.htm\">New 2 Cruising </a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\"><strong><a href=\"logincruise.htm\">Book Cruises</a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\">            <div align=\"center\" class=\"style12\"></div>            </td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\" class=\"style12\"><a href=\"occasion.htm\">Special Occasions </a></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\"><strong><a href=\"faqc.htm\">FAQ's</a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\"><strong><a href=\"Cruise%20Protection%20Plan.htm\">Cruise Protection Plan </a></strong></div></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<p class=\"style11\"><img src=\"images/celebrity_2.jpg\" width=\"145\" height=\"31\"></p>");
					out.println("<p class=\"style11\"><img src=\"images/carnival_2.jpg\" width=\"144\" height=\"31\"></p></td >");
					out.println("<td width=\"588\">      <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"images/airfare_search_bg_big.gif\">");
					out.println("<tr bgcolor=\"#FFCCFF\">");
					out.println("<td colspan=\"2\">");
					out.println("<div align=\"center\"><font color=\"#660033\" size=\"5\">Cruise Booking Form</font></div></td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td width=\"61%\" height=\"20\"><font size=\"4\"> &nbsp;Your Customer ID</font></td>");
					out.println("<td width=\"39%\">");
					out.println("<input name=\"loginid\" type=\"text\" id=\"loginid\" value=\""+loginid+"\"size=\"25\" maxlength=\"25\"  >");
					out.println("<strong></strong></td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td height=\"20\"><font size=\"4\">&nbsp;Departure From</font></td>");
					out.println("<td>");
					out.println("<select name=\"source\" id=\"select33\">");
					out.println("<option value=\"ND\" selected>New Delhi</option>");
					out.println("<option value=\"KL\">Kolkata</option>");
					out.println("<option value=\"CH\">Chennai</option>");
					out.println("<option value=\"MB\">Mumbai</option>");
					out.println("<option value=\"VS\">Vishakapatnam</option>");
					out.println("<option value=\"MG\">Manglore</option>");
					out.println("<option value=\"LK\">Lucknow</option>");
					out.println("<option value=\"GO\">Goa</option>");
					out.println("</select>");
					out.println("</td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td><font size=\"4\">&nbsp;Arrival To</font></td>");
					out.println("<td><select name=\"destination\" id=\"select34\">");
					out.println("<option value=\"ND\">New Delhi</option>");
					out.println("<option value=\"KL\">Kolkata</option>");
					out.println("<option value=\"CH\" selected>Chennai</option>");
					out.println("<option value=\"MB\">Mumbai</option>");
					out.println("<option value=\"VS\">Vishakapatnam</option>");
					out.println("<option value=\"MG\">Manglore</option>");
					out.println("<option value=\"LK\">Lucknow</option>");
					out.println("<option value=\"GO\">Goa</option>");
					out.println("</select></td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td><font size=\"4\">&nbsp;Departure Date</font></td>");
					out.println("<td>");
					out.println("<select name=\"sdd\" id=\"select35\">");
					out.println("<option value=\"1\">01</option>");
					out.println("<option value=\"2\">02</option>");
					out.println("<option value=\"3\">03</option>");
					out.println("<option value=\"4\">04</option>");
					out.println("<option value=\"5\">05</option>");
					out.println("<option value=\"6\">06</option>");
					out.println("<option value=\"7\">07</option>");
					out.println("<option value=\"8\">08</option>");
					out.println("<option value=\"9\">09</option>");
					out.println("<option value=\"10\">10</option>");
					out.println("<option value=\"11\">11</option>");
					out.println("<option value=\"12\">12</option>");
					out.println("<option value=\"13\">13</option>");
					out.println("<option value=\"14\">14</option>");
					out.println("<option value=\"15\">15</option>");
					out.println("<option value=\"16\">16</option>");
					out.println("<option value=\"17\">17</option>");
					out.println("<option value=\"18\">18</option>");
					out.println("<option value=\"19\">19</option>");
					out.println("<option value=\"20\">20</option>");
					out.println("<option value=\"21\" selected>21</option>");
					out.println("<option value=\"22\">22</option>");
					out.println("<option value=\"23\">23</option>");
					out.println("<option value=\"24\">24</option>");
					out.println("<option value=\"25\">25</option>");
					out.println("<option value=\"26\">26</option>");
					out.println("<option value=\"27\">27</option>");
					out.println("<option value=\"28\">28</option>");
					out.println("<option value=\"29\">29</option>");
					out.println("<option value=\"30\">30</option>");
					out.println("<option value=\"31\">31</option>");
					out.println("</select>");
					out.println("<select name=\"smm\" id=\"select36\">");
					out.println("<option value=\"01\">JAN</option>");
					out.println("<option value=\"02\">FEB</option>");
					out.println("<option value=\"03\">MAR</option>");
					out.println("<option value=\"04\">APR</option>");
					out.println("<option value=\"05\">MAY</option>");
					out.println("<option value=\"06\">JUN</option>");
					out.println("<option value=\"07\">JUL</option>");
					out.println("<option value=\"08\">AUG</option>");
					out.println("<option value=\"09\">SEP</option>");
					out.println("<option value=\"10\">OCT</option>");
					out.println("<option value=\"11\" selected>NOV</option>");
					out.println("<option value=\"12\">DEC</option>");
					out.println("</select>");
					out.println("<select name=\"syy\" id=\"select37\">");
					out.println("<option value=\"04\" selected>2004</option>");
					out.println("<option value=\"05\">2005</option>");
					out.println("</select>");
					out.println("</td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td><font size=\"4\">Cruise Lines </font></td>");
					out.println("<td><SELECT name=cruiselines size=1 id=\"cruiselines\">");
					out.println("<OPTION value=1>Carnival Cruise Lines</OPTION>");
					out.println("<option value=\"2\">Celebrity Cruises</option>");
					out.println("<option value=\"3\">Costa Cruises</option>");
					out.println("<option value=\"4\">Crystal Cruises</option>");
					out.println("<option value=\"5\">Cunard Line</option>");
					out.println("<option value=\"6\">Disney Cruise Line</option>");
					out.println("</SELECT>");
					out.println("</td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td><font size=\"4\">Number of Nights </font></td>");
					out.println("<td><select name=\"nights\" id=\"nights\">");
					out.println("<option value=\"1\">1-6 Nights</option>");
					out.println("<option value=\"2\">7-9 Nights</option>");
					out.println("<option value=\"3\">10 Nights+</option>");
					out.println("</select>");
					out.println("</td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td><font size=\"4\">Number of Tickets </font></td>");
					out.println("<td>          <select name=\"tickets\" size=\"1\" id=\"tickets\">");
					out.println("<option value=\"1\">1</option>");
					out.println("<option value=\"2\">2</option>");
					out.println("<option value=\"3\">3</option>");
					out.println("<option value=\"4\">4</option>");
					out.println("</select>");
					out.println("</td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td><font size=\"4\">&nbsp;Number of children</font></td>");
					out.println("<td>          <select name=\"children\" id=\"children\">");
					out.println("<option value=\"1\">1</option>");
					out.println("<option value=\"2\">2</option>");
					out.println("<option value=\"3\">3</option>");
					out.println("</select>        </td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td height=\"20\"><font size=\"4\">&nbsp;Enter last four digits of your Credit Card No.</font></td>");
					out.println("<td>");
					out.println("<input name=\"cardno\" type=\"password\" id=\"cardno5\" size=\"8\" maxlength=\"4\">");
					out.println("</td>");
					out.println("</tr>");
					out.println("</table>      <p align=\"center\">");
					out.println("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"103\" height=\"24\">");
					out.println("<param name=\"BGCOLOR\" value=\"\">");
					out.println("<param name=\"movie\" value=\"images/bookc.swf\">");
					out.println("<param name=\"quality\" value=\"high\">");
					out.println("<embed src=\"images/bookc.swf\" quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" width=\"103\" height=\"24\" ></embed>");
					out.println("</object>");
					out.println("</p></td></tr></table>");
					out.println("<p align=\"center\">&nbsp;</p>");
					out.println("<hr size=1 width=\"70%\">");
					out.println("<p align=\"center\">&nbsp;</p>");
                    out.println("<p align=\"center\"><a href=\"new.htm\">New 2 Cruising</a>| <a href=\"logincruise.htm\">Book Cruises</a>|  <a href=\"occasion.htm\">Special Occasions|</a> <a href=\"faq.htm\">FAQ's</a> | <a href=\"Cruise%20Protection%20Plan.htm\">Cruise ProtectionPlan</a></p>");
					out.println("<p align=\"center\"><FONT face=\"Arial, Helvetica, sans-serif\"><A ");
                    out.println("href=\"home.htm\"><FONT ");
					out.println("size=3>Home</FONT></A></FONT></p>");
					out.println("<hr size=1 width=\"70%\">");
					out.println("<p align=\"center\"><img src=\"images/twisting_cranberry_wht.jpg\" width=\"300\" height=\"30\"></p>");
					out.println("<p align=\"center\">&nbsp;</p>");
					out.println("</body></html>");

					
				
            	}
            }
            else
            {
            	out.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">");
				out.println("<html>");
				out.println("<head>");
				out.println("<title>Untitled Document</title>");
				out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
				out.println("<SCRIPT>");
				out.println("/*function doClear()");
				out.println("{		 ");
				out.println("document.mainform.loginid.value =\"\"");
				out.println("document.mainform.password.value = \"\";");
				out.println("}*/");
				out.println("function doSubmit()");
				out.println("{");
				out.println("var strErrMsg;");
				out.println("strErrMsg = \"\";			");
				out.println("strErrMsg = doValidations();");
				out.println("if (strErrMsg == \"\" )");
				out.println("{				");
				out.println("document.mainform.action = \"cruisebooking1\";		");
				out.println("document.mainform.submit();");
				out.println("}");
				out.println("else");
				out.println("{alert(strErrMsg);}");
				out.println("}");
				out.println("function doValidations()");
				out.println("{");
				out.println("var ddIndex;");
				out.println("var strTemp;");
				out.println("var strFld;");
				out.println("var frmDoc;");
				out.println("var strErrMsg;");
				out.println("strErrMsg = \"\";");
				out.println("frmDoc = document.mainform;			");
				out.println("strFld = frmDoc.loginid");
				out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"login-id can not be null\\n\";			");
				out.println("strFld = frmDoc.pswd");
				out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"password can not be null\\n\";	");
				out.println("return strErrMsg;");
				out.println("}");
				out.println("</SCRIPT>");
				out.println("<style type=\"text/css\">");
				out.println("<!--");
				out.println(".style11 {color: #FFFFFF}");
				out.println(".style12 {");
				out.println("color: #000000;");
				out.println("font-weight: bold;");
				out.println("}");
				out.println("-->");
				out.println("</style>");
				out.println("</head>");
				out.println("<body>");
				out.println("<FORM name=mainform method=post>");
				out.println("<div align=\"center\">");
				out.println("<center>");
				out.println("<div align=\"center\">");
				out.println("<center>");
				out.println("<TABLE cellSpacing=0 cellPadding=0 width=750 border=0 style=\"border-collapse: collapse\" bordercolor=\"#111111\">");
				out.println("<TBODY>");
				out.println("<TR> ");
				out.println("<TD class=header>              <img src=\"images/frontpage.gif\" width=\"386\" height=\"71\"><img src=\"images/Hdr_AS_Seal.jpg\" width=\"289\" height=\"71\"><img src=\"images/1animated12-thumb[1].gif\" width=\"67\" height=\"50\"></TD>");
				out.println("</TR>");
				out.println("</TBODY>");
				out.println("</TABLE>");
				out.println("</center>");
				out.println("</div>");
				out.println("<p align=\"left\"><font face=\"arial\" size=\"2\"> ");
				out.println("<marquee behavior=\"scroll\" style=\"font-family: Courier New; color: #333300; text-decoration: blink; font-size: 18pt; font-style: italic; font-weight: bold\">");
				out.println("we share a visi<img src=\"images/Animsun.gif\" width=\"60\" height=\"48\">n ");
				out.println("</marquee>");
				out.println("</font></p>");
				out.println("</center>");
				out.println("</div>");
				out.println("<table width=\"97%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
				out.println("<tr bordercolor=\"#CCCCCC\" bgcolor=\"#000099\"> ");
                out.println("<td width=\"10%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"home.htm\"><font color=\"#FFFFFF\" size=\"5\">Home</font></a></div></td>");
                out.println("<td width=\"14%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"services.htm\"><font color=\"#FFFFFF\" size=\"5\">Services</font></a></div></td>");
                out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"packagefinal.htm\"><font color=\"#FFFFFF\" size=\"5\">Holiday ");
				out.println("Packages </font></a></div></td>");
                out.println("<td width=\"11%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"faq.htm\"><font color=\"#FFFFFF\" size=\"5\">FAQs</font></a></div></td>");
                out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"register.htm\"><font color=\"#FFFFFF\" size=\"5\">Register Yourself </font></a></div></td>");
                out.println("<td width=\"15%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"aboutus.htm\"><font color=\"#FFFFFF\" size=\"5\">About ");
				out.println("Us</font></a></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td colspan=\"6\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
				out.println("<tr bgcolor=\"#0000CC\"> ");
                out.println("<td width=\"22%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"acc.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
				out.println("Accommodation</font></a></div></td>");
                out.println("<td width=\"21%\" bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"travel.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
				out.println("Traveling Means</font></a></div>");
				out.println("<div align=\"center\"></div></td>");
                out.println("<td width=\"25%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travelguide.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
				out.println("Guide</font></a></div></td>");
                out.println("<td width=\"32%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travelinsurance.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
				out.println("Insurance</font></a></div></td>");
				out.println("</tr>");
				out.println("</table></td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("<table width=\"97%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
				out.println("<tr bgcolor=\"#3333FF\"> ");
                out.println("<td bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"car.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
				out.println("Car</font></a></div></td>");
                out.println("<td bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"train.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
				out.println("Train</font></a></div></td>");
                out.println("<td bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"flight.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
				out.println("Flight</font></a></div></td>");
                out.println("<td bgcolor=\"3399FF\"> <div align=\"center\"><a href=\"cruise.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
				out.println("Cruises</font></a></div></td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("<h1 align=\"center\"><font color=\"#660033\">hcutravels Cruise Ships </font></h1>");
				out.println("<table width=\"733\" height=\"304\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
				out.println("<tr> ");
				out.println("<td height=\"33\" colspan=\"2\"><div align=\"center\"><img src=\"images/headingcruises.gif\" width=\"604\" height=\"21\"></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td width=\"145\" height=\"242\" valign=\"top\" bgcolor=\"#0099FF\"> ");
				out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
				out.println("<tr> ");
                out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\"><strong><a href=\"new.htm\">New 2 Cruising </a></strong></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\"><strong><a href=\"logincruise.htm\">Book Cruises</a></strong></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\">            <div align=\"center\" class=\"style12\"></div>            </td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\" class=\"style12\"><a href=\"occasion.htm\">Special Occasions </a></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\"><strong><a href=\"faqc.htm\">FAQ's</a></strong></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"> <div align=\"center\"><strong><a href=\"Cruise%20Protection%20Plan.htm\">Cruise Protection Plan </a></strong></div></td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("<p class=\"style11\"><img src=\"images/celebrity_2.jpg\" width=\"145\" height=\"31\"></p>");
				out.println("<p class=\"style11\"><img src=\"images/carnival_2.jpg\" width=\"144\" height=\"31\"></p></td >");
				out.println("<td width=\"588\"><table width=\"100%\" height=\"278\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"\">");
				out.println("<tr bgcolor=\"#FFCCFF\"> ");
				out.println("<td height=\"49\" colspan=\"2\"> <div align=\"center\">");
				out.println("<p><font color=\"#660033\" size=\"5\">Online ");
				out.println("Cruise Booking </font></p>");
				out.println("<p><strong><font color=\"#660033\" size=\"5\">Invalid LoginID!!!</font></strong></p>");
				out.println("</div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td width=\"70%\"><table width=\"100%\" height=\"220\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
				out.println("<tr bgcolor=\"#FFCCFF\">");
				out.println("<td colspan=\"2\">");
				out.println("<div align=\"center\"><em><strong><font color=\"#660000\" size=\"5\">Try Again!!! </font></strong></em></div></td>");
				out.println("</tr>");
				out.println("<tr>");
				out.println("<td width=\"51%\"><div align=\"center\"><strong>Login ID</strong></div></td>");
				out.println("<td width=\"49%\"><div align=\"center\">");
				out.println("<input name=\"loginid\" type=\"text\" id=\"loginid3\">");
				out.println("</div></td>");
				out.println("</tr>");
				out.println("<tr>");
				out.println("<td><div align=\"center\"><strong>Password</strong></div></td>");
				out.println("<td><div align=\"center\">");
				out.println("<input name=\"pswd\" type=\"password\" id=\"password\">");
				out.println("</div></td>");
				out.println("</tr>");
				out.println("<tr bgcolor=\"#FFCCFF\">");
				out.println("<td height=\"72\" colspan=\"2\">");
				out.println("<div align=\"center\" >");
				out.println("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"147\" height=\"34\">");
				out.println("<param name=\"BGCOLOR\" value=\"#FFCCFF\">");
				out.println("<param name=\"movie\" value=\"images/loginc.swf\">");
				out.println("<param name=\"quality\" value=\"high\">");
				out.println("<embed src=\"images/loginc.swf\" width=\"147\" height=\"34\" quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" bgcolor=\"#FFCCFF\" ></embed>");
				out.println("</object> ");
				out.println("</div></td>");
				out.println("</tr>");
				out.println("</table></td>");
				out.println("<td width=\"30%\"><img src=\"images/cruises-celebrity.jpg\" width=\"200\" height=\"229\"></td>");
				out.println("</tr>");
				out.println("</table></td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("<p align=\"center\">&nbsp;</p>");
				out.println("<hr size=1 width=\"70%\">");
                out.println("<p align=\"center\"> <a href=\"new.htm\">New 2 Cruising</a>| <a href=\"logincruise.htm\">Book Cruises</a>|  <a href=\"occasion.htm\">Special Occasions|</a> <a href=\"faq.htm\">FAQ's</a> | <a href=\"Cruise%20Protection%20Plan.htm\">Cruise ProtectionPlan</a> </p>");
				out.println("<div align=\"center\"><FONT face=\"Arial, Helvetica, sans-serif\"><A ");
                out.println("href=\"home.htm\"><FONT ");
				out.println("size=3>Home</FONT></A></FONT></div>");
				out.println("<hr size=1 width=\"70%\">");
				out.println("<p align=\"center\"><img src=\"images/twisting_cranberry_wht.jpg\" width=\"300\" height=\"30\"></p>");
				out.println("</body>");
				out.println("</html>");
				
				
            }
            }catch(Exception e){
            	out.println("Exception"+e.getMessage()+e.toString());
            }
            finally{
            	try{
            		if(c!=null)
            			c.close();
            	}catch(Exception e){
            		out.println("Exception closing the connection"+e.getMessage());
            	}
            }
   		}
   }
   
