import java.io.*;

import javax.servlet.*;
import javax.servlet.http.*;

import com.jdbc.DB;

import java.sql.*;

public class flightlogin extends HttpServlet {
    public void init(ServletConfig config)
    	throws ServletException {
    		super.init(config);
    	}
	 public String getContext(String param) {
		ServletContext sc=getServletContext();
		String prop=sc.getInitParameter(param);
		prop=prop!=null&&prop.length()>0?""+prop:"";
		System.out.println("Contex param:"+prop);
		return prop;
	}
    public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException, ServletException {
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();
        out.println("<html>");
        out.println("<body>");
        out.println("<head>");
        out.println("<title>Hello World!</title>");
        out.println("</head>");
        out.println("<body>");
        out.println("<h1>Hello World!</h1>");
        out.println("Your request was"+ request.getMethod()+"\n");
        out.println("</body>");
        out.println("</html>");
    }
    public void doPost(HttpServletRequest request, HttpServletResponse response)
    throws IOException, ServletException
    {
        Connection c=null;
        String loginid=request.getParameter("loginid");
        String pswd=request.getParameter("pswd");
  		response.setContentType("text/html");
        PrintWriter out = response.getWriter();
  		try{
   	     	Connection conn=DB.getConnect();
   	     	Statement st=conn.createStatement();
            String query = new String("select * from Customer where loginid='" +loginid+ "'" ); 
            ResultSet rs= st.executeQuery(query);
            if(rs.next())
            {
            	if(!pswd.equals(rs.getString("pswd")))
            	{
	            	out.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">");
					out.println("<html>");
					out.println("<head>");
					out.println("<title>Untitled Document</title>");
					out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
					out.println("<SCRIPT>");
					out.println("function doSubmit()");
					out.println("{");
					out.println("var strErrMsg;");
					out.println("strErrMsg = \"\";			");
					out.println("strErrMsg = doValidations();");
					out.println("if (strErrMsg == \"\" )");
					out.println("{				");
					out.println("document.mainform.action = \"flightlogin\";				");
					out.println("document.mainform.submit();");
					out.println("}");
					out.println("else");
					out.println("{alert(strErrMsg);}");
					out.println("}");
					out.println("function doValidations()");
					out.println("{");
					out.println("var ddIndex;");
					out.println("var strTemp;");
					out.println("var strFld;");
					out.println("var frmDoc;");
					out.println("var strErrMsg;");
					out.println("strErrMsg = \"\";");
					out.println("frmDoc = document.mainform;			");
					out.println("strFld = frmDoc.login");
					out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"Please enter loginId\\n\";			");
					out.println("strFld = frmDoc.password");
					out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"Please enter password\\n\";	");
					out.println("return strErrMsg;");
					out.println("}");
					out.println("</SCRIPT>");
					out.println("</head>");
					out.println("<body>");
					out.println("<FORM name=mainform method=post>");
					out.println("<div align=\"center\">");
					out.println("<center>");
					out.println("<div align=\"center\">");
					out.println("<center>");
					out.println("<TABLE cellSpacing=0 cellPadding=0 width=750 border=0 style=\"border-collapse: collapse\" bordercolor=\"#111111\">");
					out.println("<TBODY>");
					out.println("<TR> ");
					out.println("<TD class=header><img src=\"images/frontpage.gif\" alt=\"\" width=\"386\" height=\"71\"><img src=\"images/Hdr_AS_Seal.jpg\" width=\"289\" height=\"71\"> ");
					out.println("<img src=\"images/1animated12-thumb%5B1%5D.gif\" width=\"67\" height=\"50\"> ");
					out.println("</TD>");
					out.println("</TR>");
					out.println("</TBODY>");
					out.println("</TABLE>");
					out.println("</center>");
					out.println("</div>");
					out.println("<p align=\"left\"><font face=\"arial\" size=\"2\"> ");
					out.println("<marquee behavior=\"scroll\" style=\"font-family: Courier New; color: #333300; text-decoration: blink; font-size: 18pt; font-style: italic; font-weight: bold\">");
					out.println("we share a visi<img src=\"images/Animsun.gif\" width=\"50\" height=\"26\">n ");
					out.println("</marquee>");
					out.println("</font></p>");
					out.println("</center>");
					out.println("</div>");
					out.println("<table width=\"97%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr bordercolor=\"#CCCCCC\" bgcolor=\"#000099\"> ");
					out.println("<td width=\"10%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"home.htm\"><font color=\"#FFFFFF\" size=\"5\">Home</font></a></div></td>");
					out.println("<td width=\"14%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"services.htm\"><font color=\"#FFFFFF\" size=\"5\">Services</font></a></div></td>");
					out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"packagefinal.htm\"><font color=\"#FFFFFF\" size=\"5\">Holiday ");
					out.println("Packages </font></a></div></td>");
					out.println("<td width=\"11%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"faq.htm\"><font color=\"#FFFFFF\" size=\"5\">FAQs</font></a></div></td>");
					out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"register.htm\"><font color=\"#FFFFFF\" size=\"5\">Register ");
					out.println("Yourself</font></a></div></td>");
					out.println("<td width=\"15%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"aboutus.htm\"><font color=\"#FFFFFF\" size=\"5\">About ");
					out.println("Us</font></a></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td colspan=\"6\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr bgcolor=\"#0000CC\"> ");
					out.println("<td width=\"22%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"acc.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
					out.println("Accommodation</font></a></div></td>");
					out.println("<td width=\"21%\" bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"travel.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
					out.println("Traveling Means</font></a></div>");
					out.println("<div align=\"center\"></div></td>");
					out.println("<td width=\"25%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travelguide.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
					out.println("Guide</font></a></div></td>");
					out.println("<td width=\"32%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travelinsurance\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
					out.println("Insurance</font></a></div></td>");
					out.println("</tr>");
					out.println("</table></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<table width=\"97%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr bgcolor=\"#3333FF\"> ");
					out.println("<td bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"car.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
					out.println("Car</font></a></div></td>");
					out.println("<td bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"train.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
					out.println("Train</font></a></div></td>");
					out.println("<td bgcolor=\"#3399FF\"> <div align=\"center\"><a href=\"flight.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
					out.println("Flight</font></a></div></td>");
					out.println("<td> <div align=\"center\"><a href=\"cruise.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
					out.println("Cruises</font></a></div></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<h1 align=\"center\"><font color=\"#660033\">Flights</font></h1>");
					out.println("<table width=\"733\" height=\"390\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
					out.println("<tr> ");
					out.println("<td height=\"130\" colspan=\"2\"><div align=\"center\"><img src=\"images/h_air_01.gif\" width=\"511\" height=\"110\"><img src=\"images/h_air_02.gif\" width=\"205\" height=\"110\"></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td width=\"145\" height=\"260\" valign=\"top\" bgcolor=\"#660000\"> ");
					out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><strong><a href=\"flightstatus.htm\">Flight ");
					out.println("Status</a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><strong><a href=\"farecompare.htm\">Fare ");
					out.println("Compare</a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><a href=\"passport.htm\"><strong>Passport ");
					out.println("Details</strong></a></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><strong><a href=\"timetable.htm\">Time ");
					out.println("Table Search</a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFCCFF\"> <div align=\"center\"><strong><a href=\"flightlogin.htm\">Flight ");
					out.println("Booking </a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><a href=\"airport.htm\"><strong>Airport ");
					out.println("Details</strong></a></div></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<p align=\"center\"><img src=\"images/108937881992.jpg\" width=\"125\" height=\"125\"></p></td>");
					out.println("<td width=\"588\"><table width=\"100%\" height=\"260\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"images/airfare_search_bg_big.gif\">");
					out.println("<tr bgcolor=\"#FFCCFF\"> ");
					out.println("<td height=\"42\" colspan=\"2\"> <div align=\"center\"><font color=\"#660033\" size=\"5\">Online ");
					out.println("Flight Booking </font></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td width=\"70%\" height=\"218\"> ");
					out.println("<div align=\"center\"> ");
					out.println("<table width=\"100%\" height=\"217\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
					out.println("<tr bgcolor=\"#FFCCFF\"> ");
					out.println("<td colspan=\"2\"> <div align=\"center\"><em><strong><font color=\"#660000\" size=\"4\">Invalid ");
					out.println("Password !!!</font></strong></em></div></td>");
					out.println("</tr>");
					out.println("<tr bgcolor=\"#FFCCFF\">");
					out.println("<td colspan=\"2\"><div align=\"center\"><strong><font color=\"#660000\" size=\"4\">Try ");
					out.println("Again</font></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td width=\"51%\"><div align=\"center\"><strong>Login ID</strong></div></td>");
					out.println("<td width=\"49%\"><div align=\"center\"> ");
					out.println("<input name=\"loginid\" type=\"text\" id=\"login\">");
					out.println("</div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td><div align=\"center\"><strong>Password</strong></div></td>");
					out.println("<td><div align=\"center\"> ");
					out.println("<input name=\"pswd\" type=\"password\" id=\"password\">");
					out.println("</div></td>");
					out.println("</tr>");
					out.println("<tr bgcolor=\"#FFCCFF\"> ");
					out.println("<td height=\"61\" colspan=\"2\"> ");
					out.println("<div align=\"center\" > ");
					out.println("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"147\" height=\"34\">");
					out.println("<param name=\"movie\" value=\"images/button8.swf\">");
					out.println("<param name=\"quality\" value=\"high\">");
					out.println("<param name=\"bgcolor\" value=\"#FFCCFF\">");
					out.println("<embed src=\"images/button8.swf\" quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" width=\"147\" height=\"34\" bgcolor=\"#FFCCFF\"></embed> ");
					out.println("</object>");
					out.println("</div></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("</div></td>");
					out.println("<td width=\"30%\"><img src=\"images/flight.jpg\" width=\"177\" height=\"218\"></td>");
					out.println("</tr>");
					out.println("</table></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<p align=\"center\">&nbsp;</p>");
					out.println("<hr size=1 width=\"70%\">");
					out.println("<p align=\"center\"><FONT face=\"Arial, Helvetica, sans-serif\" size=2><A ");
					out.println("href=\"flightstatus.htm\">Flight Status </A> | <A ");
					out.println("href=\"farecompare.htm\">Fare Compare</A> | <A ");
					out.println("href=\"passport.htm\">Passport Details</A> | <A ");
					out.println("href=\"timetable.htm\">Time Table Search</A> | <A ");
					out.println("href=\"flightlogin.htm\">Flight Booking</A> | <A ");
					out.println("href=\"airport.htm\">Airport Details</A></FONT></p>");
					out.println("<div align=\"center\"><FONT face=\"Arial, Helvetica, sans-serif\"><A ");
					out.println("href=\"home.htm\"><FONT ");
					out.println("size=3>HOME</FONT></A></FONT> </div>");
					out.println("<hr size=1 width=\"70%\">");
					out.println("<p align=\"center\"><img src=\"images/twisting_cranberry_wht.jpg\" width=\"300\" height=\"30\"></p>");
					out.println("</body>");
					out.println("</html>");

            	}
            	else
            	{
            		
            		out.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">");
					out.println("<html>");
					out.println("<head>");
					out.println("<title>Untitled Document</title>");
					out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
					out.println("<SCRIPT>");
					out.println("function doEnable()");
					out.println("{");
					out.println("if(document.mainform.type.value==\"RT\")");
					out.println("{");
					out.println("document.mainform.ddd.disabled = false;");
					out.println("document.mainform.dmm.disabled = false;");
					out.println("document.mainform.dyy.disabled = false;");
					out.println("}");
					out.println("else");
					out.println("{");
					out.println("document.mainform.ddd.disabled = true;");
					out.println("document.mainform.dmm.disabled = true;");
					out.println("document.mainform.dyy.disabled = true;");
					out.println("}");
					out.println("}");
					out.println("function doSubmit()");
					out.println("{");
					out.println("var strErrMsg;");
					out.println("strErrMsg = \"\";			");
					out.println("strErrMsg = doValidations();");
					out.println("if (strErrMsg == \"\" )");
					out.println("{				");
					out.println("document.mainform.action = \"flightbooking\";				");
					out.println("document.mainform.submit();");
					out.println("}");
					out.println("else");
					out.println("{alert(strErrMsg);}");
					out.println("}");
					out.println("function doValidations()");
					out.println("{");
					out.println("var ddIndex;");
					out.println("var strTemp;");
					out.println("var strFld;");
					out.println("var frmDoc;");
					out.println("var strErrMsg;");
					out.println("strErrMsg = \"\";");
					out.println("frmDoc = document.mainform;			");
					out.println("strFld = frmDoc.source");
					out.println("strTemp = frmDoc.destination");
					out.println("if (strFld.value == strTemp.value) strErrMsg = strErrMsg + \" Source and destination cant be same\\n\";");
					out.println("strFld = frmDoc.not");
					out.println("if (strFld.value == \"\" ) strErrMsg = strErrMsg + \" Nuber of tickets is incorrect\\n\";");
					out.println("strFld = frmDoc.type");
					out.println("if (strFld.value == \"RT\") ");
					out.println("{	");
					out.println("if(frmDoc.syy.value<=frmDoc.dyy.value)");
					out.println("{");
					out.println("if(frmDoc.smm.value<=frmDoc.dmm.value)");
					out.println("{");
					out.println("if(frmDoc.sdd.value>frmDoc.ddd.value)");
					out.println("strErrMsg = strErrMsg + \" Date is Incorrect\\n\";");
					out.println("}");
					out.println("else");
					out.println("strErrMsg = strErrMsg + \" Date is Incorrect\\n\";");
					out.println("}");
					out.println("else");
					out.println("strErrMsg = strErrMsg + \" Date is Incorrect\\n\";");
					out.println("}");
					out.println("strFld = frmDoc.cardno");
					out.println("if (strFld.value == \"\" || strFld.value.length<4) 		");
					out.println("strErrMsg = strErrMsg + \" Credit Crad No. is Invalid\\n\";");
					out.println("return strErrMsg;");
					out.println("}");
					out.println("</SCRIPT>");
					out.println("</head>");
					out.println("<body>");
					out.println("<FORM name=mainform method=post>");
					out.println("<div align=\"center\"> ");
					out.println("<center>");
					out.println("<TABLE cellSpacing=0 cellPadding=0 width=750 border=0 style=\"border-collapse: collapse\" bordercolor=\"#111111\">");
					out.println("<TBODY>");
					out.println("<TR> ");
					out.println("<TD class=header><img src=\"images/frontpage.gif\" alt=\"\" width=\"386\" height=\"71\"><img src=\"images/Hdr_AS_Seal.jpg\" width=\"289\" height=\"71\"> ");
					out.println("<img src=\"images/1animated12-thumb%5B1%5D.gif\" width=\"67\" height=\"50\"> ");
					out.println("</TD>");
					out.println("</TR>");
					out.println("</TBODY>");
					out.println("</TABLE>");
					out.println("</center>");
					out.println("</div>");
					out.println("<p align=\"left\"><font face=\"arial\" size=\"2\"> ");
					out.println("<marquee behavior=\"scroll\" style=\"font-family: Courier New; color: #333300; text-decoration: blink; font-size: 18pt; font-style: italic; font-weight: bold\">");
					out.println("we share a visi<img src=\"images/Animsun.gif\" width=\"50\" height=\"26\">n ");
					out.println("</marquee>");
					out.println("</font></p>");
					out.println("</center>");
					out.println("</div>");
					out.println("<table width=\"97%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr bordercolor=\"#CCCCCC\" bgcolor=\"#000099\"> ");
					out.println("<td width=\"10%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"home.htm\"><font color=\"#FFFFFF\" size=\"5\">Home</font></a></div></td>");
					out.println("<td width=\"14%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"services.htm\"><font color=\"#FFFFFF\" size=\"5\">Services</font></a></div></td>");
					out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"packagefinal.htm\"><font color=\"#FFFFFF\" size=\"5\">Holiday ");
					out.println("Packages </font></a></div></td>");
					out.println("<td width=\"11%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"faq.htm\"><font color=\"#FFFFFF\" size=\"5\">FAQs</font></a></div></td>");
					out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"register.htm\"><font color=\"#FFFFFF\" size=\"5\">Register ");
					out.println("Yourself</font></a></div></td>");
					out.println("<td width=\"15%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"aboutus.htm\"><font color=\"#FFFFFF\" size=\"5\">About ");
					out.println("Us</font></a></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td colspan=\"6\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr bgcolor=\"#0000CC\"> ");
					out.println("<td width=\"22%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"acc.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
					out.println("Accommodation</font></a></div></td>");
					out.println("<td width=\"21%\" bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"travel.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
					out.println("Traveling Means</font></a></div>");
					out.println("<div align=\"center\"></div></td>");
					out.println("<td width=\"25%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travelguide.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
					out.println("Guide</font></a></div></td>");
					out.println("<td width=\"32%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travelinsurance.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
					out.println("Insurance</font></a></div></td>");
					out.println("</tr>");
					out.println("</table></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<table width=\"97%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr bgcolor=\"#3333FF\"> ");
					out.println("<td bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"car.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
					out.println("Car</font></a></div></td>");
					out.println("<td bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"train.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
					out.println("Train</font></a></div></td>");
					out.println("<td bgcolor=\"#3399FF\"> <div align=\"center\"><a href=\"flight.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
					out.println("Flight</font></a></div></td>");
					out.println("<td> <div align=\"center\"><a href=\"cruise.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
					out.println("Cruises</font></a></div></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<h1 align=\"center\"><font color=\"#660033\">Flights</font></h1>");
					out.println("<table width=\"733\" height=\"401\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
					out.println("<tr> ");
					out.println("<td height=\"130\" colspan=\"2\"><div align=\"center\"><img src=\"images/h_air_01.gif\" width=\"511\" height=\"110\"><img src=\"images/h_air_02.gif\" width=\"205\" height=\"110\"></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td width=\"147\" height=\"271\" valign=\"top\" bgcolor=\"#660000\"> ");
					out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><strong><a href=\"flightstatus.htm\">Flight ");
					out.println("Status</a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><strong><a href=\"farecompare.htm\">Fare ");
					out.println("Compare</a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><a href=\"passport.htm\"><strong>Passport ");
					out.println("Details</strong></a></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><strong><a href=\"timetable.htm\">Time ");
					out.println("Table Search</a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFCCFF\"> <div align=\"center\"><strong><a href=\"flightlogin.htm\">Flight ");
					out.println("Booking </a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><a href=\"airport.htm\"><strong>Airport ");
					out.println("Details</strong></a></div></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<p align=\"center\"><img src=\"images/108937881992.jpg\" width=\"125\" height=\"125\"></p></td>");
					out.println("<td width=\"586\"><table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"images/airfare_search_bg_big.gif\">");
					out.println("<tr bgcolor=\"#FFCCFF\"> ");
					out.println("<td colspan=\"2\"> <div align=\"center\"><font color=\"#660033\" size=\"5\">Flight ");
					out.println("Booking Form</font></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td width=\"65%\" height=\"20\"><font size=\"4\"> &nbsp;Your Customer ID</font></td>");
					out.println("<td width=\"35%\"> <input name=\"loginid\" type=\"text\" id=\"loginid\" value=\"" +loginid+ "\" size=\"25\" maxlength=\"25\"   > <strong></strong></td>");
					out.println("<strong></strong></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td height=\"20\"><font size=\"4\">&nbsp;Departure From</font></td>");
					out.println("<td> <select name=\"source\" id=\"source\">");
					out.println("<option value=\"ND\" selected>New Delhi</option>");
					out.println("<option value=\"KL\">Kolkata</option>");
					out.println("<option value=\"CH\">Chennai</option>");
					out.println("<option value=\"MB\">Mumbai</option>");
					out.println("<option value=\"BG\">Banglore</option>");
					out.println("<option value=\"ID\">Indore</option>");
					out.println("<option value=\"LK\">Lucknow</option>");
					out.println("<option value=\"RC\">Ranchi</option>");
					out.println("</select> </td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td><font size=\"4\">&nbsp;Arrival To</font></td>");
					out.println("<td><select name=\"destination\" id=\"destination\">");
					out.println("<option value=\"ND\">New Delhi</option>");
					out.println("<option value=\"KL\">Kolkata</option>");
					out.println("<option value=\"CH\" selected>Chennai</option>");
					out.println("<option value=\"MB\">Mumbai</option>");
					out.println("<option value=\"BG\">Banglore</option>");
					out.println("<option value=\"ID\">Indore</option>");
					out.println("<option value=\"LK\">Lucknow</option>");
					out.println("<option value=\"RC\">Ranchi</option>");
					out.println("</select></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td><font size=\"4\">&nbsp;Departure Date</font></td>");
					out.println("<td> <select name=\"sdd\" id=\"DD\">");
					out.println("<option value=\"1\">01</option>");
					out.println("<option value=\"2\">02</option>");
					out.println("<option value=\"3\">03</option>");
					out.println("<option value=\"4\">04</option>");
					out.println("<option value=\"5\">05</option>");
					out.println("<option value=\"6\">06</option>");
					out.println("<option value=\"7\">07</option>");
					out.println("<option value=\"8\">08</option>");
					out.println("<option value=\"9\">09</option>");
					out.println("<option value=\"10\">10</option>");
					out.println("<option value=\"11\">11</option>");
					out.println("<option value=\"12\">12</option>");
					out.println("<option value=\"13\">13</option>");
					out.println("<option value=\"14\">14</option>");
					out.println("<option value=\"15\">15</option>");
					out.println("<option value=\"16\">16</option>");
					out.println("<option value=\"17\">17</option>");
					out.println("<option value=\"18\">18</option>");
					out.println("<option value=\"19\">19</option>");
					out.println("<option value=\"20\">20</option>");
					out.println("<option value=\"21\" selected>21</option>");
					out.println("<option value=\"22\">22</option>");
					out.println("<option value=\"23\">23</option>");
					out.println("<option value=\"24\">24</option>");
					out.println("<option value=\"25\">25</option>");
					out.println("<option value=\"26\">26</option>");
					out.println("<option value=\"27\">27</option>");
					out.println("<option value=\"28\">28</option>");
					out.println("<option value=\"29\">29</option>");
					out.println("<option value=\"30\">30</option>");
					out.println("<option value=\"31\">31</option>");
					out.println("</select> <select name=\"smm\" id=\"MM\">");
					out.println("<option value=\"01\">JAN</option>");
					out.println("<option value=\"02\">FEB</option>");
					out.println("<option value=\"03\">MAR</option>");
					out.println("<option value=\"04\">APR</option>");
					out.println("<option value=\"05\">MAY</option>");
					out.println("<option value=\"06\">JUN</option>");
					out.println("<option value=\"07\">JUL</option>");
					out.println("<option value=\"08\">AUG</option>");
					out.println("<option value=\"09\">SEP</option>");
					out.println("<option value=\"10\">OCT</option>");
					out.println("<option value=\"11\" selected>NOV</option>");
					out.println("<option value=\"12\">DEC</option>");
					out.println("</select> <select name=\"syy\" id=\"YY\">");
					out.println("<option value=\"04\" selected>2004</option>");
					out.println("<option value=\"05\">2005</option>");
					out.println("</select> </td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td><font size=\"4\">&nbsp;No Of Tickets</font></td>");
					out.println("<td> <input name=\"not\" type=\"text\" id=\"not\" size=\"5\" maxlength=\"1\"> ");
					out.println("</td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td><font size=\"4\">&nbsp;Class</font></td>");
					out.println("<td> <select name=\"class\" id=\"class\">");
					out.println("<option value=\"EC\" selected>Economy</option>");
					out.println("<option value=\"BS\">Business</option>");
					out.println("<option value=\"FS\">First</option>");
					out.println("</select> </td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td><font size=\"4\">&nbsp;Type</font></td>");
					out.println("<td> <select name=\"type\" id=\"type\" onChange=\"javascript:doEnable();\">");
					out.println("<option value=\"RT\">Round Trip</option>");
					out.println("<option value=\"OW\" selected>One Way</option>");
					out.println("</select> </td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td><font size=\"4\">&nbsp;Return Date</font></td>");
					out.println("<td><select name=\"ddd\" id=\"select\" disabled=true>");
					out.println("<option value=\"1\">01</option>");
					out.println("<option value=\"2\">02</option>");
					out.println("<option value=\"3\">03</option>");
					out.println("<option value=\"4\">04</option>");
					out.println("<option value=\"5\">05</option>");
					out.println("<option value=\"6\">06</option>");
					out.println("<option value=\"7\">07</option>");
					out.println("<option value=\"8\">08</option>");
					out.println("<option value=\"9\">09</option>");
					out.println("<option value=\"10\">10</option>");
					out.println("<option value=\"11\">11</option>");
					out.println("<option value=\"12\">12</option>");
					out.println("<option value=\"13\">13</option>");
					out.println("<option value=\"14\">14</option>");
					out.println("<option value=\"15\">15</option>");
					out.println("<option value=\"16\">16</option>");
					out.println("<option value=\"17\">17</option>");
					out.println("<option value=\"18\">18</option>");
					out.println("<option value=\"19\">19</option>");
					out.println("<option value=\"20\">20</option>");
					out.println("<option value=\"21\" selected>21</option>");
					out.println("<option value=\"22\">22</option>");
					out.println("<option value=\"23\">23</option>");
					out.println("<option value=\"24\">24</option>");
					out.println("<option value=\"25\">25</option>");
					out.println("<option value=\"26\">26</option>");
					out.println("<option value=\"27\">27</option>");
					out.println("<option value=\"28\">28</option>");
					out.println("<option value=\"29\">29</option>");
					out.println("<option value=\"30\">30</option>");
					out.println("<option value=\"31\">31</option>");
					out.println("</select> <select name=\"dmm\" id=\"select2\" disabled=true>");
					out.println("<option value=\"01\">JAN</option>");
					out.println("<option value=\"02\">FEB</option>");
					out.println("<option value=\"03\">MAR</option>");
					out.println("<option value=\"04\">APR</option>");
					out.println("<option value=\"05\">MAY</option>");
					out.println("<option value=\"06\">JUN</option>");
					out.println("<option value=\"07\">JUL</option>");
					out.println("<option value=\"08\">AUG</option>");
					out.println("<option value=\"09\">SEP</option>");
					out.println("<option value=\"10\">OCT</option>");
					out.println("<option value=\"11\" selected>NOV</option>");
					out.println("<option value=\"12\">DEC</option>");
					out.println("</select> <select name=\"dyy\" id=\"select3\" disabled=true>");
					out.println("<option value=\"04\" selected>2004</option>");
					out.println("<option value=\"05\">2005</option>");
					out.println("</select> </td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td height=\"20\"><font size=\"4\">&nbsp;Enter last four digits of your Credit ");
					out.println("Card No.</font></td>");
					out.println("<td> <input name=\"cardno\" type=\"password\" id=\"cardno\" size=\"8\" maxlength=\"4\"> ");
					out.println("</td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<p align=\"center\">");
					out.println("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"103\" height=\"30\">");
					out.println("<param name=\"BGCOLOR\" value=\"\">");
					out.println("<param name=\"movie\" value=\"images/button7.swf\">");
					out.println("<param name=\"quality\" value=\"high\">");
					out.println("<embed src=\"images/button7.swf\" base=\"\"  quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" width=\"103\" height=\"30\" ></embed></object>");
					out.println("</p></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<p align=\"center\">&nbsp;</p>");
					out.println("<hr size=1 width=\"70%\">");
					out.println("<p align=\"center\"><FONT face=\"Arial, Helvetica, sans-serif\" size=2><A ");
					out.println("href=\"flightstatus.htm\">Flight Status </A> | <A ");
					out.println("href=\"farecompare.htm\">Fare Compare</A> | <A ");
					out.println("href=\"passport.htm\">Passport Details</A> | <A ");
					out.println("href=\"timetable.htm\">Time Table Search</A> | <A ");
					out.println("href=\"flightlogin.htm\">Flight Booking</A> | <A ");
					out.println("href=\"airport.htm\">Airport Details</A></FONT></p>");
					out.println("<div align=\"center\"><FONT face=\"Arial, Helvetica, sans-serif\"><A ");
					out.println("href=\"home.htm\"><FONT ");
					out.println("size=3>HOME</FONT></A></FONT> </div>");
					out.println("<hr size=1 width=\"70%\">");
					out.println("<p align=\"center\"><img src=\"images/twisting_cranberry_wht.jpg\" width=\"300\" height=\"30\"></p>");
					out.println("</body>");
					out.println("</html>");

	
            	}
            }
            else
            {
            	out.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">");
				out.println("<html>");
				out.println("<head>");
				out.println("<title>Untitled Document</title>");
				out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
				out.println("<SCRIPT>");
				out.println("/*function doClear()");
				out.println("{		 ");
				out.println("document.mainform.BudgetAmtPDay.value = \"\";");
				out.println("document.mainform.BudgetAmtPTrip.value = \"\";");
				out.println("}*/");
				out.println("function doSubmit()");
				out.println("{");
				out.println("var strErrMsg;");
				out.println("strErrMsg = \"\";			");
				out.println("strErrMsg = doValidations();");
				out.println("if (strErrMsg == \"\" )");
				out.println("{				");
				out.println("document.mainform.action = \"flightlogin\";				");
				out.println("document.mainform.submit();");
				out.println("}");
				out.println("else");
				out.println("{alert(strErrMsg);}");
				out.println("}");
				out.println("function doValidations()");
				out.println("{");
				out.println("var ddIndex;");
				out.println("var strTemp;");
				out.println("var strFld;");
				out.println("var frmDoc;");
				out.println("var strErrMsg;");
				out.println("strErrMsg = \"\";");
				out.println("frmDoc = document.mainform;			");
				out.println("strFld = frmDoc.login");
				out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"Please enter loginId\\n\";			");
				out.println("strFld = frmDoc.password");
				out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"Please enter password\\n\";	");
				out.println("return strErrMsg;");
				out.println("}");
				out.println("</SCRIPT>");
				out.println("</head>");
				out.println("<body>");
				out.println("<FORM name=mainform method=post>");
				out.println("<div align=\"center\">");
				out.println("<center>");
				out.println("<div align=\"center\">");
				out.println("<center>");
				out.println("<TABLE cellSpacing=0 cellPadding=0 width=750 border=0 style=\"border-collapse: collapse\" bordercolor=\"#111111\">");
				out.println("<TBODY>");
				out.println("<TR> ");
				out.println("<TD class=header><img src=\"images/frontpage.gif\" alt=\"\" width=\"386\" height=\"71\"><img src=\"images/Hdr_AS_Seal.jpg\" width=\"289\" height=\"71\"> ");
				out.println("<img src=\"images/1animated12-thumb%5B1%5D.gif\" width=\"67\" height=\"50\"> ");
				out.println("</TD>");
				out.println("</TR>");
				out.println("</TBODY>");
				out.println("</TABLE>");
				out.println("</center>");
				out.println("</div>");
				out.println("<p align=\"left\"><font face=\"arial\" size=\"2\"> ");
				out.println("<marquee behavior=\"scroll\" style=\"font-family: Courier New; color: #333300; text-decoration: blink; font-size: 18pt; font-style: italic; font-weight: bold\">");
				out.println("we share a visi<img src=\"images/Animsun.gif\" width=\"50\" height=\"26\">n ");
				out.println("</marquee>");
				out.println("</font></p>");
				out.println("</center>");
				out.println("</div>");
				out.println("<table width=\"97%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
				out.println("<tr bordercolor=\"#CCCCCC\" bgcolor=\"#000099\"> ");
				out.println("<td width=\"10%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"home.htm\"><font color=\"#FFFFFF\" size=\"5\">Home</font></a></div></td>");
				out.println("<td width=\"14%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"services.htm\"><font color=\"#FFFFFF\" size=\"5\">Services</font></a></div></td>");
				out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"packagefinal.htm\"><font color=\"#FFFFFF\" size=\"5\">Holiday ");
				out.println("Packages </font></a></div></td>");
				out.println("<td width=\"11%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"faq.htm\"><font color=\"#FFFFFF\" size=\"5\">FAQs</font></a></div></td>");
				out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"register.htm\"><font color=\"#FFFFFF\" size=\"5\">Register ");
				out.println("Yourself</font></a></div></td>");
				out.println("<td width=\"15%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"aboutus.htm\"><font color=\"#FFFFFF\" size=\"5\">About ");
				out.println("Us</font></a></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td colspan=\"6\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
				out.println("<tr bgcolor=\"#0000CC\"> ");
				out.println("<td width=\"22%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"acc.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
				out.println("Accommodation</font></a></div></td>");
				out.println("<td width=\"21%\" bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"travel.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
				out.println("Traveling Means</font></a></div>");
				out.println("<div align=\"center\"></div></td>");
				out.println("<td width=\"25%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travelguide.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
				out.println("Guide</font></a></div></td>");
				out.println("<td width=\"32%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travelinsurance\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
				out.println("Insurance</font></a></div></td>");
				out.println("</tr>");
				out.println("</table></td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("<table width=\"97%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
				out.println("<tr bgcolor=\"#3333FF\"> ");
				out.println("<td bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"car.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
				out.println("Car</font></a></div></td>");
				out.println("<td bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"train.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
				out.println("Train</font></a></div></td>");
				out.println("<td bgcolor=\"#3399FF\"> <div align=\"center\"><a href=\"flight.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
				out.println("Flight</font></a></div></td>");
				out.println("<td> <div align=\"center\"><a href=\"cruise.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
				out.println("Cruises</font></a></div></td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("<h1 align=\"center\"><font color=\"#660033\">Flights</font></h1>");
				out.println("<table width=\"733\" height=\"390\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
				out.println("<tr> ");
				out.println("<td height=\"130\" colspan=\"2\"><div align=\"center\"><img src=\"images/h_air_01.gif\" width=\"511\" height=\"110\"><img src=\"images/h_air_02.gif\" width=\"205\" height=\"110\"></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td width=\"145\" height=\"260\" valign=\"top\" bgcolor=\"#660000\"> ");
				out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
				out.println("<tr> ");
				out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><strong><a href=\"flightstatus.htm\">Flight ");
				out.println("Status</a></strong></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><strong><a href=\"farecompare.htm\">Fare ");
				out.println("Compare</a></strong></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><a href=\"passport.htm\"><strong>Passport ");
				out.println("Details</strong></a></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><strong><a href=\"timetable.htm\">Time ");
				out.println("Table Search</a></strong></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td bgcolor=\"#FFCCFF\"> <div align=\"center\"><strong><a href=\"flightlogin.htm\">Flight ");
				out.println("Booking </a></strong></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><a href=\"airport.htm\"><strong>Airport ");
				out.println("Details</strong></a></div></td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("<p align=\"center\"><img src=\"images/108937881992.jpg\" width=\"125\" height=\"125\"></p></td>");
				out.println("<td width=\"588\"><table width=\"100%\" height=\"260\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"images/airfare_search_bg_big.gif\">");
				out.println("<tr bgcolor=\"#FFCCFF\"> ");
				out.println("<td height=\"42\" colspan=\"2\"> <div align=\"center\"><font color=\"#660033\" size=\"5\">Online ");
				out.println("Flight Booking </font></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td width=\"70%\" height=\"218\"> ");
				out.println("<div align=\"center\"> ");
				out.println("<table width=\"100%\" height=\"217\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
				out.println("<tr bgcolor=\"#FFCCFF\"> ");
				out.println("<td colspan=\"2\"> <div align=\"center\"><em><strong><font color=\"#660000\" size=\"4\">Invalid ");
				out.println("Login ID !!!</font></strong></em></div></td>");
				out.println("</tr>");
				out.println("<tr bgcolor=\"#FFCCFF\">");
				out.println("<td colspan=\"2\"><div align=\"center\"><strong><font color=\"#660000\" size=\"4\">Try ");
				out.println("Again</font></strong></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td width=\"51%\"><div align=\"center\"><strong>Login ID</strong></div></td>");
				out.println("<td width=\"49%\"><div align=\"center\"> ");
				out.println("<input name=\"loginid\" type=\"text\" id=\"login\">");
				out.println("</div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td><div align=\"center\"><strong>Password</strong></div></td>");
				out.println("<td><div align=\"center\"> ");
				out.println("<input name=\"pswd\" type=\"password\" id=\"password\">");
				out.println("</div></td>");
				out.println("</tr>");
				out.println("<tr bgcolor=\"#FFCCFF\"> ");
				out.println("<td height=\"61\" colspan=\"2\"> ");
				out.println("<div align=\"center\" > ");
				out.println("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"147\" height=\"34\">");
				out.println("<param name=\"movie\" value=\"images/button8.swf\">");
				out.println("<param name=\"quality\" value=\"high\">");
				out.println("<param name=\"bgcolor\" value=\"#FFCCFF\">");
				out.println("<embed src=\"images/button8.swf\" quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" width=\"147\" height=\"34\" bgcolor=\"#FFCCFF\"></embed> ");
				out.println("</object>");
				out.println("</div></td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("</div></td>");
				out.println("<td width=\"30%\"><img src=\"images/flight.jpg\" width=\"177\" height=\"218\"></td>");
				out.println("</tr>");
				out.println("</table></td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("<p align=\"center\">&nbsp;</p>");
				out.println("<hr size=1 width=\"70%\">");
				out.println("<p align=\"center\"><FONT face=\"Arial, Helvetica, sans-serif\" size=2><A ");
				out.println("href=\"flightstatus.htm\">Flight Status </A> | <A ");
				out.println("href=\"farecompare.htm\">Fare Compare</A> | <A ");
				out.println("href=\"passport.htm\">Passport Details</A> | <A ");
				out.println("href=\"timetable.htm\">Time Table Search</A> | <A ");
				out.println("href=\"flightlogin.htm\">Flight Booking</A> | <A ");
				out.println("href=\"airport.htm\">Airport Details</A></FONT></p>");
				out.println("<div align=\"center\"><FONT face=\"Arial, Helvetica, sans-serif\"><A ");
				out.println("href=\"home.htm\"><FONT ");
				out.println("size=3>HOME</FONT></A></FONT> </div>");
				out.println("<hr size=1 width=\"70%\">");
				out.println("<p align=\"center\"><img src=\"images/twisting_cranberry_wht.jpg\" width=\"300\" height=\"30\"></p>");
				out.println("</body>");
				out.println("</html>");

            }
            }catch(Exception e){
            	out.println("Exception"+e.getMessage()+e.toString());
            }
            finally{
            	try{
            		if(c!=null)
            			c.close();
            	}catch(Exception e){
            		out.println("Exception closing the connection"+e.getMessage());
            	}
            }
   		}
   }
   
