import java.io.*;

import javax.servlet.*;
import javax.servlet.http.*;

import com.jdbc.DB;

import java.sql.*;

public class home extends HttpServlet {

    public void init(ServletConfig config)
    	throws ServletException {
    		super.init(config);
    	}
    	 public String getContext(String param) {
		ServletContext sc=getServletContext();
		String prop=sc.getInitParameter(param);
		prop=prop!=null&&prop.length()>0?""+prop:"";
		System.out.println("Contex param:"+prop);
		return prop;
	}
    

    public void doGet(HttpServletRequest request, HttpServletResponse response)
    throws IOException, ServletException
    {
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();
        out.println("<html>");
        out.println("<body>");
        out.println("<head>");
        out.println("<title>grnd tour</title>");
        out.println("</head>");
        out.println("<body>");
        out.println("<h1>Hello World!</h1>");
        out.println("Your request was"+ request.getMethod()+"\n");
        out.println("</body>");
        out.println("</html>");
    }
    
    public void doPost(HttpServletRequest request, HttpServletResponse response)
    throws IOException, ServletException
    {
        Connection c=null;                
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();
        String query =null;
   		try{
   	     	Connection conn=DB.getConnect();
   	     	Statement st=conn.createStatement();


out.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">");
out.println("<html>");
out.println("<head>");
out.println("<title>home</title>");
out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
out.println("<STYLE>A {");
out.println("COLOR: #ffffff; TEXT-DECORATION: none");
out.println("}");
out.println("A:hover {");
out.println("COLOR: #ffff00; TEXT-DECORATION: underline");
out.println("}");
out.println("</STYLE>");
out.println("</head>");
out.println("<body>");
out.println("<div align=\"center\"> ");
out.println("<center>");
out.println("<div align=\"center\">");
out.println("<center>");
out.println("<div align=\"center\"> ");
out.println("<center>");
out.println("<div align=\"center\"> ");
out.println("<center>");
out.println("<div align=\"center\"> ");
out.println("<center>");
out.println("<div align=\"center\"> ");
out.println("<center>");
out.println("<TABLE cellSpacing=0 cellPadding=0 width=750 border=0 style=\"border-collapse: collapse\" bordercolor=\"#111111\">");
out.println("<TBODY>");
out.println("<TR> ");
out.println("<TD class=header><img src=\"images/frontpage.gif\" alt=\"\" width=\"386\" height=\"71\"><img src=\"images/Hdr_AS_Seal.jpg\" width=\"289\" height=\"71\"> ");
out.println("<img src=\"images/1animated12-thumb%5B1%5D.gif\" width=\"67\" height=\"50\"> ");
out.println("</TD>");
out.println("</TR>");
out.println("</TBODY>");
out.println("</TABLE>");
out.println("</center>");
out.println("</div>");
out.println("<p align=\"left\"><font face=\"arial\" size=\"2\"> ");
out.println("<marquee behavior=\"scroll\" style=\"font-family: Courier New; color: #333300; text-decoration: blink; font-size: 18pt; font-style: italic; font-weight: bold\">");
out.println("we share a visi<img src=\"images/Animsun.gif\" width=\"50\" height=\"26\">n ");
out.println("</marquee>");
out.println("</font></p>");
out.println("</center>");
out.println("</div>");
out.println("<table width=\"99%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
out.println("<tr bordercolor=\"#CCCCCC\" bgcolor=\"#000099\"> ");
out.println("<td width=\"9%\" bgcolor=\"#0000CC\"> ");
out.println("<div align=\"center\"><a href=\"home.htm\"><font color=\"#FFFFFF\" size=\"5\">Home</font></a></div></td>");
out.println("<td width=\"13%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"services.htm\"><font color=\"#FFFFFF\" size=\"5\">Services</font></a></div></td>");
out.println("<td width=\"26%\" bgcolor=\"#000099\"> ");
out.println("<div align=\"center\"><a href=\"packagefinal.htm\"><font color=\"#FFFFFF\" size=\"5\">Holiday ");
out.println("Packages </font></a></div></td>");
out.println("<td width=\"10%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"faq.htm\"><font color=\"#FFFFFF\" size=\"5\">FAQs</font></a></div></td>");
out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"register.htm\"><font color=\"#FFFFFF\" size=\"5\">Register ");
out.println("Yourself</font></a></div></td>");
out.println("<td width=\"17%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"aboutus.htm\"><font color=\"#FFFFFF\" size=\"5\">About ");
out.println("Us</font></a></div></td>");
out.println("</tr>");
out.println("</table>");
out.println("<p>&nbsp;</p></center>");
out.println("</div>");
out.println("</center>");
out.println("</div>");
out.println("</center>");
out.println("</div>");
out.println("</center>");
out.println("</div>");
out.println("<div align=\"center\"></div>");
out.println("<TABLE cellSpacing=0 cellPadding=0 width=760 border=0>");
out.println("<TBODY>");
out.println("<TR> ");
out.println("<TD height=\"176\" vAlign=top> ");
out.println("<TABLE cellSpacing=0 cellPadding=0 width=\"100%\" border=0 height=\"27\">");
out.println("<TBODY>");
out.println("<TR> ");
out.println("<TD width=\"47%\" height=\"1\"> ");
out.println("<div align=\"left\">");
out.println("<p><img src=\"images/images(5).jpg\" width=\"134\" height=\"147\"></p>");
out.println("</div></TD>");
out.println("<TD width=\"26%\" rowspan=\"2\" bgcolor=\"#FFFFFF\" height=\"27\"> <p><img src=\"images/HOME-02.JPG\" width=\"425\" height=\"125\"></p>");
out.println("<p align=\"center\"><font color=\"#FF9966\" size=\"5\"><strong>Welcome ");
out.println("To hcutravels.com</strong></font></p></TD>");
out.println("<TD width=\"27%\" rowspan=\"2\" height=\"27\"><FORM name=FrontPage_Form2 ");
out.println("action=pc.htm method=post>");
out.println("<TABLE cellSpacing=0 cellPadding=0 width=200 border=0>");
out.println("<TBODY>");
out.println("<TR bgColor=#8dbcf5> ");
out.println("<TD width=30 bgColor=#000033><IMG height=19 ");
out.println("src=\"images/rightcurve1.gif\" ");
out.println("width=17></TD>");
out.println("<TD width=170 bgColor=#000033> <DIV align=right><B><FONT class=abbs3 color=#ffffff>hcutravels ");
out.println("Login &nbsp;</FONT></B></DIV></TD>");
out.println("</TR>");
out.println("</TBODY>");
out.println("</TABLE>");
out.println("<TABLE width=200 height=\"120\" border=0 cellPadding=0 cellSpacing=0>");
out.println("<TBODY>");
out.println("<TR> ");
out.println("<TD width=1 bgColor=#000033><IMG height=1 ");
out.println("width=1></TD>");
out.println("<TD align=middle width=321 height=30> <TABLE cellSpacing=0 cellPadding=0 width=\"97%\" align=center ");
out.println("border=0>");
out.println("<TBODY>");
out.println("<TR bgColor=#e8f0f8> ");
out.println("<TD bgColor=#e8f0f8> <DIV align=center><FONT ");
out.println("face=\"Verdana, Arial, Helvetica, sans-serif\"><B><FONT ");
out.println("class=abbs2 size=1>hcutravels ID#</FONT></B></FONT></DIV></TD>");
out.println("<TD height=22> <DIV align=center><FONT ");
out.println("face=\"Verdana, Arial, Helvetica, sans-serif\"><B><FONT ");
out.println("class=abbs2 size=1>Password</FONT></B></FONT></DIV></TD>");
out.println("</TR>");
out.println("<TR bgColor=#e8f0f8> ");
out.println("<TD align=middle bgColor=#e8f0f8><INPUT class=abbs size=8 ");
out.println("name=Login> </TD>");
out.println("<TD align=middle bgColor=#e8f0f8><INPUT class=abbs ");
out.println("type=password size=8 name=Password> </TD>");
out.println("</TR>");
out.println("<TR bgColor=#e8f0f8> ");
out.println("<TD vAlign=top align=middle colSpan=2 height=20><FONT ");
out.println("face=\"Arial, Helvetica, sans-serif\" size=1><A class=abbs2 ");
out.println("href=\"pc.htm\" ");
out.println("target=_blank><font color=\"#0000FF\">Forgot your details?</font></A><font color=\"#0000FF\">&nbsp;&nbsp;</font></FONT><FONT ");
out.println("color=#0000FF>&nbsp; </FONT><FONT ");
out.println("color=#f0f8ff> ");
out.println("<INPUT title=\"Go for My hcutravels !\" ");
out.println("type=image height=16 ");
out.println("width=70 ");
out.println("src=\"images/loginblue.gif\" ");
out.println("align=middle border=0 name=image>");
out.println("</FONT></TD>");
out.println("</TR>");
out.println("<TR bgColor=#e8f0f8> ");
out.println("<TD vAlign=top align=middle colSpan=2 height=20> ");
out.println("<DIV align=left><FONT class=abbs2 ");
out.println("face=\"Arial, Helvetica, sans-serif\" size=1>Already a hcutravels ");
out.println("member?</FONT></DIV></TD>");
out.println("</TR>");
out.println("<TR bgColor=#e8f0f8> ");
out.println("<TD align=middle colSpan=2 height=23><FONT ");
out.println("face=\"Arial, Helvetica, sans-serif\" size=1><A ");
out.println("href=\"pc.htm\"><IMG height=16 ");
out.println("src=\"images/registerblue.gif\" ");
out.println("width=138 vspace=5 border=0></A></FONT></TD>");
out.println("</TR>");
out.println("<TR bgColor=#e8f0f8> ");
out.println("<TD vAlign=top align=middle colSpan=2 height=12> ");
out.println("<DIV align=left><FONT class=abbs2 ");
out.println("face=\"Arial, Helvetica, sans-serif\" size=1>Not a member of hcutravels?</FONT></DIV></TD>");
out.println("</TR>");
out.println("<TR align=middle bgColor=#e8f0f8> ");
out.println("<TD colSpan=2 height=25><A ");
out.println("href=\"register.htm\"><IMG height=16 ");
out.println("src=\"images/enrolblue.gif\" ");
out.println("width=138 vspace=9 border=0></A></TD>");
out.println("</TR>");
out.println("<TR align=middle bgColor=#e8f0f8> ");
out.println("<TD colSpan=2 height=2><IMG height=1 ");
out.println("src=\"Welcome aboard Air Sahara India's Fastest Growing Airline_files/spacer.gif\" ");
out.println("width=1></TD>");
out.println("</TR>");
out.println("</TBODY>");
out.println("</TABLE></TD>");
out.println("<TD width=1 bgColor=#000033><IMG height=1 ");
out.println("width=1></TD>");
out.println("</TR>");
out.println("<TR> ");
out.println("<TD width=1 bgColor=#000033><IMG height=1 ");
out.println("width=1></TD>");
out.println("<TD align=middle width=321 bgColor=#000033 height=1><IMG height=1 ");

out.println("width=1></TD>");
out.println("<TD width=1 bgColor=#000033><IMG height=1 ");

out.println("width=1></TD>");
out.println("</TR>");
out.println("</TBODY>");
out.println("</TABLE>");
out.println("</FORM></TD>");
out.println("</TR>");
out.println("<TR> ");
out.println("<TD height=\"49\" bgcolor=\"#99CCCC\"> ");
out.println("<div align=\"center\"><a href=\"bharat.htm\" target=\"_blank\"><strong><font color=\"#000099\" size=\"4\">Plan ");
out.println("for Bharat Darshan</font></strong></a></div></TD>");
out.println("</TR>");
out.println("</TBODY>");
out.println("</TABLE></TD>");
out.println("</TR>");
out.println("<TR> ");
out.println("<TD vAlign=top> <div align=\"center\"> ");
out.println("<TABLE height=636 cellSpacing=0 cellPadding=0 width=760 border=0>");
out.println("<TBODY>");
out.println("<TR> ");
out.println("<TD width=166 height=\"636\" vAlign=top> <TABLE cellSpacing=0 cellPadding=0 width=\"83%\" border=0>");
out.println("<TBODY>");
out.println("<TR> ");
out.println("<TD bgColor=#7390b1><div align=\"center\"><font color=\"#FFFFCC\"><strong>Quick ");
out.println("Links</strong></font></div></TD>");
out.println("</TR>");
out.println("<TR> ");
out.println("<TD vAlign=top bgColor=#003471 height=150> <TABLE cellSpacing=2 cellPadding=2 width=\"99%\" border=0>");
out.println("<TBODY>");
out.println("<TR> ");
out.println("<TD><div align=\"center\"><font color=\"#FFFFFF\" size=\"2\" face=\"Arial\"><a href=\"distancecalculator.htm\">Distance ");
out.println("Calculator </a></font></div></TD>");
out.println("</TR>");
out.println("<TR> ");
out.println("<TD><div align=\"center\"><FONT color=\"#ffffff\" size=2 face=Arial><a href=\"currencyconversion.htm\">Currency ");
out.println("Convertor </a></FONT></div></TD>");
out.println("</TR>");
out.println("<TR> ");
out.println("<TD><div align=\"center\"><FONT face=Arial size=2><FONT color=#ffffff><A ");
out.println("href=\"www.Hotels%20in%20India,%20Indian%20Hotels,%20India%20Hotels%20Directory%20-%20By%20Destinationindia_com.htm\">Hotels ");
out.println("In India</A> </FONT></FONT></div></TD>");
out.println("</TR>");
out.println("<TR> ");
out.println("<TD><div align=\"center\"><FONT face=Arial size=2><FONT color=#ffffff><A ");
out.println("href=\"weather.htm\">Weather Details </A></FONT></FONT></div></TD>");
out.println("</TR>");
out.println("<TR> ");
out.println("<TD><div align=\"center\"><FONT face=Arial size=2><FONT color=#ffffff><a href=\"cityguide.htm\">City ");
out.println("Guide </a></FONT></FONT></div></TD>");
out.println("</TR>");
out.println("<TR> ");
out.println("<TD><div align=\"center\"><FONT face=Arial size=2><FONT color=#ffffff><A ");
out.println("href=\"pc.htm\">Contact Us</A> </FONT></FONT></div></TD>");
out.println("</TR>");
out.println("<TR> ");
out.println("<TD><div align=\"center\"><FONT face=Arial color=#ffffff size=2><A ");
out.println("href=\"http://www.adventjourneys.com/hotelReservation.htm\">Hotel ");
out.println("Reservation</A></FONT></div></TD>");
out.println("</TR>");
out.println("<TR> ");
out.println("<TD><div align=\"center\"><FONT face=Arial color=#ffffff size=2><A ");
out.println("href=\"pc.htm\">Travel Links </A></FONT></div></TD>");
out.println("</TR>");
out.println("</TBODY>");
out.println("</TABLE></TD>");
out.println("</TR>");
out.println("<TR> ");
out.println("<TD vAlign=top><div align=\"center\"><IMG height=209 ");
out.println("src=\"images/left-image-inner.jpg\" ");
out.println("width=170></div></TD>");
out.println("</TR>");
out.println("</TBODY>");
out.println("</TABLE>");
out.println("<p><img src=\"images/n_roadahead.jpeg\" width=\"170\" height=\"212\"></p>");
out.println("<p align=\"center\"><img src=\"images/payanywhere.gif\" width=\"150\" height=\"39\"></p></TD>");
out.println("<TD width=594 bgColor=#ffffff> <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
out.println("<tr>");
out.println("<td bgcolor=\"#7390b1\"> ");
out.println("<div align=\"right\"><strong><a href=\"packagefinal.htm\">Visit ");
out.println("India on your requirements</a></strong></div></td>");
out.println("</tr>");
out.println("</table>");
out.println("<TABLE height=\"100%\" cellSpacing=0 cellPadding=0 width=\"100%\" ");
out.println("border=0>");
out.println("<TBODY>");
out.println("<TR> ");
out.println("<TD> <TABLE height=\"100%\" cellSpacing=0 cellPadding=2 width=\"100%\" ");
out.println("border=0>");
out.println("<TBODY>");
out.println("<TR> ");
out.println("<TD width=\"90%\" height=465> <P align=center><A ");
out.println("href=\"http://www.internet-site.us/advent\" ");
out.println("target=new><IMG height=60 ");
out.println("src=\"images/Lon1.jpg\" width=468 ");
out.println("border=0></A></P>");
out.println("<TABLE cellSpacing=2 cellPadding=2 width=\"100%\" ");
out.println("border=0>");
out.println("<TBODY>");
out.println("<TR> ");
out.println("<TD height=\"466\"> <P align=justify><B><FONT face=Arial color=#003366 ");
out.println("size=2>Hotel Reservation</FONT></B><FONT ");
out.println("face=Arial color=#003366 size=2><B><BR>");
out.println("</B>In order to provide the perfectly ");
out.println("sounded travel experience, hcutravels ");
out.println("has its own hotels portfolio offering ");
out.println("the highest standards in comfort, ");
out.println("decor and service while super craftsmanship, ");
out.println("professional managements and outstanding ");
out.println("cuisine are notable highlights.<BR>");
out.println("<BR>");
out.println("<B>Money Saving Choices Rates Programs</B><BR>");
out.println("Ask for special offers from our company. ");
out.println("Just call our reservations center ");
out.println("for details.<BR>");
out.println("<BR>");
out.println("<B>Business Rates</B><BR>");
out.println("Business travelers Services discounted ");
out.println("room rates and special amenities such ");
out.println("as newspaper a piping hot cup of coffee ");
out.println("and room upgrades when available.<BR>");
out.println("<BR>");
out.println("<B>Mature Travels Programs</B><BR>");
out.println("Mature travelers here the opportunity ");
out.println("for special treatment of you are 60+, ");
out.println("you'll save up to 30% off you room ");
out.println("rate with advance reservation, call ");
out.println("and ask for 60+ rate. If you are 50+, ");
out.println("we offer a 10% discount you sound ");
out.println("call in advance. 10% saving on advance ");
out.println("reservation: Save 10%on future hotel ");
out.println("reservation when you call ahead.<BR>");
out.println("<BR>");
out.println("<B>Educational &amp; Training Trips<BR>");
out.println("</B>These travelers have the opportunity ");
out.println("for special discount of 20% on your ");
out.println("room rates</FONT></P>");
out.println("<P align=center><A ");
out.println("href=\"packagefinal.htm\" ");
out.println("target=new><IMG height=72 ");
out.println("src=\"images/banner_top.gif\" ");
out.println("width=434 border=0></A></P>");
out.println("<P align=center><FONT face=Arial size=2><BR>");
out.println("<FONT ");
out.println("color=#003366><A ");
out.println("href=\"http://www.adventjourneys.com/hotelReservation.htm\">Ask ");
out.println("For Details...</A></FONT><BR>");
out.println("</font></P></TD>");
out.println("</TR>");
out.println("</TBODY>");
out.println("</TABLE></TD>");
out.println("</TR>");
out.println("<TR> ");
out.println("<TD vAlign=top bgColor=#ffffff> <p>&nbsp;</p></TD>");
out.println("</TR>");
out.println("</TBODY>");
out.println("</TABLE></TD>");
out.println("</TR>");
out.println("</TBODY>");
out.println("</TABLE>");
out.println("<p>&nbsp;</p>");
out.println("<p>&nbsp;</p></TD>");
out.println("</TR>");
out.println("</TBODY>");
out.println("</TABLE>");
out.println("</div></TD>");
out.println("</TR>");
out.println("<TR> ");
out.println("<TD height=\"19\" vAlign=top><HR align=\"center\" width=\"70%\" SIZE=1> <div align=\"center\"><FONT face=\"Arial, Helvetica, sans-serif\" size=2><A ");
out.println("href=\"sevices.htm\"><font color=\"#0000FF\">Services</font></A><font color=\"#0000FF\"> ");
out.println("| <A ");
out.println("href=\"packagefinal.htm\"><font color=\"#0000FF\">Holiday Packages</font></A><font color=\"#0000FF\"> ");
out.println("| <A ");
out.println("href=\"faq.htm\"><font color=\"#0000FF\">FAQ</font></A><font color=\"#0000FF\"> | <a href=\"aboutus.htm\"><font color=\"#0000FF\">About ");
out.println("Us</font></a></FONT> </font></font></font></div><FONT face=\"Arial, Helvetica, sans-serif\" size=2><font color=\"#0000FF\"><font color=\"#0000FF\">");
out.println("<div align=\"center\"><FONT color=\"#0000FF\" face=\"Arial, Helvetica, sans-serif\"><A ");
out.println("href=\"home.htm\"><FONT ");
out.println("size=3><font color=\"#0000FF\">HOME</FONT></font></A> ");
out.println("<HR SIZE=1 width=\"70%\">");
out.println("<DIV align=center> ");
out.println("<p><font color=\"#0000FF\"><A href=\"pc.htm\"><FONT ");
out.println("face=\"Arial, Helvetica, sans-serif\" size=1><font color=\"#0000FF\">Contact ");
out.println("us</FONT></font></A><FONT ");
out.println("face=\"Arial, Helvetica, sans-serif\" size=1> | <A class=s href=\"pc.htm\"><FONT ");
out.println("face=\"Arial, Helvetica, sans-serif\" size=1><font color=\"#0000FF\">Privacy ");
out.println("Policy</FONT></font></A><FONT ");
out.println("face=\"Arial, Helvetica, sans-serif\" size=1> | <A class=s href=\"pc.htm\"><FONT ");
out.println("face=\"Arial, Helvetica, sans-serif\" size=1><font color=\"#0000FF\">Terms ");
out.println("of Use</FONT></font></A> </font></font></font></p><font color=\"#0000FF\"><FONT ");
out.println("face=\"Arial, Helvetica, sans-serif\" size=1><FONT ");
out.println("face=\"Arial, Helvetica, sans-serif\" size=1>");
out.println("<p><font color=\"#0000FF\"><img src=\"images/twisting_cranberry_wht.jpg\" width=\"300\" height=\"30\"></font></p>");
out.println("</font></font></font></DIV>");
out.println("</font></div><FONT color=\"#0000FF\" face=\"Arial, Helvetica, sans-serif\"><font color=\"#0000FF\"><FONT ");
out.println("face=\"Arial, Helvetica, sans-serif\" size=1><FONT ");
out.println("face=\"Arial, Helvetica, sans-serif\" size=1>");
out.println("<p>&nbsp;</p></font></font></font></font></font></font></font></TD>");
out.println("</TR>");
out.println("</TBODY>");
out.println("</TABLE>");
out.println("<p>&nbsp;</p>");
out.println("<p>&nbsp;</p>");
out.println("</body>");
out.println("</html>");


            
           }catch(Exception e){
            	out.println("Exception"+e.getMessage()+e.toString());
            }
            finally{
            	try{
            		if(c!=null)
            			c.close();
            	}catch(Exception e){
            		out.println("Exception closing the connection"+e.getMessage());
            	}
            }
   		}
   }



