import java.io.*;

import javax.servlet.*;
import javax.servlet.http.*;

import com.jdbc.DB;

import java.sql.*;

public class hotelbooking extends HttpServlet {

    public void init(ServletConfig config)
    	throws ServletException {
    		super.init(config);
    	}
     public String getContext(String param) {
		ServletContext sc=getServletContext();
		String prop=sc.getInitParameter(param);
		prop=prop!=null&&prop.length()>0?""+prop:"";
		System.out.println("Contex param:"+prop);
		return prop;
	}
    public void doGet(HttpServletRequest request, HttpServletResponse response)
    throws IOException, ServletException
    {
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();
        out.println("<html>");
        out.println("<body>");
        out.println("<head>");
        out.println("<title>Hello World!</title>");
        out.println("</head>");
        out.println("<body>");
        out.println("<h1>Hello World!</h1>");
        out.println("Your request was"+ request.getMethod()+"\n");
        out.println("</body>");
        out.println("</html>");
    }
    public void doPost(HttpServletRequest request, HttpServletResponse response)
    throws IOException, ServletException
    {
        Connection c=null;
        String loginid=request.getParameter("loginid");
        String pswd=request.getParameter("pswd");
  		response.setContentType("text/html");
        PrintWriter out = response.getWriter();
  		try{
   	     	Connection conn=DB.getConnect();
   	     	Statement st=conn.createStatement();
            String query = new String("select * from Customer where loginid='" +loginid+ "'" ); 
            ResultSet rs= st.executeQuery(query);
            if(rs.next())
            {
            	if(!pswd.equals(rs.getString("pswd")))
            	{
            		out.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">");
					out.println("<html>");
					out.println("<head>");
					out.println("<title>Untitled Document</title>");
					out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
					out.println("<SCRIPT>");
					out.println("/*function doClear()");
					out.println("{		 ");
					out.println("document.mainform.loginid.value =\"\"");
					out.println("document.mainform.password.value = \"\";");
					out.println("}*/");
					out.println("function doSubmit()");
					out.println("{");
					out.println("var strErrMsg;");
					out.println("strErrMsg = \"\";			");
					out.println("strErrMsg = doValidations();");
					out.println("if (strErrMsg == \"\" )");
					out.println("{				");
					out.println("document.mainform.action = \"hotelbooking\";		");
					out.println("document.mainform.submit();");
					out.println("}");
					out.println("else");
					out.println("{alert(strErrMsg);}");
					out.println("}");
					out.println("function doValidations()");
					out.println("{");
					out.println("var ddIndex;");
					out.println("var strTemp;");
					out.println("var strFld;");
					out.println("var frmDoc;");
					out.println("var strErrMsg;");
					out.println("strErrMsg = \"\";");
					out.println("frmDoc = document.mainform;			");
					out.println("strFld = frmDoc.loginid");
					out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"login-id can not be null\\n\";			");
					out.println("strFld = frmDoc.pswd");
					out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"password can not be null\\n\";	");
					out.println("return strErrMsg;");
					out.println("}");
					out.println("</SCRIPT>");
					out.println("<style type=\"text/css\">");
					out.println("<!--");
					out.println(".style11 {color: #FFFFFF}");
					out.println(".style12 {color: #000000}");
					out.println("-->");
					out.println("</style>");
					out.println("</head>");
					out.println("<body>");
					out.println("<FORM name=mainform method=post>");
					out.println("<div align=\"center\">");
					out.println("<center>");
					out.println("<div align=\"center\">");
					out.println("<center>");
					out.println("<TABLE cellSpacing=0 cellPadding=0 width=750 border=0 style=\"border-collapse: collapse\" bordercolor=\"#111111\">");
					out.println("<TBODY>");
					out.println("<TR> ");
					out.println("<TD class=header><img src=\"images/frontpage.gif\" width=\"386\" height=\"71\"> <img src=\"images/Hdr_AS_Seal.jpg\" width=\"289\" height=\"71\"><img src=\"images/1animated12-thumb%5B1%5D.gif\" width=\"67\" height=\"50\"></TD>");
					out.println("</TR>");
					out.println("</TBODY>");
					out.println("</TABLE>");
					out.println("</center>");
					out.println("</div>");
					out.println("<p align=\"left\"><font face=\"arial\" size=\"2\"> ");
					out.println("<marquee behavior=\"scroll\" style=\"font-family: Courier New; color: #333300; text-decoration: blink; font-size: 18pt; font-style: italic; font-weight: bold\">");
					out.println("we share a visi<img src=\"images/Animsun.gif\" width=\"48\" height=\"41\">n ");
					out.println("</marquee>");
					out.println("</font></p>");
					out.println("</center>");
					out.println("</div>");
					out.println("<table width=\"97%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr bordercolor=\"#CCCCCC\" bgcolor=\"#000099\"> ");
                    out.println("<td width=\"10%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"home.htm\"><font color=\"#FFFFFF\" size=\"5\">Home</font></a></div></td>");
                    out.println("<td width=\"14%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"services.htm\"><font color=\"#FFFFFF\" size=\"5\">Services</font></a></div></td>");
                    out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"packagefinal.htm\"><font color=\"#FFFFFF\" size=\"5\">Holiday ");
					out.println("Packages </font></a></div></td>");
                    out.println("<td width=\"11%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"faq.htm\"><font color=\"#FFFFFF\" size=\"5\">FAQs</font></a></div></td>");
                    out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"register.htm\"><font color=\"#FFFFFF\" size=\"5\">Register Yourself </font></a></div></td>");
                    out.println("<td width=\"15%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"aboutus.htm\"><font color=\"#FFFFFF\" size=\"5\">About ");
					out.println("Us</font></a></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td colspan=\"6\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr bgcolor=\"#0000CC\"> ");
                    out.println("<td width=\"22%\" bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"acc.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
					out.println("Accommodation</font></a></div></td>");
                    out.println("<td width=\"21%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travel.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
					out.println("Traveling Means</font></a></div>");
					out.println("<div align=\"center\"></div></td>");
                    out.println("<td width=\"25%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travelguide.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
					out.println("Guide</font></a></div></td>");
                    out.println("<td width=\"32%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travelinsurance.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
					out.println("Insurance</font></a></div></td>");
					out.println("</tr>");
					out.println("</table></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<h1 align=\"center\"><font color=\"#660033\">Accomodation Facilities </font></h1>");
					out.println("<table width=\"733\" height=\"304\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
					out.println("<tr> ");
					out.println("<td height=\"33\" colspan=\"2\"><div align=\"center\"><img src=\"images/palmsprings_goa1.jpg\" width=\"155\" height=\"119\"><img src=\"images/north-india-hotels.jpg\" width=\"101\" height=\"119\"><img src=\"images/south-india-hotel.jpg\" width=\"101\" height=\"119\"></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td width=\"145\" height=\"242\" valign=\"top\" bgcolor=\"#0099FF\"> ");
					out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr>");
					out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\">");
					out.println("<div align=\"center\"><strong><a href=\"top15.htm\">Some Top Guest houses in India </a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\">");
                    out.println("<div align=\"center\"><strong><a href=\"loginhotel.htm\">Book Hotel/Lodging</a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"><div align=\"center\"><strong><span class=\"style12\"><a href=\"cancelhotel.htm\">Cancel Reservation</a></span></strong></div>            <div align=\"center\"></div>");
					out.println("<div align=\"center\"></div></td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\">");
					out.println("<div align=\"center\"><strong><a href=\"www.Hotels%20in%20India,%20Indian%20Hotels,%20India%20Hotels%20Directory%20-%20By%20Destinationindia_com.htm\">Hotels in India </a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\">");
					out.println("<div align=\"center\"><strong><a href=\"rates.htm\">Check Rates </a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"><div align=\"center\"><strong><a href=\"faqhotel.htm\">FAQ's</a></strong></div></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<p class=\"style11\"><img src=\"images/raj_banner.gif\" width=\"140\" height=\"145\"></p>");
					out.println("<p class=\"style11\">&nbsp;</p></td >");
					out.println("<td width=\"588\"><table width=\"100%\" height=\"331\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"\">");
					out.println("<tr bgcolor=\"#FFCCFF\"> ");
					out.println("<td height=\"49\" colspan=\"2\"> <div align=\"center\">");
					out.println("<p><font color=\"#660033\" size=\"5\">Online ");
					out.println("Hotel Booking</font><font color=\"#660033\" size=\"5\">.</font></p>");
					out.println("<p><strong><font color=\"#660033\" size=\"5\">Invalid Password!!!</font></strong></p>");
					out.println("</div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td width=\"70%\"><table width=\"100%\" height=\"220\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
					out.println("<tr bgcolor=\"#FFCCFF\">");
					out.println("<td colspan=\"2\">");
					out.println("<div align=\"center\"><em><strong><font color=\"#660000\" size=\"5\">Try Again!!! </font></strong></em></div></td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td width=\"51%\"><div align=\"center\"><strong>Login ID</strong></div></td>");
					out.println("<td width=\"49%\"><div align=\"center\">");
					out.println("<input name=\"loginid\" type=\"text\" id=\"loginid3\">");
					out.println("</div></td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td><div align=\"center\"><strong>Password</strong></div></td>");
					out.println("<td><div align=\"center\">");
					out.println("<input name=\"pswd\" type=\"password\" id=\"password\">");
					out.println("</div></td>");
					out.println("</tr>");
					out.println("<tr bgcolor=\"#FFCCFF\">");
					out.println("<td height=\"72\" colspan=\"2\">");
					out.println("<div align=\"center\" >");
					out.println("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"147\" height=\"34\">");
					out.println("<param name=\"movie\" value=\"images/loginhotel.swf\">");
					out.println("<param name=\"quality\" value=\"high\">");
					out.println("<param name=\"bgcolor\" value=\"#FFCCFF\">");
					out.println("<embed src=\"images/loginhotel.swf\" quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" width=\"147\" height=\"34\" bgcolor=\"#FFCCFF\"></embed>");
					out.println("</object>");
					out.println("</div></td>");
					out.println("</tr>");
					out.println("</table></td>");
					out.println("<td width=\"30%\"><img src=\"images/nizmar_resort1.jpg\" width=\"190\" height=\"147\"></td>");
					out.println("</tr>");
					out.println("</table></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<p align=\"center\">&nbsp;</p>");
					out.println("<hr size=1 width=\"70%\">");
                    out.println("<p align=\"center\"><a href=\"top15.htm\">Top 15 Guest houses in India</a>| <a href=\"loginhotel.htm\">Book Hotel/Lodging</a>| <a href=\"dguide.htm\">Cancel Reservation|</a> <a href=\"www.Hotels%20in%20India,%20Indian%20Hotels,%20India%20Hotels%20Directory%20-%20By%20Destinationindia_com.htm\">Hotels in India</a>|<a href=\"rates.htm\">Check Rates|</a> <a href=\"faqhotel.htm\">FAQ's </a></p>");
					out.println("<div align=\"center\"><FONT face=\"Arial, Helvetica, sans-serif\"><A ");
                    out.println("href=\"home.htm\"><FONT ");
					out.println("size=3>Home</FONT></A></FONT></div>");
					out.println("<hr size=1 width=\"70%\">");
					out.println("<p align=\"center\"><img src=\"images/twisting_cranberry_wht.jpg\" width=\"300\" height=\"30\"></p>");
					out.println("</body>");
					out.println("</html>");

            	}
            	else
            	{
            		out.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">");
					out.println("<html>");
					out.println("<head>");
					out.println("<title>Untitled Document</title>");
					out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
					out.println("<SCRIPT>");
					out.println("function doSubmit()");
					out.println("{");
					out.println("var strErrMsg;");
					out.println("strErrMsg = \"\";			");
					out.println("strErrMsg = doValidations();");
					out.println("if (strErrMsg == \"\" )");
					out.println("{				");
					out.println("document.mainform.action = 	\"hotelconfirm\";				");
					out.println("document.mainform.submit();");
					out.println("}");
					out.println("else");
					out.println("{alert(strErrMsg);}");
					out.println("}");
					out.println("function doValidations()");
					out.println("{");
					out.println("var ddIndex;");
					out.println("var strTemp;");
					out.println("var strFld;");
					out.println("var frmDoc;");
					out.println("var strErrMsg;");
					out.println("strErrMsg = \"\";");
					out.println("frmDoc = document.mainform;			");
					out.println("if(frmDoc.syy.value<=frmDoc.dyy.value)");
					out.println("{");
					out.println("if(frmDoc.smm.value<=frmDoc.dmm.value)");
					out.println("{");
					out.println("if(frmDoc.sdd.value>frmDoc.ddd.value)");
					out.println("strErrMsg = strErrMsg + \" Date is Incorrect\\n\";");
					out.println("}");
					out.println("else");
					out.println("strErrMsg = strErrMsg + \" Date is Incorrect\\n\";");
					out.println("}");
					out.println("else");
					out.println("strErrMsg = strErrMsg + \" Date is Incorrect\\n\";");
					out.println("strFld = frmDoc.cardno");
					out.println("if (strFld.value == \"\"|| strFld.value.length<4 || strFld.value.length >4 ) 		");
					out.println("strErrMsg = strErrMsg + \" Credit Crad No. is Invalid\\n\";");
					out.println("return strErrMsg;");
					out.println("}");
					out.println("</SCRIPT>");
					out.println("<style type=\"text/css\">");
					out.println("<!--");
					out.println(".style11 {color: #FFFFFF}");
					out.println(".style12 {color: #000000}");
					out.println("-->");
					out.println("</style>");
					out.println("</head>");
					out.println("<body>");
					out.println("<FORM name=mainform method=post>");
					out.println("<div align=\"center\">");
					out.println("<center>");
					out.println("<div align=\"center\">");
					out.println("<center>");
					out.println("<TABLE cellSpacing=0 cellPadding=0 width=750 border=0 style=\"border-collapse: collapse\" bordercolor=\"#111111\">");
					out.println("<TBODY>");
					out.println("<TR> ");
					out.println("<TD class=header>              <img src=\"images/frontpage.gif\" width=\"386\" height=\"71\"><img src=\"images/Hdr_AS_Seal.jpg\" width=\"289\" height=\"71\"><img src=\"images/1animated12-thumb[1].gif\" width=\"67\" height=\"50\"></TD>");
					out.println("</TR>");
					out.println("</TBODY>");
					out.println("</TABLE>");
					out.println("</center>");
					out.println("</div>");
					out.println("<p align=\"left\"><font face=\"arial\" size=\"2\"> ");
					out.println("<marquee behavior=\"scroll\" style=\"font-family: Courier New; color: #333300; text-decoration: blink; font-size: 18pt; font-style: italic; font-weight: bold\">");
					out.println("we share a visi<img src=\"images/Animsun.gif\" width=\"60\" height=\"48\">n ");
					out.println("</marquee>");
					out.println("</font></p>");
					out.println("</center>");
					out.println("</div>");
					out.println("<table width=\"97%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr bordercolor=\"#CCCCCC\" bgcolor=\"#000099\"> ");
                    out.println("<td width=\"10%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"home.htm\"><font color=\"#FFFFFF\" size=\"5\">Home</font></a></div></td>");
                    out.println("<td width=\"14%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"services.htm\"><font color=\"#FFFFFF\" size=\"5\">Services</font></a></div></td>");
                    out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"packagefinal.htm\"><font color=\"#FFFFFF\" size=\"5\">Holiday ");
					out.println("Packages </font></a></div></td>");
                    out.println("<td width=\"11%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"faq.htm\"><font color=\"#FFFFFF\" size=\"5\">FAQs</font></a></div></td>");
                    out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"register.htm\"><font color=\"#FFFFFF\" size=\"5\">Register Yourself </font></a></div></td>");
                    out.println("<td width=\"15%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"aboutus.htm\"><font color=\"#FFFFFF\" size=\"5\">About ");
					out.println("Us</font></a></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td colspan=\"6\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr bgcolor=\"#0000CC\"> ");
                    out.println("<td width=\"22%\" bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"acc.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
					out.println("Accommodation</font></a></div></td>");
                    out.println("<td width=\"21%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travel.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
					out.println("Traveling Means</font></a></div>");
					out.println("<div align=\"center\"></div></td>");
                    out.println("<td width=\"25%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travelguide.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
					out.println("Guide</font></a></div></td>");
                    out.println("<td width=\"32%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travelinsurance.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
					out.println("Insurance</font></a></div></td>");
					out.println("</tr>");
					out.println("</table></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<h1 align=\"center\"><font color=\"#660033\">Accomodation Facilities </font></h1>");
					out.println("<table width=\"733\" height=\"322\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
					out.println("<tr> ");
					out.println("<td height=\"33\" colspan=\"2\"><div align=\"center\"><img src=\"images/palmsprings_goa1.jpg\" width=\"155\" height=\"119\"><img src=\"images/north-india-hotels.jpg\" width=\"101\" height=\"119\"><img src=\"images/south-india-hotel.jpg\" width=\"101\" height=\"119\"></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td width=\"145\" height=\"289\" valign=\"top\" bgcolor=\"#0099FF\">    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr>");
					out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\">");
					out.println("<div align=\"center\"><strong><a href=\"top15.htm\">SomeTop Guest houses in India </a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\">");
					out.println("<div align=\"center\"><strong><a href=\"loginhotel.htm\">Book Hotel/Lodging</a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"><strong><span class=\"style12\"><a href=\"cancelhotel.htm\">Cancel Reservation </a></span></strong>");
					out.println("<div align=\"center\"></div></td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\">");
					out.println("<div align=\"center\"><strong><a href=\"www.Hotels%20in%20India,%20Indian%20Hotels,%20India%20Hotels%20Directory%20-%20By%20Destinationindia_com.htm\">Hotels in India </a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\">");
					out.println("<div align=\"center\"><strong><a href=\"rates.htm\">Check Rates </a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"><div align=\"center\"><strong><a href=\"faqhotel.htm\">FAQ's</a></strong></div></td>");
					out.println("</tr>");
					out.println("</table>      ");
					out.println("<p><img src=\"images/raj_banner.gif\" width=\"144\" height=\"145\"></p>    <p class=\"style11\">&nbsp;</p></td >");
					out.println("<td width=\"588\">      <table width=\"100%\" height=\"312\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"images/airfare_search_bg_big.gif\">");
					out.println("<tr bgcolor=\"#FFCCFF\">");
					out.println("<td colspan=\"2\">");
					out.println("<div align=\"center\"><font color=\"#660033\" size=\"5\">HotelBooking Form</font></div></td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td width=\"60%\" height=\"34\"><div align=\"left\"><font size=\"4\"> Your Customer ID</font></div></td>");
					out.println("<td width=\"40%\">");
					out.println("<strong>");
					out.println("<input name=\"loginid\" type=\"text\" id=\"loginid\" value=\""+loginid+"\" >");
					out.println("</strong></td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td height=\"33\"><div align=\"left\"><font size=\"4\">Type of accomodation </font></div></td>");
					out.println("<td><select name=\"type\" id=\"type\">");
					out.println("<option value=\"GH\">Guest house</option>");
					out.println("<option value=\"1S\">1 Star Hotel</option>");
					out.println("<option value=\"23S\">2/3 Star Hotel</option>");
					out.println("<option value=\"5S\">5 Star Hotel</option>");
					out.println("<option value=\"PG\">P.G Accomodation</option>");
					out.println("</select>");
					out.println("</td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td><div align=\"left\"><font size=\"4\">Check-in Date</font></div></td>");
					out.println("<td><input name=\"checkindate\" type=\"date\">");
					out.println("</td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td><font size=\"4\">Check-out Date</font></td>");
					out.println("<td><input name=\"checkout\" type=\"date\">");
					
					out.println("</td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td><font size=\"4\">Hotel Destination</font></td>");
					out.println("<td><select name=\"dest\" id=\"dest\">");
					out.println("<option value=\"ND\" selected>New Delhi</option>");
					out.println("<option value=\"KL\">Kolkata</option>");
					out.println("<option value=\"CH\">Chennai</option>");
					out.println("<option value=\"MB\">Mumbai</option>");
					out.println("<option value=\"BG\">Banglore</option>");
					out.println("<option value=\"AG\">Agra</option>");
					out.println("<option value=\"AH\">Ahmedabad</option>");
					out.println("<option value=\"HD\">Hydrebad</option>");
					out.println("<option value=\"ID\">Indore</option>");
					out.println("<option value=\"RC\">Ranchi</option>");
					out.println("</select></td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td><div align=\"left\"><font size=\"4\">Number of rooms </font></div></td>");
					out.println("<td><select name=\"rooms\" id=\"rooms\">");
					out.println("<option value=\"1\">1</option>");
					out.println("<option value=\"2\">2</option>");
					out.println("<option value=\"3\">3</option>");
					out.println("</select></td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td><div align=\"left\"><font size=\"4\">Enter last four digits of your Credit Card No.</font></div></td>");
					out.println("<td><input name=\"cardno\" type=\"password\" id=\"cardno\" size=\"8\" maxlength=\"4\"></td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td><div align=\"left\"></div></td>");
					out.println("<td>&nbsp;</td>");
					out.println("</tr>");
					out.println("<tr>");
					out.println("<td height=\"20\"><font size=\"4\">&nbsp;</font></td>");
					out.println("<td>&nbsp;");
					out.println("</td>");
					out.println("</tr>");
					out.println("</table>      <p align=\"center\">");
					out.println("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"103\" height=\"24\">");
					out.println("<param name=\"BGCOLOR\" value=\"\">");
					out.println("<param name=\"movie\" value=\"images/bookhotel.swf\">");
					out.println("<param name=\"quality\" value=\"high\">");
					out.println("<embed src=\"images/bookhotel.swf\" quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" width=\"103\" height=\"24\" ></embed>");
					out.println("</object>");
					out.println("</p>      ");
					out.println("</td>");
					out.println("</tr></table>");
					out.println("<p>&nbsp;</p>");
					out.println("<hr size=1 width=\"70%\">");
					out.println("<p align=\"center\"><a href=\"top15.htm\">SomeTop Guest houses in India</a>| <a href=\"loginhotel.htm\">Book Hotel/Lodging</a>| <a href=\"cancelhotel.htm\">Cancel Reservation| </a><a href=\"www.Hotels%20in%20India,%20Indian%20Hotels,%20India%20Hotels%20Directory%20-%20By%20Destinationindia_com.htm\">Hotels in India</a>|<a href=\"rates.htm\">Check Rates|</a> <a href=\"faqhotel.htm\">FAQ's </a></p>");
					out.println("<p align=\"center\"><FONT face=\"Arial, Helvetica, sans-serif\"><A ");
                    out.println("href=\"home.htm\"><FONT ");
					out.println("size=3>Home</FONT></A></FONT></p>");
					out.println("<hr size=1 width=\"70%\">");
					out.println("<p align=\"center\"><img src=\"images/twisting_cranberry_wht.jpg\" width=\"300\" height=\"30\"></p>");
					out.println("<p align=\"center\">&nbsp;</p>");
					out.println("</body></html>");

				
            	}
            }
            else
            {
            	out.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">");
				out.println("<html>");
				out.println("<head>");
				out.println("<title>Untitled Document</title>");
				out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
				out.println("<SCRIPT>");
				out.println("/*function doClear()");
				out.println("{		 ");
				out.println("document.mainform.loginid.value =\"\"");
				out.println("document.mainform.password.value = \"\";");
				out.println("}*/");
				out.println("function doSubmit()");
				out.println("{");
				out.println("var strErrMsg;");
				out.println("strErrMsg = \"\";			");
				out.println("strErrMsg = doValidations();");
				out.println("if (strErrMsg == \"\" )");
				out.println("{				");
				out.println("document.mainform.action = \"hotelbooking\";		");
				out.println("document.mainform.submit();");
				out.println("}");
				out.println("else");
				out.println("{alert(strErrMsg);}");
				out.println("}");
				out.println("function doValidations()");
				out.println("{");
				out.println("var ddIndex;");
				out.println("var strTemp;");
				out.println("var strFld;");
				out.println("var frmDoc;");
				out.println("var strErrMsg;");
				out.println("strErrMsg = \"\";");
				out.println("frmDoc = document.mainform;			");
				out.println("strFld = frmDoc.loginid");
				out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"login-id can not be null\\n\";			");
				out.println("strFld = frmDoc.pswd");
				out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"password can not be null\\n\";	");
				out.println("return strErrMsg;");
				out.println("}");
				out.println("</SCRIPT>");
				out.println("<style type=\"text/css\">");
				out.println("<!--");
				out.println(".style11 {color: #FFFFFF}");
				out.println("-->");
				out.println("</style>");
				out.println("</head>");
				out.println("<body>");
				out.println("<FORM name=mainform method=post>");
				out.println("<div align=\"center\">");
				out.println("<center>");
				out.println("<div align=\"center\">");
				out.println("<center>");
				out.println("<TABLE cellSpacing=0 cellPadding=0 width=750 border=0 style=\"border-collapse: collapse\" bordercolor=\"#111111\">");
				out.println("<TBODY>");
				out.println("<TR> ");
				out.println("<TD class=header><img src=\"images/frontpage.gif\" width=\"386\" height=\"71\"> <img src=\"images/Hdr_AS_Seal.jpg\" width=\"289\" height=\"71\"><img src=\"images/1animated12-thumb[1].gif\" width=\"67\" height=\"50\"></TD>");
				out.println("</TR>");
				out.println("</TBODY>");
				out.println("</TABLE>");
				out.println("</center>");
				out.println("</div>");
				out.println("<p align=\"left\"><font face=\"arial\" size=\"2\"> ");
				out.println("<marquee behavior=\"scroll\" style=\"font-family: Courier New; color: #333300; text-decoration: blink; font-size: 18pt; font-style: italic; font-weight: bold\">");
				out.println("we share a visi<img src=\"images/Animsun.gif\" width=\"48\" height=\"41\">n ");
				out.println("</marquee>");
				out.println("</font></p>");
				out.println("</center>");
				out.println("</div>");
				out.println("<table width=\"97%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
				out.println("<tr bordercolor=\"#CCCCCC\" bgcolor=\"#000099\"> ");
                out.println("<td width=\"10%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"home.htm\"><font color=\"#FFFFFF\" size=\"5\">Home</font></a></div></td>");
                out.println("<td width=\"14%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"services.htm\"><font color=\"#FFFFFF\" size=\"5\">Services</font></a></div></td>");
                out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"packagefinal.htm\"><font color=\"#FFFFFF\" size=\"5\">Holiday ");
				out.println("Packages </font></a></div></td>");
                out.println("<td width=\"11%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"faq.htm\"><font color=\"#FFFFFF\" size=\"5\">FAQs</font></a></div></td>");
                out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"register.htm\"><font color=\"#FFFFFF\" size=\"5\">Register Yourself </font></a></div></td>");
                out.println("<td width=\"15%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"aboutus.htm\"><font color=\"#FFFFFF\" size=\"5\">About ");
				out.println("Us</font></a></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td colspan=\"6\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
				out.println("<tr bgcolor=\"#0000CC\"> ");
                out.println("<td width=\"22%\" bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"acc.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
				out.println("Accommodation</font></a></div></td>");
                out.println("<td width=\"21%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travel.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
				out.println("Traveling Means</font></a></div>");
				out.println("<div align=\"center\"></div></td>");
                out.println("<td width=\"25%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travelguide.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
				out.println("Guide</font></a></div></td>");
                out.println("<td width=\"32%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travelinsurance.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
				out.println("Insurance</font></a></div></td>");
				out.println("</tr>");
				out.println("</table></td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("<h1 align=\"center\"><font color=\"#660033\">Accomodation Facilities </font></h1>");
				out.println("<table width=\"733\" height=\"304\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
				out.println("<tr> ");
				out.println("<td height=\"33\" colspan=\"2\"><div align=\"center\"><img src=\"images/palmsprings_goa1.jpg\" width=\"155\" height=\"119\"><img src=\"images/north-india-hotels.jpg\" width=\"101\" height=\"119\"><img src=\"images/south-india-hotel.jpg\" width=\"101\" height=\"119\"></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td width=\"145\" height=\"242\" valign=\"top\" bgcolor=\"#0099FF\"> ");
				out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
				out.println("<tr>");
				out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\">");
				out.println("<div align=\"center\"><strong><a href=\"top15.htm\">Some Top Guest houses in India </a></strong></div></td>");
				out.println("</tr>");
				out.println("<tr>");
				out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\">");
                out.println("<div align=\"center\"><strong><a href=\"loginhotel.htm\">Book Hotel/Lodging</a></strong></div></td>");
				out.println("</tr>");
				out.println("<tr>");
				out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\">");
                out.println("<div align=\"center\"><strong><span class=\"style12\"><a href=\"cancelhotel.htm\">Cancel Reservation</a> </span></strong></div></td>");
				out.println("</tr>");
				out.println("<tr>");
				out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\">");
				out.println("<div align=\"center\"><strong><a href=\"www.Hotels%20in%20India,%20Indian%20Hotels,%20India%20Hotels%20Directory%20-%20By%20Destinationindia_com.htm\">Hotels in India </a></strong></div></td>");
				out.println("</tr>");
				out.println("<tr>");
				out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\">");
				out.println("<div align=\"center\"><strong><a href=\"rates.htm\">Check Rates </a></strong></div></td>");
				out.println("</tr>");
				out.println("<tr>");
				out.println("<td bgcolor=\"#FFFFCC\" class=\"style11\"><div align=\"center\"><strong><a href=\"faqhotel.htm\">FAQ's</a></strong></div></td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("<p class=\"style11\"><img src=\"images/raj_banner.gif\" width=\"140\" height=\"145\"></p>");
				out.println("<p class=\"style11\">&nbsp;</p></td >");
				out.println("<td width=\"588\"><table width=\"100%\" height=\"331\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"\">");
				out.println("<tr bgcolor=\"#FFCCFF\"> ");
				out.println("<td height=\"49\" colspan=\"2\"> <div align=\"center\">");
				out.println("<p><font color=\"#660033\" size=\"5\">Online ");
				out.println("Hotel Booking</font><font color=\"#660033\" size=\"5\">.</font></p>");
				out.println("<p><strong><font color=\"#660033\" size=\"5\">Invalid LoginID!!!</font></strong></p>");
				out.println("</div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td width=\"70%\"><table width=\"100%\" height=\"220\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
				out.println("<tr bgcolor=\"#FFCCFF\">");
				out.println("<td colspan=\"2\">");
				out.println("<div align=\"center\"><em><strong><font color=\"#660000\" size=\"5\">Try Again!!! </font></strong></em></div></td>");
				out.println("</tr>");
				out.println("<tr>");
				out.println("<td width=\"51%\"><div align=\"center\"><strong>Login ID</strong></div></td>");
				out.println("<td width=\"49%\"><div align=\"center\">");
				out.println("<input name=\"loginid\" type=\"text\" id=\"loginid3\">");
				out.println("</div></td>");
				out.println("</tr>");
				out.println("<tr>");
				out.println("<td><div align=\"center\"><strong>Password</strong></div></td>");
				out.println("<td><div align=\"center\">");
				out.println("<input name=\"pswd\" type=\"password\" id=\"password\">");
				out.println("</div></td>");
				out.println("</tr>");
				out.println("<tr bgcolor=\"#FFCCFF\">");
				out.println("<td height=\"72\" colspan=\"2\">");
				out.println("<div align=\"center\" >");
				out.println("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"147\" height=\"34\">");
				out.println("<param name=\"movie\" value=\"images/loginhotel.swf\">");
				out.println("<param name=\"quality\" value=\"high\">");
				out.println("<param name=\"bgcolor\" value=\"#FFCCFF\">");
				out.println("<embed src=\"images/loginhotel.swf\" quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" width=\"147\" height=\"34\" bgcolor=\"#FFCCFF\"></embed>");
				out.println("</object>");
				out.println("</div></td>");
				out.println("</tr>");
				out.println("</table></td>");
				out.println("<td width=\"30%\"><img src=\"images/nizmar_resort1.jpg\" width=\"190\" height=\"147\"></td>");
				out.println("</tr>");
				out.println("</table></td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("<p align=\"center\">&nbsp;</p>");
				out.println("<hr size=1 width=\"70%\">");
				out.println("<p align=\"center\"><a href=\"top15.htm\">Some Top Guest houses in India</a>| <a href=\"loginhotel.htm\">Book Hotel/Lodging</a>| <a href=\"cancelhotel.htm\">Cancel Reservation| </a>|  <a href=\"www.Hotels%20in%20India,%20Indian%20Hotels,%20India%20Hotels%20Directory%20-%20By%20Destinationindia_com.htm\">Hotels in India</a>|<a href=\"rates.htm\">Check Rates|</a> <a href=\"faqhotel.htm\">FAQ's </a></p>");
				out.println("<div align=\"center\"><FONT face=\"Arial, Helvetica, sans-serif\"><A ");
                out.println("href=\"home.htm\"><FONT ");
				out.println("size=3>Home</FONT></A></FONT></div>");
				out.println("<hr size=1 width=\"70%\">");
				out.println("<p align=\"center\"><img src=\"images/twisting_cranberry_wht.jpg\" width=\"300\" height=\"30\"></p>");
				out.println("</body>");
				out.println("</html>");
				
				
            }
            }catch(Exception e){
            	out.println("Exception"+e.getMessage()+e.toString());
            }
            finally{
            	try{
            		if(c!=null)
            			c.close();
            	}catch(Exception e){
            		out.println("Exception closing the connection"+e.getMessage());
            	}
            }
   		}
   }
   
