import java.io.*;

import javax.servlet.*;
import javax.servlet.http.*;

import com.jdbc.DB;

import java.sql.*;

public class insurancebooking extends HttpServlet {
    
    public void init(ServletConfig config)
        throws ServletException {
            super.init(config);
        }
    
    public void doGet(HttpServletRequest request, HttpServletResponse response)
    throws IOException, ServletException
    {
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();
        out.println("<html>");
        out.println("<body>");
        out.println("<head>");
        out.println("<title>Hello World!</title>");
        out.println("</head>");
        out.println("<body>");
        out.println("<h1>Hello World!</h1>");
        out.println("Your request was"+ request.getMethod()+"\n");
        out.println("</body>");
        out.println("</html>");
    }
   public String getContext(String param) {
		ServletContext sc=getServletContext();
		String prop=sc.getInitParameter(param);
		prop=prop!=null&&prop.length()>0?""+prop:"";
		System.out.println("Contex param:"+prop);
		return prop;
	}
    public void doPost(HttpServletRequest request, HttpServletResponse response)
    throws IOException, ServletException
    {
        Connection c=null;
        String loginid=request.getParameter("loginid");
        String pswd=request.getParameter("pswd");
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();
        try{
   	     	Connection conn=DB.getConnect();
   	     	Statement st=conn.createStatement();
            String query = new String("select * from Customer where loginid='" +loginid+ "'" ); 
            ResultSet rs= st.executeQuery(query);
            if(rs.next())
            {
              if(!pswd.equals(rs.getString("pswd")))
                {

out.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">");
out.println("<html>");
out.println("<head>");
out.println("<title>invalipasswordins</title>");
out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
out.println("<SCRIPT>");
out.println("function doClear()");
out.println("{       ");
out.println("}");
out.println("function doSubmit()");
out.println("{");
out.println("var strErrMsg;         ");
out.println("strErrMsg = \"\";          ");
out.println("strErrMsg = doValidations();");
out.println("if (strErrMsg == \"\" )");
out.println("{                          ");
out.println("document.mainform.action = \"insurancebooking\"  ;                  ");
out.println("document.mainform.submit();");
out.println("}");
out.println("else");
out.println("{alert(strErrMsg);}");
out.println("}");
out.println("function doValidations()");
out.println("{         ");
out.println("var ddIndex;");
out.println("var strTemp;");
out.println("var strFld;");
out.println("var frmDoc;");
out.println("var strErrMsg;");
out.println("strErrMsg = \"\";");
out.println("frmDoc = document.mainform;            ");
out.println("strFld = frmDoc.loginid");
out.println("if (strFld.value == \"\")strErrMsg = strErrMsg + \"Please enter loginid\\n\";");
out.println("strFld = frmDoc.pswd");
out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"Please enter password\\n\";                                             ");
out.println("return strErrMsg;");
out.println("}");
out.println("</SCRIPT>");
out.println("</head>");
out.println("<body bgcolor=\"#FFFFFF\">");
out.println("<FORM name=mainform method=post>");
out.println("<div align=\"center\">");
out.println("<center>");
out.println("<div align=\"center\">");
out.println("<center>");
out.println("<TABLE cellSpacing=0 cellPadding=0 width=750 border=0 style=\"border-collapse: collapse\" bordercolor=\"#111111\">");
out.println("<TBODY>");
out.println("<TR> ");
out.println("<TD class=header><img src=\"images/frontpage.gif\" alt=\"\" width=\"386\" height=\"71\"><img src=\"images/Hdr_AS_Seal.jpg\" width=\"289\" height=\"71\"> ");
out.println("<img src=\"images/1animated12-thumb%5B1%5D.gif\" width=\"67\" height=\"50\"> ");
out.println("</TD>");
out.println("</TR>");
out.println("</TBODY>");
out.println("</TABLE>");
out.println("</center>");
out.println("</div>");
out.println("<p align=\"left\"><font face=\"arial\" size=\"2\"> ");
out.println("<marquee behavior=\"scroll\" style=\"font-family: Courier New; color: #333300; text-decoration: blink; font-size: 18pt; font-style: italic; font-weight: bold\">");
out.println("we share a visi<img src=\"images/Animsun.gif\" width=\"50\" height=\"26\">n ");
out.println("</marquee>");
out.println("</font></p>");
out.println("</center>");
out.println("</div>");
out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
out.println("<tr bordercolor=\"#CCCCCC\" bgcolor=\"#000099\"> ");
out.println("<td width=\"10%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"home.htm\"><font color=\"#FFFFFF\" size=\"5\">Home</font></a></div></td>");
out.println("<td width=\"14%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"services.htm\"><font color=\"#FFFFFF\" size=\"5\">Services</font></a></div></td>");
out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"packagefinal.htm\"><font color=\"#FFFFFF\" size=\"5\">Holiday ");
out.println("Packages </font></a></div></td>");
out.println("<td width=\"11%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"faq.htm\"><font color=\"#FFFFFF\" size=\"5\">FAQs</font></a></div></td>");
out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"register.htm\"><font color=\"#FFFFFF\" size=\"5\">Register ");
out.println("Yourself</font></a></div></td>");
out.println("<td width=\"15%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"aboutus.htm\"><font color=\"#FFFFFF\" size=\"5\">About ");
out.println("Us</font></a></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td colspan=\"6\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
out.println("<tr bgcolor=\"#0000CC\"> ");
out.println("<td width=\"21%\" height=\"20\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"acc.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
out.println("Accommodation</font></a></div></td>");
out.println("<td width=\"24%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travel.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
out.println("Traveling Means</font></a></div>");
out.println("<div align=\"center\"></div></td>");
out.println("<td width=\"25%\" bgcolor=\"#0000CC\"> ");
out.println("<div align=\"center\"><a href=\"travelguide.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
out.println("Guide</font></a></div></td>");
out.println("<td width=\"30%\" bgcolor=\"#3333FF\"> ");
out.println("<div align=\"center\"><a href=\"travelinsurance.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
out.println("Insurance</font></a></div></td>");
out.println("</tr>");
out.println("</table></td>");
out.println("</tr>");
out.println("</table>");
out.println("<p align=\"center\"><span class=\"style1\"><u><font color=\"#660033\" size=\"6\"><strong>Travel ");
out.println("Insurance </strong></font></u></span></p>");
out.println("<div align=\"center\"></div>");
out.println("<table width=\"100%\" border=\"0\" cellspacing=\"1\" cellpadding=\"0\">");
out.println("<tr>");
out.println("<td width=\"47%\" height=\"318\"> ");
out.println("<table width=\"18%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
out.println("<tr> ");
out.println("<td width=\"45%\" height=\"55\" bgcolor=\"#333333\">");
out.println("<div align=\"center\"><img src=\"images/supersurpriceban.jpg\" width=\"356\" height=\"55\"> ");
out.println("</div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td height=\"263\"> ");
out.println("<table width=\"46%\" border=\"0\" cellspacing=\"1\" cellpadding=\"0\">");
out.println("<tr> ");
out.println("<td width=\"46%\" height=\"260\"><img src=\"images/Southern%20GP59.jpg\" width=\"170\" height=\"261\"></td>");
out.println("<td width=\"54%\"><table width=\"47%\" height=\"260\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\">");
out.println("<tr> ");
out.println("<td height=\"137\"><img src=\"images/cruises-celebrity.jpg\" width=\"201\" height=\"157\"></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td height=\"100\"> ");
out.println("<div align=\"center\"><img src=\"images/vitara.jpg\" width=\"200\" height=\"100\"></div></td>");
out.println("</tr>");
out.println("</table></td>");
out.println("</tr>");
out.println("</table></td>");
out.println("</tr>");
out.println("</table>");
out.println("</td>");
out.println("<td width=\"53%\" bgcolor=\"#FFCCFF\">");
out.println("<table width=\"100%\" height=\"233\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
out.println("<tr bgcolor=\"#FFCCFF\"> ");
out.println("<td colspan=\"2\"> <div align=\"center\"><em><strong><font color=\"#660000\" size=\"5\">Invalid ");
out.println("password try again!!!</font></strong></em></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td width=\"41%\" bgcolor=\"#FFCCFF\"> <div align=\"center\"><strong>Login ");
out.println("ID</strong></div></td>");
out.println("<td width=\"59%\" bgcolor=\"#FFCCFF\"> <div align=\"center\"> ");
out.println("<input name=\"loginid\" type=\"text\" id=\"login\">");
out.println("</div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFCCFF\"> <div align=\"center\"><strong>Password</strong></div></td>");
out.println("<td bgcolor=\"#FFCCFF\"> <div align=\"center\"> ");
out.println("<input name=\"pswd\" type=\"password\" id=\"password\">");
out.println("</div></td>");
out.println("</tr>");
out.println("<tr bgcolor=\"#FFCCFF\"> ");
out.println("<td height=\"88\" colspan=\"2\"> <div align=\"center\" > <strong> ");
out.println("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"147\" height=\"34\">");
out.println("<param name=\"movie\" value=\"images/travellogin.swf\">");
out.println("<param name=\"quality\" value=\"high\">");
out.println("<param name=\"BGCOLOR\" value=\"#FFCCFF\">");
out.println("<embed src=\"images/travellogin.swf\" width=\"147\" height=\"34\" quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" bgcolor=\"#FFCCFF\" ></embed> ");
out.println("</object>");
out.println("</strong></div></td>");
out.println("</tr>");
out.println("</table>");
out.println("</td>");
out.println("</tr>");
out.println("</table>");
out.println("<HR align=center noShade>");
out.println("<p align=\"center\"><font size=\"4\" face=\"Arial\"><a href=\"home.htm\">Home</a> | <a href=\"services.htm\">Services</a></font></p>");
out.println("<HR align=center noShade>");
out.println("<p>&nbsp;</p>");
out.println("</body>");
out.println("</html>");

                   
                }

               else
                 {

out.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">");
out.println("<html>");
out.println("<head>");
out.println("<title>insurancebooking</title>");
out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
out.println("<SCRIPT>");
out.println("function doClear()");
out.println("{       ");
out.println("document.mainform.name.value = \"\";");
out.println("document.mainform.age.value = \"\";");
out.println("document.mainform.sex.value = \"\";");
out.println("document.mainform.ticketno.value = \"\";");
out.println("document.mainform.inamount.value = \"\";       ");
out.println("document.mainform.cardno.value = \"\";");
out.println("}");
out.println("function doSubmit()");
out.println("{");
out.println("var strErrMsg;         ");
out.println("strErrMsg = \"\";          ");
out.println("strErrMsg = doValidations();");
out.println("if (strErrMsg == \"\" )");
out.println("{                          ");
out.println("document.mainform.action = \"insuranceconfirm\"  ;                      ");
out.println("document.mainform.submit();");
out.println("}");
out.println("else");
out.println("{alert(strErrMsg);}");
out.println("}");
out.println("function doValidations()");
out.println("{         ");
out.println("var ddIndex;");
out.println("var strTemp;");
out.println("var strFld;");
out.println("var frmDoc;");
out.println("var strErrMsg;");
out.println("strErrMsg = \"\";");
out.println("frmDoc = document.mainform;            ");
out.println("strFld = frmDoc.name");
out.println("if (strFld.value == \"\")strErrMsg = strErrMsg + \"Please enter the name\\n\";");
out.println("strFld = frmDoc.age");
out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"Please enter age\\n\";");
out.println("strFld = frmDoc.ticketno");
out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"Please enter ticket no/ Req. no.\\n\";");
out.println("strFld = frmDoc.inamount");
out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"Please enter insurance amount\\n\";");
out.println("strFld = frmDoc.cardno");
out.println("if (strFld.value == \"\"|| strFld.value.length<4 || strFld.value.length >4 ) ");
out.println("strErrMsg = strErrMsg + \"Please enter credit card no\\n\"; ");
out.println("return strErrMsg;");
out.println("}");
out.println("</SCRIPT>");
out.println("</head>");
out.println("<body bgcolor=\"#FFFFFF\">");
out.println("<FORM name=mainform method=post>");
out.println("<div align=\"center\">");
out.println("<center>");
out.println("<div align=\"center\">");
out.println("<center>");
out.println("<TABLE cellSpacing=0 cellPadding=0 width=750 border=0 style=\"border-collapse: collapse\" bordercolor=\"#111111\">");
out.println("<TBODY>");
out.println("<TR> ");
out.println("<TD class=header><img src=\"images/frontpage.gif\" alt=\"\" width=\"386\" height=\"71\"><img src=\"images/Hdr_AS_Seal.jpg\" width=\"289\" height=\"71\"> ");
out.println("<img src=\"images/1animated12-thumb%5B1%5D.gif\" width=\"67\" height=\"50\"> ");
out.println("</TD>");
out.println("</TR>");
out.println("</TBODY>");
out.println("</TABLE>");
out.println("</center>");
out.println("</div>");
out.println("<p align=\"left\"><font face=\"arial\" size=\"2\"> ");
out.println("<marquee behavior=\"scroll\" style=\"font-family: Courier New; color: #333300; text-decoration: blink; font-size: 18pt; font-style: italic; font-weight: bold\">");
out.println("we share a visi<img src=\"images/Animsun.gif\" width=\"50\" height=\"26\">n ");
out.println("</marquee>");
out.println("</font></p>");
out.println("</center>");
out.println("</div>");
out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
out.println("<tr bordercolor=\"#CCCCCC\" bgcolor=\"#000099\"> ");
out.println("<td width=\"10%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"home.htm\"><font color=\"#FFFFFF\" size=\"5\">Home</font></a></div></td>");
out.println("<td width=\"14%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"services.htm\"><font color=\"#FFFFFF\" size=\"5\">Services</font></a></div></td>");
out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"packagefinal.htm\"><font color=\"#FFFFFF\" size=\"5\">Holiday ");
out.println("Packages </font></a></div></td>");
out.println("<td width=\"11%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"faq.htm\"><font color=\"#FFFFFF\" size=\"5\">FAQs</font></a></div></td>");
out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"register.htm\"><font color=\"#FFFFFF\" size=\"5\">Register ");
out.println("Yourself</font></a></div></td>");
out.println("<td width=\"15%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"aboutus.htm\"><font color=\"#FFFFFF\" size=\"5\">About ");
out.println("Us</font></a></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td colspan=\"6\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
out.println("<tr bgcolor=\"#0000CC\"> ");
out.println("<td width=\"21%\" height=\"20\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"acc.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
out.println("Accommodation</font></a></div></td>");
out.println("<td width=\"24%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travel.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
out.println("Traveling Means</font></a></div>");
out.println("<div align=\"center\"></div></td>");
out.println("<td width=\"25%\" bgcolor=\"#0000CC\"> ");
out.println("<div align=\"center\"><a href=\"travelguide.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
out.println("Guide</font></a></div></td>");
out.println("<td width=\"30%\" bgcolor=\"#3333FF\"> ");
out.println("<div align=\"center\"><a href=\"travelinsurance.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
out.println("Insurance</font></a></div></td>");
out.println("</tr>");
out.println("</table></td>");
out.println("</tr>");
out.println("</table>");
out.println("<p align=\"center\"><span class=\"style1\"><u><font color=\"#660033\" size=\"6\"><strong>Travel ");
out.println("Insurance </strong></font><font color=\"#0000FF\" size=\"6\"></font></u></span></p>");
out.println("<div align=\"center\"></div>");
out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
out.println("<tr> ");
out.println("<td width=\"45%\" height=\"55\" valign=\"top\" bgcolor=\"#333333\"> ");
out.println("<div align=\"center\"><img src=\"images/supersurpriceban.jpg\" width=\"356\" height=\"55\"> ");
out.println("</div></td>");
out.println("<td width=\"55%\" rowspan=\"2\" valign=\"top\" bgcolor=\"#FFCCFF\"> ");
out.println("<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#660033\" background=\"airfare_search_bg_big.gif\">");
out.println("<tr bgcolor=\"#FFCCFF\"> ");
out.println("<td colspan=\"2\"> <div align=\"center\"> ");
out.println("<p><font color=\"#660033\" size=\"5\">Travel Insurance Form</font></p>");
out.println("</div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td width=\"71%\" bgcolor=\"#FFCCFF\"><font size=\"4\"> Enter Your Name</font></td>");
out.println("<td width=\"29%\" bgcolor=\"#FFCCFF\"> <INPUT name=\"name\" type=\"text\"class=if id=\"name\"  size=\"10\" maxlength=\"10\"> ");
out.println("</td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td height=\"20\" bgcolor=\"#FFCCFF\"><font size=\"4\">Age</font></td>");
out.println("<td bgcolor=\"#FFCCFF\"><B> ");
out.println("<input name=\"age\" type=\"text\" id=\"age\" size=\"2\">");
out.println("</B> </td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFCCFF\"><font size=\"4\">Sex</font></td>");
out.println("<td bgcolor=\"#FFCCFF\"><B> ");
out.println("<select name=\"sex\" id=\"sex\">");
out.println("<option value=\"M\" selected>M</option>");
out.println("<option value=\"F\">F</option>");
out.println("</select>");
out.println("</B></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFCCFF\"><font size=\"4\">Travelling means</font></td>");
out.println("<td bgcolor=\"#FFCCFF\"><select name=\"tm\" id=\"tm\">");
out.println("<option value=\"1\" selected>train</option>");
out.println("<option value=\"2\">flight</option>");
out.println("<option value=\"3\">car</option>");
out.println("<option value=\"4\">cruise</option>");
out.println("</select></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td height=\"22\" bgcolor=\"#FFCCFF\"><font size=\"4\">Ticket no./Req no.(First ");
out.println("Three Digits) </font></td>");
out.println("<td bgcolor=\"#FFCCFF\"><input name=\"ticketno\" type=\"text\" id=\"ticketno2\" size=\"3\" maxlength=\"3\"> ");
out.println("</td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFCCFF\"><font size=\"4\">Insurance amount</font></td>");
out.println("<td bgcolor=\"#FFCCFF\"><input name=\"inamount\" type=\"text\" id=\"inamount2\" size=\"6\"> ");
out.println("</td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFCCFF\"><font size=\"4\">Enter last four digits of your ");
out.println("Credit Card No.</font></td>");
out.println("<td bgcolor=\"#FFCCFF\"><input name=\"cardno\" type=\"text\" id=\"cardno2\" size=\"4\" maxlength=\"4\"> ");
out.println("</td>");
out.println("</tr>");
out.println("</table>");
out.println("<p align=\"center\" onClick=\"javascript:doSubmit();\"> ");
out.println("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"147\" height=\"34\">");
out.println("<param name=\"BGCOLOR\" value=\"#FFCCFF\">");
out.println("<param name=\"movie\" value=\"images/getinsurance.swf\">");
out.println("<param name=\"quality\" value=\"high\">");
out.println("<embed src=\"images/getinsurance.swf\" width=\"147\" height=\"34\" quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" bgcolor=\"#FFCCFF\" ></embed> ");
out.println("</object>");
out.println("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"147\" height=\"34\">");
out.println("<param name=\"movie\" value=\"images/inscleardata.swf\">");
out.println("<param name=\"quality\" value=\"high\">");
out.println("<param name=\"bgcolor\" value=\"#FFCCFF\">");
out.println("<embed src=\"images/inscleardata.swf\" quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" width=\"147\" height=\"34\" bgcolor=\"#FFCCFF\"></embed> ");
out.println("</object>");
out.println("</p></td>");
out.println("</tr>");
out.println("<tr>");
out.println("<td height=\"263\"> ");
out.println("<table width=\"100%\" border=\"0\" cellspacing=\"1\" cellpadding=\"0\">");
out.println("<tr>");
out.println("<td width=\"46%\" height=\"261\"><img src=\"images/Southern%20GP59.jpg\" width=\"170\" height=\"260\"></td>");
out.println("<td width=\"54%\"><table width=\"100%\" height=\"245\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\">");
out.println("<tr>");
out.println("<td height=\"141\"><img src=\"images/cruises-celebrity.jpg\" width=\"201\" height=\"157\"></td>");
out.println("</tr>");
out.println("<tr>");
out.println("<td height=\"101\"> ");
out.println("<div align=\"center\"><img src=\"images/vitara.jpg\" width=\"200\" height=\"100\"></div></td>");
out.println("</tr>");
out.println("</table></td>");
out.println("</tr>");
out.println("</table></td>");
out.println("</tr>");
out.println("</table>");
out.println("<HR align=center noShade>");
out.println("<p align=\"center\"><font size=\"4\" face=\"Arial\"><a href=\"home.htm\">Home</a> | <a href=\"services.htm\">Services</a></font></p>");
out.println("<HR align=center noShade>");
out.println("<p>&nbsp;</p>");
out.println("</body>");
out.println("</html>");


                 }
             }
            else
             {

out.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">");
out.println("<html>");
out.println("<head>");
out.println("<title>invalidloginins</title>");
out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
out.println("<SCRIPT>");
out.println("function doClear()");
out.println("{       ");
out.println("}");
out.println("function doSubmit()");
out.println("{");
out.println("var strErrMsg;         ");
out.println("strErrMsg = \"\";          ");
out.println("strErrMsg = doValidations();");
out.println("if (strErrMsg == \"\" )");
out.println("{                          ");
out.println("document.mainform.action = \"insurancebooking\"  ;                  ");
out.println("document.mainform.submit();");
out.println("}");
out.println("else");
out.println("{alert(strErrMsg);}");
out.println("}");
out.println("function doValidations()");
out.println("{         ");
out.println("var ddIndex;");
out.println("var strTemp;");
out.println("var strFld;");
out.println("var frmDoc;");
out.println("var strErrMsg;");
out.println("strErrMsg = \"\";");
out.println("frmDoc = document.mainform;            ");
out.println("strFld = frmDoc.loginid");
out.println("if (strFld.value == \"\")strErrMsg = strErrMsg + \"Please enter loginid\\n\";");
out.println("strFld = frmDoc.pswd");
out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"Please enter password\\n\";                                             ");
out.println("return strErrMsg;");
out.println("}");
out.println("</SCRIPT>");
out.println("</head>");
out.println("<body bgcolor=\"#FFFFFF\">");
out.println("<FORM name=mainform method=post>");
out.println("<div align=\"center\">");
out.println("<center>");
out.println("<div align=\"center\">");
out.println("<center>");
out.println("<TABLE cellSpacing=0 cellPadding=0 width=750 border=0 style=\"border-collapse: collapse\" bordercolor=\"#111111\">");
out.println("<TBODY>");
out.println("<TR> ");
out.println("<TD class=header><img src=\"images/frontpage.gif\" alt=\"\" width=\"386\" height=\"71\"><img src=\"images/Hdr_AS_Seal.jpg\" width=\"289\" height=\"71\"> ");
out.println("<img src=\"images/1animated12-thumb%5B1%5D.gif\" width=\"67\" height=\"50\"> ");
out.println("</TD>");
out.println("</TR>");
out.println("</TBODY>");
out.println("</TABLE>");
out.println("</center>");
out.println("</div>");
out.println("<p align=\"left\"><font face=\"arial\" size=\"2\"> ");
out.println("<marquee behavior=\"scroll\" style=\"font-family: Courier New; color: #333300; text-decoration: blink; font-size: 18pt; font-style: italic; font-weight: bold\">");
out.println("we share a visi<img src=\"images/Animsun.gif\" width=\"50\" height=\"26\">n ");
out.println("</marquee>");
out.println("</font></p>");
out.println("</center>");
out.println("</div>");
out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
out.println("<tr bordercolor=\"#CCCCCC\" bgcolor=\"#000099\"> ");
out.println("<td width=\"10%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"home.htm\"><font color=\"#FFFFFF\" size=\"5\">Home</font></a></div></td>");
out.println("<td width=\"14%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"services.htm\"><font color=\"#FFFFFF\" size=\"5\">Services</font></a></div></td>");
out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"packagefinal.htm\"><font color=\"#FFFFFF\" size=\"5\">Holiday ");
out.println("Packages </font></a></div></td>");
out.println("<td width=\"11%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"faq.htm\"><font color=\"#FFFFFF\" size=\"5\">FAQs</font></a></div></td>");
out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"register.htm\"><font color=\"#FFFFFF\" size=\"5\">Register ");
out.println("Yourself</font></a></div></td>");
out.println("<td width=\"15%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"aboutus.htm\"><font color=\"#FFFFFF\" size=\"5\">About ");
out.println("Us</font></a></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td colspan=\"6\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
out.println("<tr bgcolor=\"#0000CC\"> ");
out.println("<td width=\"21%\" height=\"20\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"acc.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
out.println("Accommodation</font></a></div></td>");
out.println("<td width=\"24%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travel.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
out.println("Traveling Means</font></a></div>");
out.println("<div align=\"center\"></div></td>");
out.println("<td width=\"25%\" bgcolor=\"#0000CC\"> ");
out.println("<div align=\"center\"><a href=\"travelguide.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
out.println("Guide</font></a></div></td>");
out.println("<td width=\"30%\" bgcolor=\"#3333FF\"> ");
out.println("<div align=\"center\"><a href=\"travelinsurance.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
out.println("Insurance</font></a></div></td>");
out.println("</tr>");
out.println("</table></td>");
out.println("</tr>");
out.println("</table>");
out.println("<p align=\"center\"><span class=\"style1\"><u><font color=\"#660033\" size=\"6\"><strong>Travel ");
out.println("Insurance </strong></font></u></span></p>");
out.println("<div align=\"center\"></div>");
out.println("<table width=\"100%\" border=\"0\" cellspacing=\"1\" cellpadding=\"0\">");
out.println("<tr>");
out.println("<td width=\"47%\" height=\"317\"> ");
out.println("<table width=\"18%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
out.println("<tr> ");
out.println("<td width=\"45%\" height=\"55\" bgcolor=\"#333333\">");
out.println("<div align=\"center\"><img src=\"images/supersurpriceban.jpg\" width=\"356\" height=\"55\"> ");
out.println("</div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td height=\"255\" valign=\"top\"> ");
out.println("<table width=\"46%\" border=\"0\" cellspacing=\"1\" cellpadding=\"0\">");
out.println("<tr> ");
out.println("<td width=\"46%\" height=\"260\"><img src=\"images/Southern%20GP59.jpg\" width=\"171\" height=\"256\"></td>");
out.println("<td width=\"54%\"><table width=\"100%\" height=\"251\" border=\"0\" cellpadding=\"0\" cellspacing=\"1\">");
out.println("<tr> ");
out.println("<td height=\"137\"><img src=\"images/cruises-celebrity.jpg\" width=\"201\" height=\"157\"></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td height=\"19\"> <div align=\"center\"><img src=\"images/vitara.jpg\" width=\"200\" height=\"100\"></div></td>");
out.println("</tr>");
out.println("</table></td>");
out.println("</tr>");
out.println("</table>");
out.println("</td>");
out.println("</tr>");
out.println("</table>");
out.println("</td>");
out.println("<td width=\"53%\" height=\"317\" valign=\"middle\" bgcolor=\"#FFCCFF\"> ");
out.println("<table width=\"100%\" height=\"233\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
out.println("<tr bgcolor=\"#FFCCFF\"> ");
out.println("<td colspan=\"2\"> <div align=\"center\"><em><strong><font color=\"#660000\" size=\"5\">Invalid ");
out.println("login id try again!!!</font></strong></em></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td width=\"41%\" bgcolor=\"#FFCCFF\"> <div align=\"center\"><strong>Login ");
out.println("ID</strong></div></td>");
out.println("<td width=\"59%\" bgcolor=\"#FFCCFF\"> <div align=\"center\"> ");
out.println("<input name=\"loginid\" type=\"text\" id=\"login\">");
out.println("</div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFCCFF\"> <div align=\"center\"><strong>Password</strong></div></td>");
out.println("<td bgcolor=\"#FFCCFF\"> <div align=\"center\"> ");
out.println("<input name=\"pswd\" type=\"password\" id=\"password\">");
out.println("</div></td>");
out.println("</tr>");
out.println("<tr bgcolor=\"#FFCCFF\"> ");
out.println("<td height=\"88\" colspan=\"2\"> <div align=\"center\" > <strong> ");
out.println("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"147\" height=\"34\">");
out.println("<param name=\"movie\" value=\"images/travellogin.swf\">");
out.println("<param name=\"quality\" value=\"high\">");
out.println("<param name=\"BGCOLOR\" value=\"#FFCCFF\">");
out.println("<embed src=\"images/travellogin.swf\" width=\"147\" height=\"34\" quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" bgcolor=\"#FFCCFF\" ></embed> ");
out.println("</object>");
out.println("</strong></div></td>");
out.println("</tr>");
out.println("</table>");
out.println("</td>");
out.println("</tr>");
out.println("</table>");
out.println("<HR align=center noShade>");
out.println("<p align=\"center\"><font size=\"4\" face=\"Arial\"><a href=\"home.htm\">Home</a> | <a href=\"services.htm\">Services</a></font></p>");
out.println("<HR align=center noShade>");
out.println("<p>&nbsp;</p>");
out.println("</body>");
out.println("</html>");

 
              }




             }
catch(Exception e){
                out.println("Exception"+e.getMessage()+e.toString());
            }
            finally{
                try{
                    if(c!=null)
                        c.close();
                }catch(Exception e){
                    out.println("Exception closing the connection"+e.getMessage());
                }
            }
        }
   }
   
