import java.io.*;

import javax.servlet.*;
import javax.servlet.http.*;

import com.jdbc.DB;

import java.sql.*;

public class pckglogin extends HttpServlet {

    public void init(ServletConfig config)
    	throws ServletException {
    		super.init(config);
    	}
      public String getContext(String param) {
		ServletContext sc=getServletContext();
		String prop=sc.getInitParameter(param);
		prop=prop!=null&&prop.length()>0?""+prop:"";
		System.out.println("Contex param:"+prop);
		return prop;
	}
    
    public void doGet(HttpServletRequest request, HttpServletResponse response)
    throws IOException, ServletException
    {
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();
        out.println("<html>");
        out.println("<body>");
        out.println("<head>");
        out.println("<title>Hello World!</title>");
        out.println("</head>");
        out.println("<body>");
        out.println("<h1>Hello World!</h1>");
        out.println("Your request was"+ request.getMethod()+"\n");
        out.println("</body>");
        out.println("</html>");
    }
    public void doPost(HttpServletRequest request, HttpServletResponse response)
    throws IOException, ServletException
    {
        Connection c=null;
        String loginid=request.getParameter("loginid");
        String pswd=request.getParameter("pswd");
  		response.setContentType("text/html");
        PrintWriter out = response.getWriter();
  		try{
   	     	Connection conn=DB.getConnect();
   	     	Statement st=conn.createStatement();
            String query = new String("select * from Customer where loginid='" +loginid+ "'" ); 
            ResultSet rs= st.executeQuery(query);
            if(rs.next())
            {
            	if(!pswd.equals(rs.getString("pswd")))
            	{
	 				out.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">");
					out.println("<html>");
					out.println("<head>");
					out.println("<title>Untitled Document</title>");
					out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
					out.println("<SCRIPT>");
					out.println("/*function doClear()");
					out.println("{		 ");
					out.println("document.mainform.BudgetAmtPDay.value = \"\";");
					out.println("document.mainform.BudgetAmtPTrip.value = \"\";");
					out.println("}*/");
					out.println("function doSubmit()");
					out.println("{");
					out.println("var strErrMsg;");
					out.println("strErrMsg = \"\";			");
					out.println("strErrMsg = doValidations();");
					out.println("if (strErrMsg == \"\" )");
					out.println("{				");
					out.println("document.mainform.action = \"pckglogin\";				");
					out.println("document.mainform.submit();");
					out.println("}");
					out.println("else");
					out.println("{alert(strErrMsg);}");
					out.println("}");
					out.println("function doValidations()");
					out.println("{");
					out.println("var ddIndex;");
					out.println("var strTemp;");
					out.println("var strFld;");
					out.println("var frmDoc;");
					out.println("var strErrMsg;");
					out.println("strErrMsg = \"\";");
					out.println("frmDoc = document.mainform;			");
					out.println("strFld = frmDoc.login");
					out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"Please enter loginId\\n\";			");
					out.println("strFld = frmDoc.password");
					out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"Please enter password\\n\";	");
					out.println("return strErrMsg;");
					out.println("}");
					out.println("</SCRIPT>");
					out.println("</head>");
					out.println("<body>");
					out.println("<FORM name=mainform method=post>");
					out.println("<div align=\"center\">");
					out.println("<center>");
					out.println("<div align=\"center\">");
					out.println("<center>");
					out.println("<TABLE cellSpacing=0 cellPadding=0 width=750 border=0 style=\"border-collapse: collapse\" bordercolor=\"#111111\">");
					out.println("<TBODY>");
					out.println("<TR> ");
					out.println("<TD class=header><img src=\"images/frontpage.gif\" alt=\"\" width=\"386\" height=\"71\"><img src=\"images/Hdr_AS_Seal.jpg\" width=\"289\" height=\"71\"> ");
					out.println("<img src=\"images/1animated12-thumb%5B1%5D.gif\" width=\"67\" height=\"50\"> ");
					out.println("</TD>");
					out.println("</TR>");
					out.println("</TBODY>");
					out.println("</TABLE>");
					out.println("</center>");
					out.println("</div>");
					out.println("<p align=\"left\"><font face=\"arial\" size=\"2\"> ");
					out.println("<marquee behavior=\"scroll\" style=\"font-family: Courier New; color: #333300; text-decoration: blink; font-size: 18pt; font-style: italic; font-weight: bold\">");
					out.println("we share a visi<img src=\"images/Animsun.gif\" width=\"50\" height=\"26\">n ");
					out.println("</marquee>");
					out.println("</font></p>");
					out.println("</center>");
					out.println("</div>");
					out.println("<table width=\"97%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr bordercolor=\"#CCCCCC\" bgcolor=\"#000099\"> ");
					out.println("<td width=\"10%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"home.htm\"><font color=\"#FFFFFF\" size=\"5\">Home</font></a></div></td>");
					out.println("<td width=\"14%\" bgcolor=\"#000099\"> ");
					out.println("<div align=\"center\"><a href=\"services.htm\"><font color=\"#FFFFFF\" size=\"5\">Services</font></a></div></td>");
					out.println("<td width=\"25%\" bgcolor=\"#0000CC\"> ");
					out.println("<div align=\"center\"><a href=\"packagefinal.htm\"><font color=\"#FFFFFF\" size=\"5\">Holiday ");
					out.println("Packages </font></a></div></td>");
					out.println("<td width=\"11%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"faq.htm\"><font color=\"#FFFFFF\" size=\"5\">FAQs</font></a></div></td>");
					out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"register.htm\"><font color=\"#FFFFFF\" size=\"5\">Register ");
					out.println("Yourself</font></a></div></td>");
					out.println("<td width=\"15%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"aboutus.htm\"><font color=\"#FFFFFF\" size=\"5\">About ");
					out.println("Us</font></a></div></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<h1 align=\"center\"><font color=\"#660033\">Holiday Packages</font></h1>");
					out.println("<table width=\"733\" height=\"438\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
					out.println("<tr> ");
					out.println("<td height=\"172\" colspan=\"2\"> ");
					out.println("<div align=\"left\"><img src=\"images/top-image.jpg\" width=\"594\" height=\"172\"><img src=\"images/1069floridakeys.jpg\" width=\"138\" height=\"172\"></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td width=\"145\" height=\"266\" valign=\"top\" bgcolor=\"#FFFFCC\"> ");
					out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"><div align=\"center\">Quick Links</div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><strong><a href=\"distancecalculator.htm\">Distance ");
					out.println("Calculator </a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><strong><a href=\"currencyconversion.htm\"> ");
					out.println("Currency Convertor</a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><a href=\"weather.htm\"><strong>Weather ");
					out.println("Details</strong></a></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><strong><a href=\"cityguide.htm\">City ");
					out.println("Guide</a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> ");
					out.println("<div align=\"center\"><strong><a href=\"www.Hotels in India, Indian Hotels, India Hotels Directory - By Destinationindia_com.htm\">Hotels In India ");
					out.println("</a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><a href=\"pc.htm\"><strong>Contact ");
					out.println("Us</strong></a></div></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<div align=\"center\"><img src=\"images/Banner.jpeg\" width=\"125\" height=\"125\"></div></td>");
					out.println("<td width=\"588\"><table width=\"100%\" height=\"160\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
					out.println("<tr bgcolor=\"#FFCCFF\"> ");
					out.println("<td height=\"42\" colspan=\"2\"> <div align=\"center\"><font color=\"#660033\" size=\"5\">Holiday ");
					out.println("Package Booking </font></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td width=\"70%\"> <div align=\"center\"> ");
					out.println("<table width=\"100%\" height=\"217\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
					out.println("<tr bgcolor=\"#FFCCFF\"> ");
					out.println("<td colspan=\"2\"> <div align=\"center\">");
					out.println("<p><em><strong><font color=\"#660000\" size=\"5\">Invalid Password!!!</font></strong></em></p>");
					out.println("<div align=\"right\"><em><strong><font color=\"#9900CC\" size=\"3\">New ");
					out.println("User ???</font><font color=\"#660000\" size=\"3\"> <a href=\"register.htm\">sign ");
					out.println("up here</a></font></strong></em></div>");
					out.println("</div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td width=\"51%\"><div align=\"center\"><strong>Login ID</strong></div></td>");
					out.println("<td width=\"49%\"><div align=\"center\"> ");
					out.println("<input name=\"loginid\" type=\"text\" id=\"login\">");
					out.println("</div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td><div align=\"center\"><strong>Password</strong></div></td>");
					out.println("<td><div align=\"center\"> ");
					out.println("<input name=\"pswd\" type=\"password\" id=\"password\">");
					out.println("</div></td>");
					out.println("</tr>");
					out.println("<tr bgcolor=\"#FFCCFF\"> ");
					out.println("<td height=\"72\" colspan=\"2\"> <div align=\"center\" > ");
					out.println("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"147\" height=\"34\">");
					out.println("<param name=\"movie\" value=\"images/button8.swf\">");
					out.println("<param name=\"quality\" value=\"high\">");
					out.println("<param name=\"bgcolor\" value=\"#FFCCFF\">");
					out.println("<embed src=\"images/button8.swf\" quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" width=\"147\" height=\"34\" bgcolor=\"#FFCCFF\"></embed> ");
					out.println("</object>");
					out.println("</div></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("</div></td>");
					out.println("<td width=\"30%\"><img src=\"images/left-image.jpg\" width=\"177\" height=\"214\"></td>");
					out.println("</tr>");
					out.println("</table></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<TABLE border=0 cellPadding=0 cellSpacing=0 width=\"96%\">");
					out.println("<TBODY>");
					out.println("<TR> ");
					out.println("<TD> <HR SIZE=1 width=\"70%\"> <DIV align=center><A ");
					out.println("href=\"goaholidays.htm\"><FONT ");
					out.println("face=\"Arial, Helvetica, sans-serif\" size=2>Holiday in Goa</FONT></A><FONT face=\"Arial, Helvetica, sans-serif\" size=2> ");
					out.println("| <A ");
					out.println("href=\"tajmahal.htm\">Visit the Taj ");
					out.println("Mahal</A> | <A ");
					out.println("href=\"pc.htm\">Golden Triangle</A> ");
					out.println("| <A ");
					out.println("href=\"pc.htm\">Resplendent Rajasthan</A><BR>");
					out.println("<A ");
					out.println("href=\"pc.htm\">Scent Of Sandlewood</A> ");
					out.println("| <A ");
					out.println("href=\"pc.htm\">Kerala Palms &amp; ");
					out.println("Backwaters</A> | <A ");
					out.println("href=\"pc.htm\">Palms &amp; Backwaters ");
					out.println("Special</A><BR>");
					out.println("<A ");
					out.println("href=\"pc.htm\">Kerala Holidays</A> ");
					out.println("| <A ");
					out.println("href=\"pc.htm\">Himalayan Magic</A> ");
					out.println("| <A ");
					out.println("href=\"pc.htm\">Ruins Of An Empire</A> ");
					out.println("| <A ");
					out.println("href=\"pc.htm\">Holiday in Bombay / ");
					out.println("Mumbai</A> | <A ");
					out.println("href=\"pc.htm\">Holiday Nepal</A><BR>");
					out.println("<A ");
					out.println("href=\"pc.htm\">South India Panorama</A> ");
					out.println("| <A ");
					out.println("href=\"pc.htm\">Glorious Rajasthan</A> ");
					out.println("| <A href=\"pc.htm\">The Temple Tryst</A> ");
					out.println("| <A ");
					out.println("href=\"pc.htm\">On The Trails of Buddha</A> ");
					out.println("</FONT><FONT face=\"Arial, Helvetica, sans-serif\"><BR>");
					out.println("<A ");
					out.println("href=\"home.htm\"><FONT ");
					out.println("size=3>HOME</FONT></A></FONT></DIV></TD>");
					out.println("</TR>");
					out.println("<TR> ");
					out.println("<TD width=\"100%\" height=\"38\"> <DIV> ");
					out.println("<HR SIZE=1 width=\"70%\">");
					out.println("<DIV align=center><A href=\"pc.htm\"><FONT ");
					out.println("face=\"Arial, Helvetica, sans-serif\" size=1>Contact us</FONT></A> | ");
					out.println("<A class=s href=\"pc.htm\"><FONT ");
					out.println("face=\"Arial, Helvetica, sans-serif\" size=1>Privacy Policy</FONT></A> ");
					out.println("| <A class=s href=\"pc.htm\"><FONT ");
					out.println("face=\"Arial, Helvetica, sans-serif\" size=1>Terms of Use</FONT></A> ");
					out.println("</DIV>");
					out.println("</DIV></TD>");
					out.println("</TR>");
					out.println("</TBODY>");
					out.println("</TABLE>");
					out.println("<hr size=1 width=\"70%\">");
					out.println("<p align=\"center\"><img src=\"images/twisting_cranberry_wht.jpg\" width=\"300\" height=\"30\"></p>");
					out.println("</body>");
					out.println("</html>");
	

            	}
            	else
            	{
            		out.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">");
					out.println("<html>");
					out.println("<head>");
					out.println("<title>Untitled Document</title>");
					out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
					out.println("<SCRIPT>");
					out.println("function doSubmit()");
					out.println("{");
					out.println("var strErrMsg;");
					out.println("strErrMsg = \"\";			");
					out.println("strErrMsg = doValidations();");
					out.println("if (strErrMsg == \"\" )");
					out.println("{				");
					out.println("document.mainform.action = \"pckgbooking\";				");
					out.println("document.mainform.submit();");
					out.println("}");
					out.println("else");
					out.println("{alert(strErrMsg);}");
					out.println("}");
					out.println("function doValidations()");
					out.println("{");
					out.println("var ddIndex;");
					out.println("var strTemp;");
					out.println("var strFld;");
					out.println("var frmDoc;");
					out.println("var strErrMsg;");
					out.println("strErrMsg = \"\";");
					out.println("frmDoc = document.mainform;			");
					out.println("strFld = frmDoc.pckgid");
					out.println("if (strFld.value == \"\" || strFld.value.length<4) 		");
					out.println("strErrMsg = strErrMsg + \" Package ID is Invalid\\n\";");
					out.println("if(frmDoc.syy.value<=frmDoc.dyy.value)");
					out.println("{");
					out.println("if(frmDoc.smm.value<=frmDoc.dmm.value)");
					out.println("{");
					out.println("if(frmDoc.sdd.value>frmDoc.ddd.value)");
					out.println("strErrMsg = strErrMsg + \" Date is Incorrect\\n\";");
					out.println("}");
					out.println("else");
					out.println("strErrMsg = strErrMsg + \" Date is Incorrect\\n\";");
					out.println("}");
					out.println("else");
					out.println("strErrMsg = strErrMsg + \" Date is Incorrect\\n\";");
					out.println("return strErrMsg;");
					out.println("}");
					out.println("</SCRIPT>");
					out.println("</head>");
					out.println("<body>");
					out.println("<FORM name=mainform method=post>");
				out.println("<div align=\"center\">");
					out.println("<center>");
					out.println("<div align=\"center\">");
					out.println("<center>");
					out.println("<TABLE cellSpacing=0 cellPadding=0 width=750 border=0 style=\"border-collapse: collapse\" bordercolor=\"#111111\">");
					out.println("<TBODY>");
					out.println("<TR> ");
					out.println("<TD class=header><img src=\"images/frontpage.gif\" alt=\"\" width=\"386\" height=\"71\"><img src=\"images/Hdr_AS_Seal.jpg\" width=\"289\" height=\"71\"> ");
					out.println("<img src=\"images/1animated12-thumb%5B1%5D.gif\" width=\"67\" height=\"50\"> ");
					out.println("</TD>");
					out.println("</TR>");
					out.println("</TBODY>");
					out.println("</TABLE>");
					out.println("</center>");
					out.println("</div>");
					out.println("<p align=\"left\"><font face=\"arial\" size=\"2\"> ");
					out.println("<marquee behavior=\"scroll\" style=\"font-family: Courier New; color: #333300; text-decoration: blink; font-size: 18pt; font-style: italic; font-weight: bold\">");
					out.println("we share a visi<img src=\"images/Animsun.gif\" width=\"50\" height=\"26\">n ");
					out.println("</marquee>");
					out.println("</font></p>");
					out.println("</center>");
					out.println("</div>");
					out.println("<table width=\"97%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr bordercolor=\"#CCCCCC\" bgcolor=\"#000099\"> ");
					out.println("<td width=\"10%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"home.htm\"><font color=\"#FFFFFF\" size=\"5\">Home</font></a></div></td>");
					out.println("<td width=\"14%\" bgcolor=\"#000099\"> ");
					out.println("<div align=\"center\"><a href=\"services.htm\"><font color=\"#FFFFFF\" size=\"5\">Services</font></a></div></td>");
					out.println("<td width=\"25%\" bgcolor=\"#0000CC\"> ");
					out.println("<div align=\"center\"><a href=\"packagefinal.htm\"><font color=\"#FFFFFF\" size=\"5\">Holiday ");
					out.println("Packages </font></a></div></td>");
					out.println("<td width=\"11%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"faq.htm\"><font color=\"#FFFFFF\" size=\"5\">FAQs</font></a></div></td>");
					out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"register.htm\"><font color=\"#FFFFFF\" size=\"5\">Register ");
					out.println("Yourself</font></a></div></td>");
					out.println("<td width=\"15%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"aboutus.htm\"><font color=\"#FFFFFF\" size=\"5\">About ");
					out.println("Us</font></a></div></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<h1 align=\"center\"><font color=\"#660033\">Holiday Packages</font></h1>");
					out.println("<table width=\"733\" height=\"438\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
					out.println("<tr> ");
					out.println("<td height=\"172\" colspan=\"2\"> ");
					out.println("<div align=\"left\"><img src=\"images/top-image.jpg\" width=\"594\" height=\"172\"><img src=\"images/1069floridakeys.jpg\" width=\"138\" height=\"172\"></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td width=\"145\" height=\"266\" valign=\"top\" bgcolor=\"#FFFFCC\"> ");
					out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"><div align=\"center\">Quick Links</div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><strong><a href=\"distancecalculator.htm\">Distance ");
					out.println("Calculator </a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><strong><a href=\"currencyconversion.htm\"> ");
					out.println("Currency Convertor</a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><a href=\"weather.htm\"><strong>Weather ");
					out.println("Details</strong></a></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><strong><a href=\"cityguide.htm\">City ");
					out.println("Guide</a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> ");
					out.println("<div align=\"center\"><strong><a href=\"www.Hotels in India, Indian Hotels, India Hotels Directory - By Destinationindia_com.htm\">Hotels In India ");
					out.println("</a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><a href=\"pc.htm\"><strong>Contact ");
					out.println("Us</strong></a></div></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<div align=\"center\"><img src=\"images/Banner.jpeg\" width=\"125\" height=\"125\"></div></td>");
					out.println("<td width=\"588\"><table width=\"100%\" height=\"160\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
					out.println("<tr bgcolor=\"#FFCCFF\"> ");
					out.println("<td height=\"42\" colspan=\"2\"> <div align=\"center\"><font color=\"#660033\" size=\"5\">Holiday ");
					out.println("Package Booking </font></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td width=\"70%\"> <div align=\"center\"> ");
					out.println("<table width=\"100%\" height=\"219\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
					out.println("<tr bgcolor=\"#FFCCFF\"> ");
					out.println("<td bgcolor=\"#FFFFFF\"> ");
					out.println("<div align=\"center\"> ");
					out.println("<p><strong>Login Id</strong></p>");
					out.println("</div></td>");
					out.println("<td bgcolor=\"#FFFFFF\">");
					out.println("<input name=\"loginid\" type=\"text\" id=\"loginid\" value=\"" +loginid+ "\" size=\"20\" maxlength=\"25\"   > <strong></strong></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td width=\"51%\"><div align=\"center\"><strong>Package ID</strong></div></td>");
					out.println("<td width=\"49%\"><div align=\"left\">");
					out.println("<input name=\"pckgid\" type=\"text\" id=\"loginid\" size=\"20\" maxlength=\"4\">");
					out.println("</div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td><div align=\"center\"><strong>Departure Date</strong></div></td>");
					out.println("<td><select name=\"sdd\" id=\"sdd\">");
					out.println("<option value=\"1\">01</option>");
					out.println("<option value=\"2\">02</option>");
					out.println("<option value=\"3\">03</option>");
					out.println("<option value=\"4\">04</option>");
					out.println("<option value=\"5\">05</option>");
					out.println("<option value=\"6\">06</option>");
					out.println("<option value=\"7\">07</option>");
					out.println("<option value=\"8\">08</option>");
					out.println("<option value=\"9\">09</option>");
					out.println("<option value=\"10\">10</option>");
					out.println("<option value=\"11\">11</option>");
					out.println("<option value=\"12\">12</option>");
					out.println("<option value=\"13\">13</option>");
					out.println("<option value=\"14\">14</option>");
					out.println("<option value=\"15\">15</option>");
					out.println("<option value=\"16\">16</option>");
					out.println("<option value=\"17\">17</option>");
					out.println("<option value=\"18\">18</option>");
					out.println("<option value=\"19\">19</option>");
					out.println("<option value=\"20\">20</option>");
					out.println("<option value=\"21\" selected>21</option>");
					out.println("<option value=\"22\">22</option>");
					out.println("<option value=\"23\">23</option>");
					out.println("<option value=\"24\">24</option>");
					out.println("<option value=\"25\">25</option>");
					out.println("<option value=\"26\">26</option>");
					out.println("<option value=\"27\">27</option>");
					out.println("<option value=\"28\">28</option>");
					out.println("<option value=\"29\">29</option>");
					out.println("<option value=\"30\">30</option>");
					out.println("<option value=\"31\">31</option>");
					out.println("</select>");
					out.println("<select name=\"smm\" id=\"smm\">");
					out.println("<option value=\"1\">JAN</option>");
					out.println("<option value=\"2\">FEB</option>");
					out.println("<option value=\"3\">MAR</option>");
					out.println("<option value=\"4\">APR</option>");
					out.println("<option value=\"5\">MAY</option>");
					out.println("<option value=\"6\">JUN</option>");
					out.println("<option value=\"7\">JUL</option>");
					out.println("<option value=\"8\">AUG</option>");
					out.println("<option value=\"9\">SEP</option>");
					out.println("<option value=\"10\">OCT</option>");
					out.println("<option value=\"11\" selected>NOV</option>");
					out.println("<option value=\"12\">DEC</option>");
					out.println("</select>");
					out.println("<select name=\"syy\" id=\"syy\">");
					out.println("<option value=\"04\" selected>2004</option>");
					out.println("<option value=\"05\">2005</option>");
					out.println("</select> </td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td><div align=\"center\"><strong>Departure From</strong></div></td>");
					out.println("<td><select name=\"source\" id=\"source\">");
					out.println("<option value=\"ND\" selected>New Delhi</option>");
					out.println("<option value=\"KL\">Kolkata</option>");
					out.println("<option value=\"CH\">Chennai</option>");
					out.println("<option value=\"MB\">Mumbai</option>");
					out.println("<option value=\"BG\">Banglore</option>");
					out.println("<option value=\"ID\">Indore</option>");
					out.println("<option value=\"LK\">Lucknow</option>");
					out.println("<option value=\"RC\">Ranchi</option>");
					out.println("</select></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td><div align=\"center\"><strong>Return Date</strong></div></td>");
					out.println("<td><select name=\"ddd\" id=\"ddd\">");
					out.println("<option value=\"1\">01</option>");
					out.println("<option value=\"2\">02</option>");
					out.println("<option value=\"3\">03</option>");
					out.println("<option value=\"4\">04</option>");
					out.println("<option value=\"5\">05</option>");
					out.println("<option value=\"6\">06</option>");
					out.println("<option value=\"7\">07</option>");
					out.println("<option value=\"8\">08</option>");
					out.println("<option value=\"9\">09</option>");
					out.println("<option value=\"10\">10</option>");
					out.println("<option value=\"11\">11</option>");
					out.println("<option value=\"12\">12</option>");
					out.println("<option value=\"13\">13</option>");
					out.println("<option value=\"14\">14</option>");
					out.println("<option value=\"15\">15</option>");
					out.println("<option value=\"16\">16</option>");
					out.println("<option value=\"17\">17</option>");
					out.println("<option value=\"18\">18</option>");
					out.println("<option value=\"19\">19</option>");
					out.println("<option value=\"20\">20</option>");
					out.println("<option value=\"21\" selected>21</option>");
					out.println("<option value=\"22\">22</option>");
					out.println("<option value=\"23\">23</option>");
					out.println("<option value=\"24\">24</option>");
					out.println("<option value=\"25\">25</option>");
					out.println("<option value=\"26\">26</option>");
					out.println("<option value=\"27\">27</option>");
					out.println("<option value=\"28\">28</option>");
					out.println("<option value=\"29\">29</option>");
					out.println("<option value=\"30\">30</option>");
					out.println("<option value=\"31\">31</option>");
					out.println("</select>");
					out.println("<select name=\"dmm\" id=\"dmm\">");
					out.println("<option value=\"1\">JAN</option>");
					out.println("<option value=\"2\">FEB</option>");
					out.println("<option value=\"3\">MAR</option>");
					out.println("<option value=\"4\">APR</option>");
					out.println("<option value=\"5\">MAY</option>");
					out.println("<option value=\"6\">JUN</option>");
					out.println("<option value=\"7\">JUL</option>");
					out.println("<option value=\"8\">AUG</option>");
					out.println("<option value=\"9\">SEP</option>");
					out.println("<option value=\"10\">OCT</option>");
					out.println("<option value=\"11\" selected>NOV</option>");
					out.println("<option value=\"12\">DEC</option>");
					out.println("</select>");
					out.println("<select name=\"dyy\" id=\"dyy\">");
					out.println("<option value=\"04\" selected>2004</option>");
					out.println("<option value=\"05\">2005</option>");
					out.println("</select></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td height=\"25\" colspan=\"2\"> <div align=\"left\"><strong> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Hotel ");
					out.println("Booking </strong> ");
					out.println("<input type=\"checkbox\" name=\"checkbox\" value=\"checkbox\">");
					out.println("<strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Car Booking ");
					out.println("<input type=\"checkbox\" name=\"checkbox2\" value=\"checkbox\">");
					out.println("</strong></div>");
					out.println("<div align=\"center\"></div></td>");
					out.println("</tr>");
					out.println("<tr bgcolor=\"#FFCCFF\"> ");
					out.println("<td height=\"72\" colspan=\"2\"><div align=\"center\"> <strong> ");
					out.println("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"105\" height=\"33\" align=\"middle\">");
					out.println("<param name=\"BGCOLOR\" value=\"#FFCCFF\">");
					out.println("<param name=\"movie\" value=\"images/button10.swf\">");
					out.println("<param name=\"quality\" value=\"high\">");
					out.println("<embed src=\"images/button10.swf\" width=\"105\" height=\"33\" align=\"middle\" quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" bgcolor=\"#FFCCFF\" ></embed></object>");
					out.println("</strong></div></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("</div></td>");
					out.println("<td width=\"30%\"><img src=\"images/left-image.jpg\" width=\"177\" height=\"214\"></td>");
					out.println("</tr>");
					out.println("</table></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<TABLE border=0 cellPadding=0 cellSpacing=0 width=\"96%\">");
					out.println("<TBODY>");
					out.println("<TR> ");
					out.println("<TD> <HR SIZE=1 width=\"70%\"> <DIV align=center><A ");
					out.println("href=\"goaholidays.htm\"><FONT ");
					out.println("face=\"Arial, Helvetica, sans-serif\" size=2>Holiday in Goa</FONT></A><FONT face=\"Arial, Helvetica, sans-serif\" size=2> ");
					out.println("| <A ");
					out.println("href=\"tajmahal.htm\">Visit the Taj ");
					out.println("Mahal</A> | <A ");
					out.println("href=\"pc.htm\">Golden Triangle</A> ");
					out.println("| <A ");
					out.println("href=\"pc.htm\">Resplendent Rajasthan</A><BR>");
					out.println("<A ");
					out.println("href=\"pc.htm\">Scent Of Sandlewood</A> ");
					out.println("| <A ");
					out.println("href=\"pc.htm\">Kerala Palms &amp; ");
					out.println("Backwaters</A> | <A ");
					out.println("href=\"pc.htm\">Palms &amp; Backwaters ");
					out.println("Special</A><BR>");
					out.println("<A ");
					out.println("href=\"pc.htm\">Kerala Holidays</A> ");
					out.println("| <A ");
					out.println("href=\"pc.htm\">Himalayan Magic</A> ");
					out.println("| <A ");
					out.println("href=\"pc.htm\">Ruins Of An Empire</A> ");
					out.println("| <A ");
					out.println("href=\"pc.htm\">Holiday in Bombay / ");
					out.println("Mumbai</A> | <A ");
					out.println("href=\"pc.htm\">Holiday Nepal</A><BR>");
					out.println("<A ");
					out.println("href=\"pc.htm\">South India Panorama</A> ");
					out.println("| <A ");
					out.println("href=\"pc.htm\">Glorious Rajasthan</A> ");
					out.println("| <A href=\"pc.htm\">The Temple Tryst</A> ");
					out.println("| <A ");
					out.println("href=\"pc.htm\">On The Trails of Buddha</A> ");
					out.println("</FONT><FONT face=\"Arial, Helvetica, sans-serif\"><BR>");
					out.println("<A ");
					out.println("href=\"home.htm\"><FONT ");
					out.println("size=3>HOME</FONT></A></FONT></DIV></TD>");
					out.println("</TR>");
					out.println("<TR> ");
					out.println("<TD width=\"100%\" height=\"38\"> <DIV> ");
					out.println("<HR SIZE=1 width=\"70%\">");
					out.println("<DIV align=center><A href=\"pc.htm\"><FONT ");
					out.println("face=\"Arial, Helvetica, sans-serif\" size=1>Contact us</FONT></A> | ");
					out.println("<A class=s href=\"pc.htm\"><FONT ");
					out.println("face=\"Arial, Helvetica, sans-serif\" size=1>Privacy Policy</FONT></A> ");
					out.println("| <A class=s href=\"pc.htm\"><FONT ");
					out.println("face=\"Arial, Helvetica, sans-serif\" size=1>Terms of Use</FONT></A> ");
					out.println("</DIV>");
					out.println("</DIV></TD>");
					out.println("</TR>");
					out.println("</TBODY>");
					out.println("</TABLE>");
					out.println("<hr size=1 width=\"70%\">");
					out.println("<p align=\"center\"><img src=\"images/twisting_cranberry_wht.jpg\" width=\"300\" height=\"30\"></p>");
					out.println("</form></body>");
					out.println("</html>");

            	

	
            	}
            }
            else
            {
            	out.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">");
				out.println("<html>");
				out.println("<head>");
				out.println("<title>Untitled Document</title>");
				out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
				out.println("<SCRIPT>");
				out.println("/*function doClear()");
				out.println("{		 ");
				out.println("document.mainform.BudgetAmtPDay.value = \"\";");
				out.println("document.mainform.BudgetAmtPTrip.value = \"\";");
				out.println("}*/");
				out.println("function doSubmit()");
				out.println("{");
				out.println("var strErrMsg;");
				out.println("strErrMsg = \"\";			");
				out.println("strErrMsg = doValidations();");
				out.println("if (strErrMsg == \"\" )");
				out.println("{				");
				out.println("document.mainform.action = \"pckglogin\";				");
				out.println("document.mainform.submit();");
				out.println("}");
				out.println("else");
				out.println("{alert(strErrMsg);}");
				out.println("}");
				out.println("function doValidations()");
				out.println("{");
				out.println("var ddIndex;");
				out.println("var strTemp;");
				out.println("var strFld;");
				out.println("var frmDoc;");
				out.println("var strErrMsg;");
				out.println("strErrMsg = \"\";");
				out.println("frmDoc = document.mainform;			");
				out.println("strFld = frmDoc.login");
				out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"Please enter loginId\\n\";			");
				out.println("strFld = frmDoc.password");
				out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"Please enter password\\n\";	");
				out.println("return strErrMsg;");
				out.println("}");
				out.println("</SCRIPT>");
				out.println("</head>");
				out.println("<body>");
				out.println("<FORM name=mainform method=post>");
				out.println("<div align=\"center\">");
					out.println("<center>");
					out.println("<div align=\"center\">");
					out.println("<center>");
					out.println("<TABLE cellSpacing=0 cellPadding=0 width=750 border=0 style=\"border-collapse: collapse\" bordercolor=\"#111111\">");
					out.println("<TBODY>");
					out.println("<TR> ");
					out.println("<TD class=header><img src=\"images/frontpage.gif\" alt=\"\" width=\"386\" height=\"71\"><img src=\"images/Hdr_AS_Seal.jpg\" width=\"289\" height=\"71\"> ");
					out.println("<img src=\"images/1animated12-thumb%5B1%5D.gif\" width=\"67\" height=\"50\"> ");
					out.println("</TD>");
					out.println("</TR>");
					out.println("</TBODY>");
					out.println("</TABLE>");
					out.println("</center>");
					out.println("</div>");
					out.println("<p align=\"left\"><font face=\"arial\" size=\"2\"> ");
					out.println("<marquee behavior=\"scroll\" style=\"font-family: Courier New; color: #333300; text-decoration: blink; font-size: 18pt; font-style: italic; font-weight: bold\">");
					out.println("we share a visi<img src=\"images/Animsun.gif\" width=\"50\" height=\"26\">n ");
					out.println("</marquee>");
					out.println("</font></p>");
					out.println("</center>");
					out.println("</div>");
					out.println("<table width=\"97%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
					out.println("<tr bordercolor=\"#CCCCCC\" bgcolor=\"#000099\"> ");
					out.println("<td width=\"10%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"home.htm\"><font color=\"#FFFFFF\" size=\"5\">Home</font></a></div></td>");
					out.println("<td width=\"14%\" bgcolor=\"#000099\"> ");
					out.println("<div align=\"center\"><a href=\"services.htm\"><font color=\"#FFFFFF\" size=\"5\">Services</font></a></div></td>");
					out.println("<td width=\"25%\" bgcolor=\"#0000CC\"> ");
					out.println("<div align=\"center\"><a href=\"packagefinal.htm\"><font color=\"#FFFFFF\" size=\"5\">Holiday ");
					out.println("Packages </font></a></div></td>");
					out.println("<td width=\"11%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"faq.htm\"><font color=\"#FFFFFF\" size=\"5\">FAQs</font></a></div></td>");
					out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"register.htm\"><font color=\"#FFFFFF\" size=\"5\">Register ");
					out.println("Yourself</font></a></div></td>");
					out.println("<td width=\"15%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"aboutus.htm\"><font color=\"#FFFFFF\" size=\"5\">About ");
					out.println("Us</font></a></div></td>");
					out.println("</tr>");
					out.println("</table>");
					out.println("<h1 align=\"center\"><font color=\"#660033\">Holiday Packages</font></h1>");
					out.println("<table width=\"733\" height=\"438\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
					out.println("<tr> ");
					out.println("<td height=\"172\" colspan=\"2\"> ");
					out.println("<div align=\"left\"><img src=\"images/top-image.jpg\" width=\"594\" height=\"172\"><img src=\"images/1069floridakeys.jpg\" width=\"138\" height=\"172\"></div></td>");
					out.println("</tr>");
				out.println("<tr> ");
				out.println("<td width=\"145\" height=\"266\" valign=\"top\" bgcolor=\"#FFFFCC\"> ");
				out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
				out.println("<tr> ");
				out.println("<td bgcolor=\"#FFFFCC\"><div align=\"center\">Quick Links</div></td>");
				out.println("</tr>");
				out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><strong><a href=\"distancecalculator.htm\">Distance ");
					out.println("Calculator </a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><strong><a href=\"currencyconversion.htm\"> ");
					out.println("Currency Convertor</a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><a href=\"weather.htm\"><strong>Weather ");
					out.println("Details</strong></a></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><strong><a href=\"cityguide.htm\">City ");
					out.println("Guide</a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> ");
					out.println("<div align=\"center\"><strong><a href=\"www.Hotels in India, Indian Hotels, India Hotels Directory - By Destinationindia_com.htm\">Hotels In India ");
					out.println("</a></strong></div></td>");
					out.println("</tr>");
					out.println("<tr> ");
					out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><a href=\"pc.htm\"><strong>Contact ");
					out.println("Us</strong></a></div></td>");
					out.println("</tr>");
					out.println("</table>");
				out.println("<div align=\"center\"><img src=\"images/Banner.jpeg\" width=\"125\" height=\"125\"></div></td>");
				out.println("<td width=\"588\"><table width=\"100%\" height=\"160\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
				out.println("<tr bgcolor=\"#FFCCFF\"> ");
				out.println("<td height=\"42\" colspan=\"2\"> <div align=\"center\"><font color=\"#660033\" size=\"5\">Holiday ");
				out.println("Package Booking </font></div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td width=\"70%\"> <div align=\"center\"> ");
				out.println("<table width=\"100%\" height=\"217\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
				out.println("<tr bgcolor=\"#FFCCFF\"> ");
				out.println("<td colspan=\"2\"> <div align=\"center\">");
				out.println("<p><em><strong><font color=\"#660000\" size=\"5\">Invalid loginid ");
				out.println("!!!</font></strong></em></p>");
				out.println("<div align=\"right\"><em><strong><font color=\"#9900CC\" size=\"3\">New ");
				out.println("User ???</font><font color=\"#660000\" size=\"3\"> <a href=\"register.htm\">sign ");
				out.println("up here</a></font></strong></em></div>");
				out.println("</div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td width=\"51%\"><div align=\"center\"><strong>Login ID</strong></div></td>");
				out.println("<td width=\"49%\"><div align=\"center\"> ");
				out.println("<input name=\"loginid\" type=\"text\" id=\"login\">");
				out.println("</div></td>");
				out.println("</tr>");
				out.println("<tr> ");
				out.println("<td><div align=\"center\"><strong>Password</strong></div></td>");
				out.println("<td><div align=\"center\"> ");
				out.println("<input name=\"pswd\" type=\"password\" id=\"password\">");
				out.println("</div></td>");
				out.println("</tr>");
				out.println("<tr bgcolor=\"#FFCCFF\"> ");
				out.println("<td height=\"72\" colspan=\"2\"> <div align=\"center\" > ");
				out.println("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"147\" height=\"34\">");
				out.println("<param name=\"movie\" value=\"images/button8.swf\">");
				out.println("<param name=\"quality\" value=\"high\">");
				out.println("<param name=\"bgcolor\" value=\"#FFCCFF\">");
				out.println("<embed src=\"images/button8.swf\" quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" width=\"147\" height=\"34\" bgcolor=\"#FFCCFF\"></embed> ");
				out.println("</object>");
				out.println("</div></td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("</div></td>");
				out.println("<td width=\"30%\"><img src=\"images/left-image.jpg\" width=\"177\" height=\"214\"></td>");
				out.println("</tr>");
				out.println("</table></td>");
				out.println("</tr>");
				out.println("</table>");
				out.println("<TABLE border=0 cellPadding=0 cellSpacing=0 width=\"96%\">");
				out.println("<TBODY>");
				out.println("<TR> ");
				out.println("<TD> <HR SIZE=1 width=\"70%\"> ");
				out.println("<DIV align=center><A ");
				out.println("href=\"goaholidays.htm\"><FONT ");
				out.println("face=\"Arial, Helvetica, sans-serif\" size=2>Holiday in Goa</FONT></A><FONT face=\"Arial, Helvetica, sans-serif\" size=2> ");
				out.println("| <A ");
				out.println("href=\"tajmahal.htm\">Visit the Taj ");
				out.println("Mahal</A> | <A ");
				out.println("href=\"pc.htm\">Golden Triangle</A> ");
				out.println("| <A ");
				out.println("href=\"pc.htm\">Resplendent Rajasthan</A><BR>");
				out.println("<A ");
				out.println("href=\"pc.htm\">Scent Of Sandlewood</A> ");
				out.println("| <A ");
				out.println("href=\"pc.htm\">Kerala Palms &amp; ");
				out.println("Backwaters</A> | <A ");
				out.println("href=\"pc.htm\">Palms &amp; Backwaters ");
				out.println("Special</A><BR>");
				out.println("<A ");
				out.println("href=\"pc.htm\">Kerala Holidays</A> ");
				out.println("| <A ");
				out.println("href=\"pc.htm\">Himalayan Magic</A> ");
				out.println("| <A ");
				out.println("href=\"pc.htm\">Ruins Of An Empire</A> ");
				out.println("| <A ");
				out.println("href=\"pc.htm\">Holiday in Bombay / ");
				out.println("Mumbai</A> | <A ");
				out.println("href=\"pc.htm\">Holiday Nepal</A><BR>");
				out.println("<A ");
				out.println("href=\"pc.htm\">South India Panorama</A> ");
				out.println("| <A ");
				out.println("href=\"pc.htm\">Glorious Rajasthan</A> ");
				out.println("| <A href=\"pc.htm\">The Temple Tryst</A> ");
				out.println("| <A ");
				out.println("href=\"pc.htm\">On The Trails of Buddha</A> ");
				out.println("</FONT><FONT face=\"Arial, Helvetica, sans-serif\"><BR>");
				out.println("<A ");
				out.println("href=\"home.htm\"><FONT ");
				out.println("size=3>HOME</FONT></A></FONT></DIV></TD>");
				out.println("</TR>");
				out.println("<TR> ");
				out.println("<TD width=\"100%\" height=\"38\"> <DIV> ");
				out.println("<HR SIZE=1 width=\"70%\">");
				out.println("<DIV align=center><A href=\"pc.htm\"><FONT ");
				out.println("face=\"Arial, Helvetica, sans-serif\" size=1>Contact us</FONT></A> | ");
				out.println("<A class=s href=\"pc.htm\"><FONT ");
				out.println("face=\"Arial, Helvetica, sans-serif\" size=1>Privacy Policy</FONT></A> ");
				out.println("| <A class=s href=\"pc.htm\"><FONT ");
				out.println("face=\"Arial, Helvetica, sans-serif\" size=1>Terms of Use</FONT></A> ");
				out.println("</DIV>");
				out.println("</DIV></TD>");
				out.println("</TR>");
				out.println("</TBODY>");
				out.println("</TABLE>");
				out.println("<hr size=1 width=\"70%\">");
				out.println("<p align=\"center\"><img src=\"images/twisting_cranberry_wht.jpg\" width=\"300\" height=\"30\"></p>");
				out.println("</body>");
				out.println("</html>");


            }
            }catch(Exception e){
            	out.println("Exception"+e.getMessage()+e.toString());
            }
            finally{
            	try{
            		if(c!=null)
            			c.close();
            	}catch(Exception e){
            		out.println("Exception closing the connection"+e.getMessage());
            	}
            }
   		}
   }
   
