import java.io.*; 
import javax.servlet.*;
import javax.servlet.http.*;

import com.jdbc.DB;

import java.sql.*;

public class trainbook extends HttpServlet {

    public void init(ServletConfig config)
        throws ServletException {
            super.init(config);
        }
      public String getContext(String param) {
		ServletContext sc=getServletContext();
		String prop=sc.getInitParameter(param);
		prop=prop!=null&&prop.length()>0?""+prop:"";
		System.out.println("Contex param:"+prop);
		return prop;
	}
    public void doGet(HttpServletRequest request, HttpServletResponse response)
    throws IOException, ServletException
    {
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();
        out.println("<html>");
        out.println("<body>");
        out.println("<head>");
        out.println("<title>Hello World!</title>");
        out.println("</head>");
        out.println("<body>");
        out.println("<h1>Hello World!</h1>");
        out.println("Your request was"+ request.getMethod()+"\n");
        out.println("</body>");
        out.println("</html>");
    }
    public void doPost(HttpServletRequest request, HttpServletResponse response)
    throws IOException, ServletException
    {
        Connection c=null;
        String loginid=request.getParameter("loginid");
        String pswd=request.getParameter("pswd");
        response.setContentType("text/html");
        PrintWriter out = response.getWriter();
        try{
   	     	Connection conn=DB.getConnect();
   	     	Statement st=conn.createStatement();
            String query = new String("select * from Customer where loginid='" +loginid+ "'" ); 
            ResultSet rs= st.executeQuery(query);
            if(rs.next())
            {
              if(!pswd.equals(rs.getString("pswd")))
                {
out.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">");
out.println("<html>");
out.println("<head>");
out.println("<title>invalidpassword</title>");
out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
out.println("<SCRIPT>");
out.println("/*function doClear()");
out.println("{       ");
out.println("document.mainform.BudgetAmtPDay.value = \"\";");
out.println("document.mainform.BudgetAmtPTrip.value = \"\";");
out.println("}*/");
out.println("function doSubmit()");
out.println("{         ");
out.println("var strErrMsg;");
out.println("strErrMsg = \"\";          ");
out.println("strErrMsg = doValidations();");
out.println("if (strErrMsg == \"\" )");
out.println("{              ");
out.println("document.mainform.action = \"trainbook\"  ;                     ");
out.println("document.mainform.submit();");
out.println("}");
out.println("else");
out.println("{alert(strErrMsg);}");
out.println("}");
out.println("function doValidations()");
out.println("{");
out.println("var ddIndex;");
out.println("var strTemp;");
out.println("var strFld;");
out.println("var frmDoc;");
out.println("var strErrMsg;");
out.println("strErrMsg = \"\";");
out.println("frmDoc = document.mainform;            ");
out.println("strFld = frmDoc.login");
out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"Please enter loginId\\n\";          ");
out.println("strFld = frmDoc.password");
out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"Please enter password\\n\"; ");
out.println("return strErrMsg;");
out.println("}");
out.println("</SCRIPT>");
out.println("</head>");
out.println("<body>");
out.println("<FORM name=mainform method=post>");
out.println("<div align=\"center\">");
out.println("<center>");
out.println("<div align=\"center\">");
out.println("<center>");
out.println("<TABLE cellSpacing=0 cellPadding=0 width=750 border=0 style=\"border-collapse: collapse\" bordercolor=\"#111111\">");
out.println("<TBODY>");
out.println("<TR> ");
out.println("<TD class=header><img src=\"images/frontpage.gif\" alt=\"\" width=\"386\" height=\"71\"><img src=\"images/Hdr_AS_Seal.jpg\" width=\"289\" height=\"71\"> ");
out.println("<img src=\"images/1animated12-thumb%5B1%5D.gif\" width=\"67\" height=\"50\"> ");
out.println("</TD>");
out.println("</TR>");
out.println("</TBODY>");
out.println("</TABLE>");
out.println("</center>");
out.println("</div>");
out.println("<p align=\"left\"><font face=\"arial\" size=\"2\"> ");
out.println("<marquee behavior=\"scroll\" style=\"font-family: Courier New; color: #333300; text-decoration: blink; font-size: 18pt; font-style: italic; font-weight: bold\">");
out.println("we share a visi<img src=\"images/Animsun.gif\" width=\"50\" height=\"26\">n ");
out.println("</marquee>");
out.println("</font></p>");
out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
out.println("<tr bordercolor=\"#CCCCCC\" bgcolor=\"#000099\"> ");
out.println("<td width=\"10%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"home.htm\"><font color=\"#FFFFFF\" size=\"5\">Home</font></a></div></td>");
out.println("<td width=\"14%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"services\"><font color=\"#FFFFFF\" size=\"5\">Services</font></a></div></td>");
out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"packagefinal.htm\"><font color=\"#FFFFFF\" size=\"5\">Holiday ");
out.println("Packages </font></a></div></td>");
out.println("<td width=\"11%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"faq.htm\"><font color=\"#FFFFFF\" size=\"5\">FAQs</font></a></div></td>");
out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"register.htm\"><font color=\"#FFFFFF\" size=\"5\">Register ");
out.println("Yourself</font></a></div></td>");
out.println("<td width=\"15%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"aboutus\"><font color=\"#FFFFFF\" size=\"5\">About ");
out.println("Us</font></a></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td colspan=\"6\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
out.println("<tr bgcolor=\"#0000CC\"> ");
out.println("<td width=\"21%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"acc.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
out.println("Accommodation</font></a></div></td>");
out.println("<td width=\"24%\" bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"travel.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
out.println("Traveling Means</font></a></div>");
out.println("<div align=\"center\"></div></td>");
out.println("<td width=\"25%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travelguide.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
out.println("Guide</font></a></div></td>");
out.println("<td width=\"30%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travelinsurance.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
out.println("Insurance</font></a></div></td>");
out.println("</tr>");
out.println("</table></td>");
out.println("</tr>");
out.println("</table>");
out.println("</center>");
out.println("</div>");
out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
out.println("<tr bgcolor=\"#3333FF\"> ");
out.println("<td bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"car.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
out.println("Car</font></a></div></td>");
out.println("<td bgcolor=\"#3399FF\"> <div align=\"center\"><a href=\"train.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
out.println("Train</font></a></div></td>");
out.println("<td bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"flight.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
out.println("Flight</font></a></div></td>");
out.println("<td> <div align=\"center\"><a href=\"cruise.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
out.println("Cruises</font></a></div></td>");
out.println("</tr>");
out.println("</table>");
out.println("<p align=\"center\"><span class=\"style1\"><u><font color=\"#990000\" size=\"6\"><strong>Online resrevation</strong></font></u></span></p>");
out.println("<div align=\"center\"></div>");
out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
out.println("<tr> ");
out.println("<td width=\"35%\" height=\"52\" bgcolor=\"#FFCCFF\"> <table width=\"100%\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#FF99FF\">");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><font size=\"4\"><a href=\"passengerstatus.htm\">Passenger ");
out.println("Status</a></font></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFFFCC\"><div align=\"center\"><font size=\"4\"><a href=\"trainsbetweenimportantstations.htm\">Trains ");
out.println("between important stations</a></font></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><font size=\"4\"><a href=\"avalibiltystatusatstations.htm\">Avalibilty ");
out.println("status at stations</a></font></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFFFCC\"><div align=\"center\"><font size=\"4\"><a href=\"faresoftrains.htm\">Fares ");
out.println("of trains </a> </font></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFCCFF\"> <div align=\"center\"><font size=\"4\"><a href=\"onlinereservation.htm\">Online ");
out.println("Reservation</a></font></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td height=\"25\" bgcolor=\"#FFFFCC\"> <div align=\"center\"><font size=\"4\"><a href=\"timetablet.htm\" target=\"_blank\">Time ");
out.println("Table</a></font></div></td>");
out.println("</tr>");
out.println("</table> ");
out.println("<p>&nbsp;</p></td>");
out.println("<td width=\"65%\"><table width=\"100%\" height=\"267\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"../airfare_search_bg_big.gif\">");
out.println("<tr bgcolor=\"#FFCCFF\"> ");
out.println("<td height=\"39\" colspan=\"2\"> ");
out.println("<div align=\"center\"><font color=\"#660033\" size=\"5\">Online Railway ");
out.println("Reservation</font></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td width=\"69%\" height=\"228\"> ");
out.println("<div align=\"center\"> ");
out.println("<table width=\"100%\" height=\"224\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
out.println("<tr bgcolor=\"#FFCCFF\"> ");
out.println("<td colspan=\"2\"> ");
out.println("<div align=\"center\"><em><strong><font color=\"#660000\" size=\"5\">Invalid ");
out.println("password try again!!!</font></strong></em></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td width=\"41%\" bgcolor=\"#FFCCFF\"> ");
out.println("<div align=\"center\"><strong>Login ID</strong></div></td>");
out.println("<td width=\"59%\" bgcolor=\"#FFCCFF\"> ");
out.println("<div align=\"center\"> ");
out.println("<input name=\"loginid\" type=\"text\" id=\"login\">");
out.println("</div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFCCFF\"> ");
out.println("<div align=\"center\"><strong>Password</strong></div></td>");
out.println("<td bgcolor=\"#FFCCFF\"> ");
out.println("<div align=\"center\"> ");
out.println("<input name=\"pswd\" type=\"password\" id=\"password\">");
out.println("</div></td>");
out.println("</tr>");
out.println("<tr bgcolor=\"#FFCCFF\"> ");
out.println("<td height=\"79\" colspan=\"2\"> ");
out.println("<div align=\"center\" > <strong> ");
out.println("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"147\" height=\"34\">");
out.println("<param name=\"BGCOLOR\" value=\"#FFCCFF\">");
out.println("<param name=\"movie\" value=\"images/oresinvpswd.swf\">");
out.println("<param name=\"quality\" value=\"high\">");
out.println("<embed src=\"images/oresinvpswd.swf\" width=\"147\" height=\"34\" quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" bgcolor=\"#FFCCFF\" base=\"\" ></embed> ");
out.println("</object>");
out.println("</strong></div></td>");
out.println("</tr>");
out.println("</table>");
out.println("</div></td>");
out.println("<td width=\"31%\"><img src=\"images/Southern%20GP59.jpg\" width=\"162\" height=\"225\"></td>");
out.println("</tr>");
out.println("</table></td>");
out.println("</tr>");
out.println("</table>");
out.println("<p align=\"center\"><u></u></p>");
out.println("<HR align=center noShade>");
out.println("<p align=\"center\"><FONT face=Arial size=1>|| <A ");
out.println("href=\"http://www.indianrail.gov.in/abir.html\">Indian Railways</A>| <A href=\"http://www.indianrail.gov.in/pnr_stat.html\" target=DispArea>Passenger ");
out.println("Status</A> | <A href=\"http://www.indianrail.gov.in/acc_avl.html\" ");
out.println("target=DispArea>Seat Availability</A> | <A ");
out.println("href=\"http://www.indianrail.gov.in/fare_enq.html\" target=DispArea>Fare</A> |<BR>");
out.println("| <A href=\"http://www.indianrail.gov.in/src_dest_trns.html\" ");
out.println("target=DispArea>TrainsBetween Stations</A> | <A ");
out.println("href=\"http://www.indianrail.gov.in/inet_trn_num.html\" ");
out.println("target=DispArea>Schedule</A> | <A href=\"http://www.indianrail.gov.in/stn_code.html\" ");
out.println("target=DispArea>Know Station Code?</A> |<A ");
out.println("href=\"http://www.indianrail.gov.in/inet_trn_num.html\" target=DispArea>Know Train ");
out.println("Number?</A> | <BR>");
out.println("| <A href=\"http://www.indianrail.gov.in/seatkt.html\" ");
out.println("target=DispArea>Season Tickets</A> | <A ");
out.println("href=\"http://www.indianrail.gov.in/class.html\" target=DispArea>Class Codes</A> ");
out.println("| <A href=\"http://www.indianrail.gov.in/quotas.html\" target=DispArea>Quota Codes</A>| ");
out.println("<A ");
out.println("href=\"http://www.indianrail.gov.in/resrules.html\" target=DispArea>Reservation ");
out.println("Rules</A><BR>");
out.println("| <A href=\"http://www.indianrail.gov.in/refund_rules.html\" ");
out.println("target=DispArea>Refund Rules</A> | <A ");
out.println("href=\"http://www.indianrail.gov.in/break.html\" target=DispArea>Break Journey Rules</A> ");
out.println("| <A ");
out.println("href=\"http://www.indianrail.gov.in/tatkal.html\" target=DispArea>Tatkal Trains&nbsp;</A> ");
out.println("||</FONT> </p>");
out.println("<HR align=center noShade>");
out.println("<p>&nbsp;</p>");
out.println("</body>");
out.println("</html>");


                   
                }

               else
                 {

out.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">");
out.println("<html>");
out.println("<head>");
out.println("<title>trainbook</title>");
out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
out.println("<SCRIPT>");
out.println("function doClear()");
out.println("{       ");
out.println("document.mainform.trainno.value =\"\";");
out.println("document.mainform.not.value = \"\";");
out.println("document.mainform.trainno.value = \"\";");
out.println("document.mainform.cardno.value = \"\";");
out.println("}");
out.println("function doSubmit()");
out.println("{");
out.println("var strErrMsg;         ");
out.println("strErrMsg = \"\";          ");
out.println("strErrMsg = doValidations();");
out.println("if (strErrMsg == \"\" )");
out.println("{                          ");
out.println("document.mainform.action = \"bookingconfirm\"  ;                ");
out.println("document.mainform.submit();");
out.println("}");
out.println("else");
out.println("{alert(strErrMsg);}");
out.println("}");
out.println("function doValidations()");
out.println("{         ");
out.println("var ddIndex;");
out.println("var strTemp;");
out.println("var strFld;");
out.println("var frmDoc;");
out.println("var strErrMsg;");
out.println("strErrMsg = \"\";");
out.println("frmDoc = document.mainform;            ");
out.println("strFld = frmDoc.loginid");
out.println("if (strFld.value == \"\")                  ");
out.println("strErrMsg = strErrMsg + \"Please enter the customer ID\\n\";    ");
out.println("strFld = frmDoc.not");
out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"Please enter no of tickets\\n\";");
out.println("strFld = frmDoc.trainno");
out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"Please enter train no\\n\";");
out.println("strFld = frmDoc.cardno");
out.println("if (strFld.value == \"\"|| strFld.value.length<4 || strFld.value.length >4 )       ");
out.println("strErrMsg = strErrMsg + \" Credit Crad No. is Invalid\\n\"; ");
out.println("return strErrMsg;");
out.println("}");
out.println("</SCRIPT>");
out.println("</head>");
out.println("<body bgcolor=\"#FFFFFF\">");
out.println("<FORM name=mainform method=post>");
out.println("<div align=\"center\">");
out.println("<center>");
out.println("<div align=\"center\">");
out.println("<center>");
out.println("<TABLE cellSpacing=0 cellPadding=0 width=750 border=0 style=\"border-collapse: collapse\" bordercolor=\"#111111\">");
out.println("<TBODY>");
out.println("<TR> ");
out.println("<TD class=header><img src=\"images/frontpage.gif\" alt=\"\" width=\"386\" height=\"71\"><img src=\"images/Hdr_AS_Seal.jpg\" width=\"289\" height=\"71\"> ");
out.println("<img src=\"images/1animated12-thumb%5B1%5D.gif\" width=\"67\" height=\"50\"> ");
out.println("</TD>");
out.println("</TR>");
out.println("</TBODY>");
out.println("</TABLE>");
out.println("</center>");
out.println("</div>");
out.println("<p align=\"left\"><font face=\"arial\" size=\"2\"> ");
out.println("<marquee behavior=\"scroll\" style=\"font-family: Courier New; color: #333300; text-decoration: blink; font-size: 18pt; font-style: italic; font-weight: bold\">");
out.println("we share a visi<img src=\"images/Animsun.gif\" width=\"50\" height=\"26\">n ");
out.println("</marquee>");
out.println("</font></p>");
out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
out.println("<tr bordercolor=\"#CCCCCC\" bgcolor=\"#000099\"> ");
out.println("<td width=\"10%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"home.htm\"><font color=\"#FFFFFF\" size=\"5\">Home</font></a></div></td>");
out.println("<td width=\"14%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"services\"><font color=\"#FFFFFF\" size=\"5\">Services</font></a></div></td>");
out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"packagefinal.htm\"><font color=\"#FFFFFF\" size=\"5\">Holiday ");
out.println("Packages </font></a></div></td>");
out.println("<td width=\"11%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"faq.htm\"><font color=\"#FFFFFF\" size=\"5\">FAQs</font></a></div></td>");
out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"register.htm\"><font color=\"#FFFFFF\" size=\"5\">Register ");
out.println("Yourself</font></a></div></td>");
out.println("<td width=\"15%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"aboutus\"><font color=\"#FFFFFF\" size=\"5\">About ");
out.println("Us</font></a></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td colspan=\"6\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
out.println("<tr bgcolor=\"#0000CC\"> ");
out.println("<td width=\"21%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"acc.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
out.println("Accommodation</font></a></div></td>");
out.println("<td width=\"24%\" bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"travel.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
out.println("Traveling Means</font></a></div>");
out.println("<div align=\"center\"></div></td>");
out.println("<td width=\"25%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travelguide.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
out.println("Guide</font></a></div></td>");
out.println("<td width=\"30%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travelinsurance.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
out.println("Insurance</font></a></div></td>");
out.println("</tr>");
out.println("</table></td>");
out.println("</tr>");
out.println("</table>");
out.println("</center>");
out.println("</div>");
out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
out.println("<tr bgcolor=\"#3333FF\"> ");
out.println("<td bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"car.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
out.println("Car</font></a></div></td>");
out.println("<td bgcolor=\"#3399FF\"> <div align=\"center\"><a href=\"train.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
out.println("Train</font></a></div></td>");
out.println("<td bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"flight.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
out.println("Flight</font></a></div></td>");
out.println("<td> <div align=\"center\"><a href=\"cruise.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
out.println("Cruises</font></a></div></td>");
out.println("</tr>");
out.println("</table>");
out.println("<p align=\"center\"><span class=\"style1\"><u><font color=\"#990000\" size=\"6\"><strong>Online resrevation</strong></font></u></span></p>");
out.println("<div align=\"center\"></div>");
out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
out.println("<tr> ");
out.println("<td width=\"35%\" height=\"52\" bgcolor=\"#FFCCFF\"> <table width=\"100%\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#FF99FF\">");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><font size=\"4\"><a href=\"passengerstatus.htm\">Passenger ");
out.println("Status</a></font></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFFFCC\"><div align=\"center\"><font size=\"4\"><a href=\"trainsbetweenimportantstations.htm\">Trains ");
out.println("between important stations</a></font></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><font size=\"4\"><a href=\"avalibiltystatusatstations.htm\">Avalibilty ");
out.println("status at stations</a></font></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFFFCC\"><div align=\"center\"><font size=\"4\"><a href=\"faresoftrains.htm\">Fares ");
out.println("of trains </a> </font></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFCCFF\"> <div align=\"center\"><font size=\"4\"><a href=\"onlinereservation.htm\">Online ");
out.println("Reservation</a></font></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td height=\"25\" bgcolor=\"#FFFFCC\"> <div align=\"center\"><font size=\"4\"><a href=\"timetablet.htm\" target=\"_blank\">Time ");
out.println("Table</a></font></div></td>");
out.println("</tr>");
out.println("</table> ");
out.println("</td>");
out.println("<td width=\"65%\" bgcolor=\"#FFCCFF\"> ");
out.println("<table width=\"88%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#660033\" background=\"../hcutravels/airfare_search_bg_big.gif\">");
out.println("<tr bgcolor=\"#FFCCFF\"> ");
out.println("<td height=\"29\" colspan=\"2\"> ");
out.println("<div align=\"center\"> ");
out.println("<p><font color=\"#660033\" size=\"5\">Railway reservation </font><font color=\"#660033\" size=\"5\">Form</font></p>");
out.println("</div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td width=\"60%\" bgcolor=\"#FFCCFF\"><font size=\"4\"> Enter Your Customer ");
out.println("ID</font></td>");
out.println("<td width=\"40%\" bgcolor=\"#FFCCFF\"> ");
out.println("<INPUT name=\"loginid\" type=\"text\"class=if id=\"login\" value=\"" +loginid+ "\" size=\"25\" maxlength=\"25\" > ");
out.println("</td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td height=\"20\" bgcolor=\"#FFCCFF\"><font size=\"4\">Departure From</font></td>");
out.println("<td bgcolor=\"#FFCCFF\"><B> ");
out.println("<select name=\"source\" id=\"source\">");
out.println("<OPTION value=ABR>ABU ROAD - ABR ");
out.println("<OPTION value=AGC>AGRA CANTT - AGC ");
out.println("<OPTION value=AF>AGRA FORT - AF ");
out.println("<OPTION value=AGA>AGRA CITY - AGA ");
out.println("<OPTION value=ADI>AHMEDABAD JN - ADI ");
out.println("<OPTION value=AII>AJMER - AII ");
out.println("<OPTION value=AK>AKOLA - AK ");
out.println("<OPTION value=ALJN>ALIGARH JN - ALJN ");
out.println("<OPTION value=ALD>ALLAHABAD - ALD ");
out.println("<OPTION value=ALLP>ALLEPPEY - ALLP ");
out.println("<OPTION value=AWR>ALWAR - AWR ");
out.println("<OPTION value=AWY>ALWAYE - AWY ");
out.println("<OPTION ");
out.println("value=UMB>AMBALA - UMB ");
out.println("<OPTION value=AME>AMETHI - AME ");
out.println("<OPTION ");
out.println("value=AMI>AMRAVATI - AMI ");
out.println("<OPTION value=ASR>AMRITSAR - ASR ");
out.println("<OPTION ");
out.println("value=ASN>ASANSOL JN - ASN ");
out.println("<OPTION value=AWB>AURANGABAD - AWB ");
out.println("<OPTION ");
out.println("value=AMH>AZAMGARH - AMH ");
out.println("<OPTION value=BRK>BAHRAICH - BRK ");
out.println("<OPTION ");
out.println("value=SBC>BANGALORE - SBC ");
out.println("<OPTION value=BUI>BALLIA - BUI ");
out.println("<OPTION ");
out.println("value=BWT>BANGARAPET - BWT ");
out.println("<OPTION value=BP>BARRACKPORE - BP ");
out.println("<OPTION ");
out.println("value=BJU>BARAUNI JN - BJU ");
out.println("<OPTION value=BE>BAREILLY - BE ");
out.println("<OPTION ");
out.println("value=BST>BASTI - BST ");
out.println("<OPTION value=BSL>BHUSAVAL - BSL ");
out.println("<OPTION ");
out.println("value=BGS>BEGU SARAI - BGS ");
out.println("<OPTION value=BGM>BELGAUM - BGM ");
out.println("<OPTION ");
out.println("value=BAY>BELLARY - BAY ");
out.println("<OPTION value=BGP>BHAGALPUR - BGP ");
out.println("<OPTION ");
out.println("value=BKN>BIKANER JN - BKN ");
out.println("<OPTION value=BSP>BILASPUR - BSP ");
out.println("<OPTION ");
out.println("value=BINA>BINA - BINA ");
out.println("<OPTION value=BPL>BHOPAL - BPL ");
out.println("<OPTION ");
out.println("value=BTI>BHATINDA - BTI ");
out.println("<OPTION value=BKSC>BOKARO STL CITY - BKSC ");
out.println("<OPTION ");
out.println("value=BBS>BHUBANESHWAR - BBS ");
out.println("<OPTION value=BWN>BURDWAN - BWN ");
out.println("<OPTION ");
out.println("value=BXR>BUXAR - BXR ");
out.println("<OPTION value=CLT>CALICUT - CLT ");
out.println("<OPTION ");
out.println("value=CDG>CHANDIGARH - CDG ");
out.println("<OPTION value=MAS>CHENNAI - MAS ");
out.println("<OPTION ");
out.println("value=CHTS>COCHIN - CHTS ");
out.println("<OPTION value=CRJ>CHITTARANJAN - CRJ ");
out.println("<OPTION ");
out.println("value=CBE>COIMBATORE JN - CBE ");
out.println("<OPTION value=DBG>DARBHANGA JN - DBG ");
out.println("<OPTION ");
out.println("value=DJ>DARJEELING - DJ ");
out.println("<OPTION value=DDN>DEHRADUN - DDN ");
out.println("<OPTION ");
out.println("value=DHN>DHANBAD JN - DHN ");
out.println("<OPTION value=DWR>DHARWAR - DWR ");
out.println("<OPTION ");
out.println("value=DURG>DURG - DURG ");
out.println("<OPTION value=DBRT>DIBRUGARH TOWN - DBRT ");
out.println("<OPTION ");
out.println("value=ERS>ERNAKULAM - ERS ");
out.println("<OPTION value=ED>ERODE - ED ");
out.println("<OPTION ");
out.println("value=FD>FAIZABAD JN - FD ");
out.println("<OPTION value=FDB>FARIDABAD - FDB ");
out.println("<OPTION ");
out.println("value=FBD>FARUKHABAD - FBD ");
out.println("<OPTION value=GAYA>GAYA JN - GAYA ");
out.println("<OPTION ");
out.println("value=G>GONDIA - G ");
out.println("<OPTION value=GKP>GORAKHPUR JN - GKP ");
out.println("<OPTION ");
out.println("value=GR>GULBARGA - GR ");
out.println("<OPTION value=GNT>GUNTUR - GNT ");
out.println("<OPTION ");
out.println("value=GHY>GUWAHATI - GHY ");
out.println("<OPTION value=GWL>GWALIOR - GWL ");
out.println("<OPTION ");
out.println("value=HBJ>HABIBGANJ - HBJ ");
out.println("<OPTION value=HW>HARIDWAR JN - HW ");
out.println("<OPTION ");
out.println("value=HWH>HOWRAH - HWH ");
out.println("<OPTION value=HYB>HYDERABAD - HYB ");
out.println("<OPTION ");
out.println("value=INDB>INDORE JN BG - INDB ");
out.println("<OPTION value=ET>ITARSI - ET ");
out.println("<OPTION ");
out.println("value=JBP>JABALPUR - JBP ");
out.println("<OPTION value=JP>JAIPUR - JP ");
out.println("<OPTION ");
out.println("value=JSM>JAISALMER - JSM ");
out.println("<OPTION value=JUC>JALANDHAR CITY - JUC ");
out.println("<OPTION ");
out.println("value=JAT>JAMMU - JAT ");
out.println("<OPTION value=JHS>JHANSI JN - JHS ");
out.println("<OPTION ");
out.println("value=JU>JODHPUR - JU ");
out.println("<OPTION value=KLK>KALKA - KLK ");
out.println("<OPTION ");
out.println("value=CNB>KANPUR - CNB ");
out.println("<OPTION value=CAPE>KANYAKUMARI - CAPE ");
out.println("<OPTION ");
out.println("value=KGM>KATHGODAM - KGM ");
out.println("<OPTION value=KPD>KATPADI - KPD ");
out.println("<OPTION ");
out.println("value=HWH>KOLKATA - HWH ");
out.println("<OPTION value=KOTA>KOTA JN - KOTA ");
out.println("<OPTION ");
out.println("value=KTYM>KOTTAYAM - KTYM ");
out.println("<OPTION value=KZJ>KAZIPET - KZJ ");
out.println("<OPTION ");
out.println("value=LKO>LUCKNOW - LKO ");
out.println("<OPTION value=LDH>LUDHIANA - LDH ");
out.println("<OPTION ");
out.println("value=MAO>MADGAON - MAO ");
out.println("<OPTION value=MDU>MADURAI - MDU ");
out.println("<OPTION ");
out.println("value=MMC>MAHAMANDIR - MMC ");
out.println("<OPTION value=MAQ>MANGALORE - MAQ ");
out.println("<OPTION ");
out.println("value=MMR>MANMAD - MMR ");
out.println("<OPTION value=MTJ>MATHURA JN - MTJ ");
out.println("<OPTION ");
out.println("value=MAU>MAU JN - MAU ");
out.println("<OPTION value=MTC>MEERUT CITY - MTC ");
out.println("<OPTION ");
out.println("value=MB>MORADABAD - MB ");
out.println("<OPTION value=MGS>MUGHAL SARAI - MGS ");
out.println("<OPTION ");
out.println("value=BCT>MUMBAI - BCT ");
out.println("<OPTION value=MYS>MYSORE - MYS ");
out.println("<OPTION ");
out.println("value=NGP>NAGPUR - NGP ");
out.println("<OPTION value=NK>NASIK - NK ");
out.println("<OPTION ");
out.println("value=NLR>NELLORE - NLR ");
out.println("<OPTION value=NJP>NEW JALPAIGURI - NJP ");
out.println("<OPTION ");
out.println("selected value=NDLS>NEW DELHI - NDLS ");
out.println("<OPTION value=PGT>PALGHAT - PGT ");
out.println("<OPTION value=PNP>PANIPAT JN - PNP ");
out.println("<OPTION value=PTA>PATIALA - PTA ");
out.println("<OPTION value=PNBE>PATNA JN - PNBE ");
out.println("<OPTION value=PUNE>PUNE JN - PUNE ");
out.println("<OPTION value=PTBY>PUTTAPARTHI OA - PTBY ");
out.println("<OPTION value=RBL>RAE BARELI JN - RBL ");
out.println("<OPTION value=RIG>RAIGARH - RIG ");
out.println("<OPTION value=R>RAIPUR - R ");
out.println("<OPTION ");
out.println("value=RMM>RAMESWARAM - RMM ");
out.println("<OPTION value=RNC>RANCHI - RNC ");
out.println("<OPTION ");
out.println("value=RRME>RANCHI ROAD - RRME ");
out.println("<OPTION value=RTM>RATLAM - RTM ");
out.println("<OPTION ");
out.println("value=RN>RATNAGIRI - RN ");
out.println("<OPTION value=REWA>REWA - REWA ");
out.println("<OPTION ");
out.println("value=ROK>ROHTAK - ROK ");
out.println("<OPTION value=RKSH>RISHIKESH - RKSH ");
out.println("<OPTION ");
out.println("value=RK>ROORKEE - RK ");
out.println("<OPTION value=ROU>ROURKELA - ROU ");
out.println("<OPTION ");
out.println("value=SRE>SAHARANPUR - SRE ");
out.println("<OPTION value=SA>SALEM - SA ");
out.println("<OPTION ");
out.println("value=SLI>SANGLI - SLI ");
out.println("<OPTION value=STA>SATNA - STA ");
out.println("<OPTION ");
out.println("value=SNP>SONIPAT - SNP ");
out.println("<OPTION value=SCL>SILCHAR - SCL ");
out.println("<OPTION ");
out.println("value=SML>SIMLA - SML ");
out.println("<OPTION value=SVKS>SIVAKASI - SVKS ");
out.println("<OPTION ");
out.println("value=ST>SURAT - ST ");
out.println("<OPTION value=TATA>TATANAGAR JN - TATA ");
out.println("<OPTION ");
out.println("value=TNA>THANE - TNA ");
out.println("<OPTION value=TJ>THANJAVUR - TJ ");
out.println("<OPTION ");
out.println("value=TPTY>TIRUPATI - TPTY ");
out.println("<OPTION value=TPJ>TIRUCHIRAPALLI - TPJ ");
out.println("<OPTION ");
out.println("value=TCR>TRICHUR - TCR ");
out.println("<OPTION value=TVC>TRIVANDRUM - TVC ");
out.println("<OPTION ");
out.println("value=TN>TUTICORIN - TN ");
out.println("<OPTION value=UDZ>UDAIPUR - UDZ ");
out.println("<OPTION ");
out.println("value=UJN>UJJAIN - UJN ");
out.println("<OPTION value=BRC>VADODARA - BRC ");
out.println("<OPTION ");
out.println("value=BSB>VARANASI JN - BSB ");
out.println("<OPTION value=VSG>VASCO DA GAMA - VSG ");
out.println("<OPTION ");
out.println("value=BZA>VIJAYAWADA JN - BZA ");
out.println("<OPTION value=VSKP>VISHAKAPATNAM - VSKP ");
out.println("<OPTION value=WL>WARANGAL - WL ");
out.println("<OPTION value=WR>WARDHA - WR</OPTION>");
out.println("</SELECT>");
out.println("</B> </td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFCCFF\"><font size=\"4\">Arrival To</font></td>");
out.println("<td bgcolor=\"#FFCCFF\"><B> ");
out.println("<select name=\"destination\" id=\"destination\">");
out.println("<OPTION ");
out.println("value=ABR>ABU ROAD - ABR ");
out.println("<OPTION value=AGC>AGRA CANTT - AGC ");
out.println("<OPTION ");
out.println("value=AF>AGRA FORT - AF ");
out.println("<OPTION value=AGA>AGRA CITY - AGA ");
out.println("<OPTION ");
out.println("value=ADI>AHMEDABAD JN - ADI ");
out.println("<OPTION value=AII>AJMER - AII ");
out.println("<OPTION ");
out.println("value=AK>AKOLA - AK ");
out.println("<OPTION value=ALJN>ALIGARH JN - ALJN ");
out.println("<OPTION ");
out.println("value=ALD>ALLAHABAD - ALD ");
out.println("<OPTION value=ALLP>ALLEPPEY - ALLP ");
out.println("<OPTION ");
out.println("value=AWR>ALWAR - AWR ");
out.println("<OPTION value=AWY>ALWAYE - AWY ");
out.println("<OPTION ");
out.println("value=UMB>AMBALA - UMB ");
out.println("<OPTION value=AME>AMETHI - AME ");
out.println("<OPTION ");
out.println("value=AMI>AMRAVATI - AMI ");
out.println("<OPTION value=ASR>AMRITSAR - ASR ");
out.println("<OPTION ");
out.println("value=ASN>ASANSOL JN - ASN ");
out.println("<OPTION value=AWB>AURANGABAD - AWB ");
out.println("<OPTION ");
out.println("value=AMH>AZAMGARH - AMH ");
out.println("<OPTION value=BRK>BAHRAICH - BRK ");
out.println("<OPTION ");
out.println("value=SBC>BANGALORE - SBC ");
out.println("<OPTION value=BUI>BALLIA - BUI ");
out.println("<OPTION ");
out.println("value=BWT>BANGARAPET - BWT ");
out.println("<OPTION value=BP>BARRACKPORE - BP ");
out.println("<OPTION ");
out.println("value=BJU>BARAUNI JN - BJU ");
out.println("<OPTION value=BE>BAREILLY - BE ");
out.println("<OPTION ");
out.println("value=BST>BASTI - BST ");
out.println("<OPTION value=BSL>BHUSAVAL - BSL ");
out.println("<OPTION ");
out.println("value=BGS>BEGU SARAI - BGS ");
out.println("<OPTION value=BGM>BELGAUM - BGM ");
out.println("<OPTION ");
out.println("value=BAY>BELLARY - BAY ");
out.println("<OPTION value=BGP>BHAGALPUR - BGP ");
out.println("<OPTION ");
out.println("value=BKN>BIKANER JN - BKN ");
out.println("<OPTION value=BSP>BILASPUR - BSP ");
out.println("<OPTION ");
out.println("value=BINA>BINA - BINA ");
out.println("<OPTION value=BPL>BHOPAL - BPL ");
out.println("<OPTION ");
out.println("value=BTI>BHATINDA - BTI ");
out.println("<OPTION value=BKSC>BOKARO STL CITY - BKSC ");
out.println("<OPTION ");
out.println("value=BBS>BHUBANESHWAR - BBS ");
out.println("<OPTION value=BWN>BURDWAN - BWN ");
out.println("<OPTION ");
out.println("value=BXR>BUXAR - BXR ");
out.println("<OPTION value=CLT>CALICUT - CLT ");
out.println("<OPTION ");
out.println("value=CDG>CHANDIGARH - CDG ");
out.println("<OPTION value=MAS>CHENNAI - MAS ");
out.println("<OPTION ");
out.println("value=CHTS>COCHIN - CHTS ");
out.println("<OPTION value=CRJ>CHITTARANJAN - CRJ ");
out.println("<OPTION ");
out.println("value=CBE>COIMBATORE JN - CBE ");
out.println("<OPTION value=DBG>DARBHANGA JN - DBG ");
out.println("<OPTION ");
out.println("value=DJ>DARJEELING - DJ ");
out.println("<OPTION value=DDN>DEHRADUN - DDN ");
out.println("<OPTION ");
out.println("value=DHN>DHANBAD JN - DHN ");
out.println("<OPTION value=DWR>DHARWAR - DWR ");
out.println("<OPTION ");
out.println("value=DURG>DURG - DURG ");
out.println("<OPTION value=DBRT>DIBRUGARH TOWN - DBRT ");
out.println("<OPTION ");
out.println("value=ERS>ERNAKULAM - ERS ");
out.println("<OPTION value=ED>ERODE - ED ");
out.println("<OPTION ");
out.println("value=FD>FAIZABAD JN - FD ");
out.println("<OPTION value=FDB>FARIDABAD - FDB ");
out.println("<OPTION ");
out.println("value=FBD>FARUKHABAD - FBD ");
out.println("<OPTION value=GAYA>GAYA JN - GAYA ");
out.println("<OPTION ");
out.println("value=G>GONDIA - G ");
out.println("<OPTION value=GKP>GORAKHPUR JN - GKP ");
out.println("<OPTION ");
out.println("value=GR>GULBARGA - GR ");
out.println("<OPTION value=GNT>GUNTUR - GNT ");
out.println("<OPTION ");
out.println("value=GHY>GUWAHATI - GHY ");
out.println("<OPTION value=GWL>GWALIOR - GWL ");
out.println("<OPTION ");
out.println("value=HBJ>HABIBGANJ - HBJ ");
out.println("<OPTION value=HW>HARIDWAR JN - HW ");
out.println("<OPTION ");
out.println("value=HWH>HOWRAH - HWH ");
out.println("<OPTION value=HYB>HYDERABAD - HYB ");
out.println("<OPTION ");
out.println("value=INDB>INDORE JN BG - INDB ");
out.println("<OPTION value=ET>ITARSI - ET ");
out.println("<OPTION ");
out.println("value=JBP>JABALPUR - JBP ");
out.println("<OPTION value=JP>JAIPUR - JP ");
out.println("<OPTION ");
out.println("value=JSM>JAISALMER - JSM ");
out.println("<OPTION value=JUC>JALANDHAR CITY - JUC ");
out.println("<OPTION ");
out.println("value=JAT>JAMMU - JAT ");
out.println("<OPTION value=JHS>JHANSI JN - JHS ");
out.println("<OPTION ");
out.println("value=JU>JODHPUR - JU ");
out.println("<OPTION value=KLK>KALKA - KLK ");
out.println("<OPTION ");
out.println("value=CNB>KANPUR - CNB ");
out.println("<OPTION value=CAPE>KANYAKUMARI - CAPE ");
out.println("<OPTION ");
out.println("value=KGM>KATHGODAM - KGM ");
out.println("<OPTION value=KPD>KATPADI - KPD ");
out.println("<OPTION ");
out.println("value=HWH>KOLKATA - HWH ");
out.println("<OPTION value=KOTA>KOTA JN - KOTA ");
out.println("<OPTION ");
out.println("value=KTYM>KOTTAYAM - KTYM ");
out.println("<OPTION value=KZJ>KAZIPET - KZJ ");
out.println("<OPTION ");
out.println("value=LKO>LUCKNOW - LKO ");
out.println("<OPTION value=LDH>LUDHIANA - LDH ");
out.println("<OPTION ");
out.println("value=MAO>MADGAON - MAO ");
out.println("<OPTION value=MDU>MADURAI - MDU ");
out.println("<OPTION ");
out.println("value=MMC>MAHAMANDIR - MMC ");
out.println("<OPTION value=MAQ>MANGALORE - MAQ ");
out.println("<OPTION ");
out.println("value=MMR>MANMAD - MMR ");
out.println("<OPTION value=MTJ>MATHURA JN - MTJ ");
out.println("<OPTION ");
out.println("value=MAU>MAU JN - MAU ");
out.println("<OPTION value=MTC>MEERUT CITY - MTC ");
out.println("<OPTION ");
out.println("value=MB>MORADABAD - MB ");
out.println("<OPTION value=MGS>MUGHAL SARAI - MGS ");
out.println("<OPTION ");
out.println("selected value=BCT>MUMBAI - BCT ");
out.println("<OPTION value=MYS>MYSORE - MYS ");
out.println("<OPTION ");
out.println("value=NGP>NAGPUR - NGP ");
out.println("<OPTION value=NK>NASIK - NK ");
out.println("<OPTION ");
out.println("value=NLR>NELLORE - NLR ");
out.println("<OPTION value=NJP>NEW JALPAIGURI - NJP ");
out.println("<OPTION ");
out.println("value=NDLS>NEW DELHI - NDLS ");
out.println("<OPTION value=PGT>PALGHAT - PGT ");
out.println("<OPTION ");
out.println("value=PNP>PANIPAT JN - PNP ");
out.println("<OPTION value=PTA>PATIALA - PTA ");
out.println("<OPTION ");
out.println("value=PNBE>PATNA JN - PNBE ");
out.println("<OPTION value=PUNE>PUNE JN - PUNE ");
out.println("<OPTION ");
out.println("value=PTBY>PUTTAPARTHI OA - PTBY ");
out.println("<OPTION value=RBL>RAE BARELI JN - RBL ");
out.println("<OPTION value=RIG>RAIGARH - RIG ");
out.println("<OPTION value=R>RAIPUR - R ");
out.println("<OPTION ");
out.println("value=RMM>RAMESWARAM - RMM ");
out.println("<OPTION value=RNC>RANCHI - RNC ");
out.println("<OPTION ");
out.println("value=RRME>RANCHI ROAD - RRME ");
out.println("<OPTION value=RTM>RATLAM - RTM ");
out.println("<OPTION ");
out.println("value=RN>RATNAGIRI - RN ");
out.println("<OPTION value=REWA>REWA - REWA ");
out.println("<OPTION ");
out.println("value=ROK>ROHTAK - ROK ");
out.println("<OPTION value=RKSH>RISHIKESH - RKSH ");
out.println("<OPTION ");
out.println("value=RK>ROORKEE - RK ");
out.println("<OPTION value=ROU>ROURKELA - ROU ");
out.println("<OPTION ");
out.println("value=SRE>SAHARANPUR - SRE ");
out.println("<OPTION value=SA>SALEM - SA ");
out.println("<OPTION ");
out.println("value=SLI>SANGLI - SLI ");
out.println("<OPTION value=STA>SATNA - STA ");
out.println("<OPTION ");
out.println("value=SNP>SONIPAT - SNP ");
out.println("<OPTION value=SCL>SILCHAR - SCL ");
out.println("<OPTION ");
out.println("value=SML>SIMLA - SML ");
out.println("<OPTION value=SVKS>SIVAKASI - SVKS ");
out.println("<OPTION ");
out.println("value=ST>SURAT - ST ");
out.println("<OPTION value=TATA>TATANAGAR JN - TATA ");
out.println("<OPTION ");
out.println("value=TNA>THANE - TNA ");
out.println("<OPTION value=TJ>THANJAVUR - TJ ");
out.println("<OPTION ");
out.println("value=TPTY>TIRUPATI - TPTY ");
out.println("<OPTION value=TPJ>TIRUCHIRAPALLI - TPJ ");
out.println("<OPTION ");
out.println("value=TCR>TRICHUR - TCR ");
out.println("<OPTION value=TVC>TRIVANDRUM - TVC ");
out.println("<OPTION ");
out.println("value=TN>TUTICORIN - TN ");
out.println("<OPTION value=UDZ>UDAIPUR - UDZ ");
out.println("<OPTION ");
out.println("value=UJN>UJJAIN - UJN ");
out.println("<OPTION value=BRC>VADODARA - BRC ");
out.println("<OPTION ");
out.println("value=BSB>VARANASI JN - BSB ");
out.println("<OPTION value=VSG>VASCO DA GAMA - VSG ");
out.println("<OPTION ");
out.println("value=BZA>VIJAYAWADA JN - BZA ");
out.println("<OPTION value=VSKP>VISHAKAPATNAM - VSKP ");
out.println("<OPTION value=WL>WARANGAL - WL ");
out.println("<OPTION value=WR>WARDHA - WR</OPTION>");
out.println("</SELECT>");
out.println("</B></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFCCFF\"><font size=\"4\">Departure Date</font></td>");
out.println("<td bgcolor=\"#FFCCFF\"> ");
out.println("<select name=\"sdd\" id=\"sdd\">");
out.println("<option value=\"1\">01</option>");
out.println("<option value=\"2\">02</option>");
out.println("<option value=\"3\">03</option>");
out.println("<option value=\"4\">04</option>");
out.println("<option value=\"5\">05</option>");
out.println("<option value=\"6\">06</option>");
out.println("<option value=\"7\">07</option>");
out.println("<option value=\"8\">08</option>");
out.println("<option value=\"9\">09</option>");
out.println("<option value=\"10\">10</option>");
out.println("<option value=\"11\">11</option>");
out.println("<option value=\"12\">12</option>");
out.println("<option value=\"13\" selected>13</option>");
out.println("<option value=\"14\">14</option>");
out.println("<option value=\"15\">15</option>");
out.println("<option value=\"16\">16</option>");
out.println("<option value=\"17\">17</option>");
out.println("<option value=\"18\">18</option>");
out.println("<option value=\"19\">19</option>");
out.println("<option value=\"20\">20</option>");
out.println("<option value=\"21\">21</option>");
out.println("<option value=\"22\">22</option>");
out.println("<option value=\"23\">23</option>");
out.println("<option value=\"24\">24</option>");
out.println("<option value=\"25\">25</option>");
out.println("<option value=\"26\">26</option>");
out.println("<option value=\"27\">27</option>");
out.println("<option value=\"28\">28</option>");
out.println("<option value=\"29\">29</option>");
out.println("<option value=\"30\">30</option>");
out.println("<option value=\"31\">31</option>");
out.println("</select> ");
out.println("<select name=\"smm\" id=\"smm\">");
out.println("<option value=\"1\">JAN</option>");
out.println("<option value=\"2\">FEB</option>");
out.println("<option value=\"3\">MAR</option>");
out.println("<option value=\"4\">APR</option>");
out.println("<option value=\"5\">MAY</option>");
out.println("<option value=\"6\">JUN</option>");
out.println("<option value=\"7\">JUL</option>");
out.println("<option value=\"8\">AUG</option>");
out.println("<option value=\"9\">SEP</option>");
out.println("<option value=\"10\">OCT</option>");
out.println("<option value=\"11\" selected>NOV</option>");
out.println("<option value=\"12\">DEC</option>");
out.println("</select> ");
out.println("<select name=\"syy\" id=\"syy\">");
out.println("<option value=\"04\" selected>2004</option>");
out.println("<option value=\"05\">2005</option>");
out.println("</select>");
out.println("</td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td valign=\"top\" bgcolor=\"#FFCCFF\"> ");
out.println("<p><font size=\"4\">No Of Tickets</font></p></td>");
out.println("<td bgcolor=\"#FFCCFF\"> ");
out.println("<input name=\"not\" type=\"text\" id=\"not\" size=\"4\">");
out.println("</td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFCCFF\"><font size=\"4\">No of children below five years</font></td>");
out.println("<td bgcolor=\"#FFCCFF\">");
out.println("<input name=\"noc\" type=\"text\" id=\"noc\" value=\"0\" size=\"4\">");
out.println("</td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFCCFF\"><font size=\"4\">Class</font></td>");
out.println("<td bgcolor=\"#FFCCFF\"> ");
out.println("<SELECT name=class size=1 id=\"class\">");
out.println("<OPTION ");
out.println("value=ZZ>All Class ");
out.println("<OPTION value=1A>First AC ");
out.println("<OPTION value=2A>Second AC ");
out.println("<OPTION value=3A>Third AC ");
out.println("<OPTION value=CC>AC Chair Car ");
out.println("<OPTION ");
out.println("value=FC>First Class ");
out.println("<OPTION selected value=SL>Sleeper Class ");
out.println("<OPTION ");
out.println("value=2S>Second Seating</OPTION>");
out.println("</SELECT>");
out.println("</td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFCCFF\"><font size=\"4\">Train no.</font></td>");
out.println("<td bgcolor=\"#FFCCFF\"> ");
out.println("<input name=\"trainno\" type=\"text\" id=\"trainno\"size=\"4\" maxlength=\"4\">");
out.println("</td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td height=\"40\" bgcolor=\"#FFCCFF\"> ");
out.println("<p><font size=\"4\">Enter last four digits of your Credit Card No.</font></p></td>");
out.println("<td bgcolor=\"#FFCCFF\"> ");
out.println("<input name=\"cardno\" type=\"password\" id=\"cardno\" size=\"4\" maxlength=\"4\">");
out.println("</td>");
out.println("</tr>");
out.println("</table>");
out.println("<p align=\"center\" > ");
out.println("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"147\" height=\"34\">");
out.println("<param name=\"BGCOLOR\" value=\"#FFCCFF\">");
out.println("<param name=\"movie\" value=\"images/getit.swf\">");
out.println("<param name=\"quality\" value=\"high\">");
out.println("<embed src=\"images/getit.swf\" width=\"147\" height=\"34\" quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" bgcolor=\"#FFCCFF\" ></embed> ");
out.println("</object>");
out.println("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"147\" height=\"34\">");
out.println("<param name=\"BGCOLOR\" value=\"#FFCCFF\">");
out.println("<param name=\"movie\" value=\"images/cleardata.swf\">");
out.println("<param name=\"quality\" value=\"high\">");
out.println("<embed src=\"images/cleardata.swf\" width=\"147\" height=\"34\" quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" bgcolor=\"#FFCCFF\" ></embed> ");
out.println("</object>");
out.println("</p></td>");
out.println("</tr>");
out.println("</table>");
out.println("<p align=\"center\"><u></u></p>");
out.println("<HR align=center noShade>");
out.println("<p align=\"center\"><FONT face=Arial size=1>|| <A ");
out.println("href=\"http://www.indianrail.gov.in/abir.html\">Indian Railways</A>| <A href=\"http://www.indianrail.gov.in/pnr_stat.html\" target=DispArea>Passenger ");
out.println("Status</A> | <A href=\"http://www.indianrail.gov.in/acc_avl.html\" ");
out.println("target=DispArea>Seat Availability</A> | <A ");
out.println("href=\"http://www.indianrail.gov.in/fare_enq.html\" target=DispArea>Fare</A> |<BR>");
out.println("| <A href=\"http://www.indianrail.gov.in/src_dest_trns.html\" ");
out.println("target=DispArea>TrainsBetween Stations</A> | <A ");
out.println("href=\"http://www.indianrail.gov.in/inet_trn_num.html\" ");
out.println("target=DispArea>Schedule</A> | <A href=\"http://www.indianrail.gov.in/stn_code.html\" ");
out.println("target=DispArea>Know Station Code?</A> |<A ");
out.println("href=\"http://www.indianrail.gov.in/inet_trn_num.html\" target=DispArea>Know Train ");
out.println("Number?</A> | <BR>");
out.println("| <A href=\"http://www.indianrail.gov.in/seatkt.html\" ");
out.println("target=DispArea>Season Tickets</A> | <A ");
out.println("href=\"http://www.indianrail.gov.in/class.html\" target=DispArea>Class Codes</A> ");
out.println("| <A href=\"http://www.indianrail.gov.in/quotas.html\" target=DispArea>Quota Codes</A>| ");
out.println("<A ");
out.println("href=\"http://www.indianrail.gov.in/resrules.html\" target=DispArea>Reservation ");
out.println("Rules</A><BR>");
out.println("| <A href=\"http://www.indianrail.gov.in/refund_rules.html\" ");
out.println("target=DispArea>Refund Rules</A> | <A ");
out.println("href=\"http://www.indianrail.gov.in/break.html\" target=DispArea>Break Journey Rules</A> ");
out.println("| <A ");
out.println("href=\"http://www.indianrail.gov.in/tatkal.html\" target=DispArea>Tatkal Trains&nbsp;</A> ");
out.println("||</FONT> </p>");
out.println("<HR align=center noShade>");
out.println("<p>&nbsp;</p>");
out.println("</body>");
out.println("</html>");

                      }

             }
            else
             {


out.println("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">");
out.println("<html>");
out.println("<head>");
out.println("<title>invalidlogin</title>");
out.println("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">");
out.println("<SCRIPT>");
out.println("/*function doClear()");
out.println("{       ");
out.println("document.mainform.BudgetAmtPDay.value = \"\";");
out.println("document.mainform.BudgetAmtPTrip.value = \"\";");
out.println("}*/");
out.println("function doSubmit()");
out.println("{         ");
out.println("var strErrMsg;");
out.println("strErrMsg = \"\";          ");
out.println("strErrMsg = doValidations();");
out.println("if (strErrMsg == \"\" )");
out.println("{              ");
out.println("document.mainform.action = \"trainbook\"  ;                     ");
out.println("document.mainform.submit();");
out.println("}");
out.println("else");
out.println("{alert(strErrMsg);}");
out.println("}");
out.println("function doValidations()");
out.println("{");
out.println("var ddIndex;");
out.println("var strTemp;");
out.println("var strFld;");
out.println("var frmDoc;");
out.println("var strErrMsg;");
out.println("strErrMsg = \"\";");
out.println("frmDoc = document.mainform;            ");
out.println("strFld = frmDoc.login");
out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"Please enter loginId\\n\";          ");
out.println("strFld = frmDoc.password");
out.println("if (strFld.value == \"\") strErrMsg = strErrMsg + \"Please enter password\\n\"; ");
out.println("return strErrMsg;");
out.println("}");
out.println("</SCRIPT>");
out.println("</head>");
out.println("<body>");
out.println("<FORM name=mainform method=post>");
out.println("<div align=\"center\">");
out.println("<center>");
out.println("<div align=\"center\">");
out.println("<center>");
out.println("<TABLE cellSpacing=0 cellPadding=0 width=750 border=0 style=\"border-collapse: collapse\" bordercolor=\"#111111\">");
out.println("<TBODY>");
out.println("<TR> ");
out.println("<TD class=header><img src=\"images/frontpage.gif\" alt=\"\" width=\"386\" height=\"71\"><img src=\"images/Hdr_AS_Seal.jpg\" width=\"289\" height=\"71\"> ");
out.println("<img src=\"images/1animated12-thumb%5B1%5D.gif\" width=\"67\" height=\"50\"> ");
out.println("</TD>");
out.println("</TR>");
out.println("</TBODY>");
out.println("</TABLE>");
out.println("</center>");
out.println("</div>");
out.println("<p align=\"left\"><font face=\"arial\" size=\"2\"> ");
out.println("<marquee behavior=\"scroll\" style=\"font-family: Courier New; color: #333300; text-decoration: blink; font-size: 18pt; font-style: italic; font-weight: bold\">");
out.println("we share a visi<img src=\"images/Animsun.gif\" width=\"50\" height=\"26\">n ");
out.println("</marquee>");
out.println("</font></p>");
out.println("</center>");
out.println("</div>");
out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
out.println("<tr bordercolor=\"#CCCCCC\" bgcolor=\"#000099\"> ");
out.println("<td width=\"10%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"home.htm\"><font color=\"#FFFFFF\" size=\"5\">Home</font></a></div></td>");
out.println("<td width=\"14%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"services\"><font color=\"#FFFFFF\" size=\"5\">Services</font></a></div></td>");
out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"packagefinal.htm\"><font color=\"#FFFFFF\" size=\"5\">Holiday ");
out.println("Packages </font></a></div></td>");
out.println("<td width=\"11%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"faq.htm\"><font color=\"#FFFFFF\" size=\"5\">FAQs</font></a></div></td>");
out.println("<td width=\"25%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"register.htm\"><font color=\"#FFFFFF\" size=\"5\">Register ");
out.println("Yourself</font></a></div></td>");
out.println("<td width=\"15%\" bgcolor=\"#000099\"> <div align=\"center\"><a href=\"aboutus.htm\"><font color=\"#FFFFFF\" size=\"5\">About ");
out.println("Us</font></a></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td colspan=\"6\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
out.println("<tr bgcolor=\"#0000CC\"> ");
out.println("<td width=\"21%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"acc.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
out.println("Accommodation</font></a></div></td>");
out.println("<td width=\"24%\" bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"travel.htm\"><font color=\"#FFFFFF\" size=\"4\"> ");
out.println("Traveling Means</font></a></div>");
out.println("<div align=\"center\"></div></td>");
out.println("<td width=\"25%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travelguide.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
out.println("Guide</font></a></div></td>");
out.println("<td width=\"30%\" bgcolor=\"#0000CC\"> <div align=\"center\"><a href=\"travelinsurance.htm\"><font color=\"#FFFFFF\" size=\"4\">Travel ");
out.println("Insurance</font></a></div></td>");
out.println("</tr>");
out.println("</table></td>");
out.println("</tr>");
out.println("</table>");
out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
out.println("<tr bgcolor=\"#3333FF\"> ");
out.println("<td bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"car.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
out.println("Car</font></a></div></td>");
out.println("<td bgcolor=\"#3399FF\"> <div align=\"center\"><a href=\"train.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
out.println("Train</font></a></div></td>");
out.println("<td bgcolor=\"#3333FF\"> <div align=\"center\"><a href=\"flight.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
out.println("Flight</font></a></div></td>");
out.println("<td> <div align=\"center\"><a href=\"cruise.htm\"><font color=\"#FFFFFF\" size=\"4\">By ");
out.println("Cruises</font></a></div></td>");
out.println("</tr>");
out.println("</table>");
out.println("<p align=\"center\"><span class=\"style1\"><u><font color=\"#990000\" size=\"6\"><strong>Online resrevation</strong></font></u></span></p>");
out.println("<div align=\"center\"></div>");
out.println("<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
out.println("<tr> ");
out.println("<td width=\"35%\" height=\"52\" bgcolor=\"#FFCCFF\"> <table width=\"100%\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#FF99FF\">");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><font size=\"4\"><a href=\"passengerstatus.htm\">Passenger ");
out.println("Status</a></font></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFFFCC\"><div align=\"center\"><font size=\"4\"><a href=\"trainsbetweenimportantstations.htm\">Trains ");
out.println("between important stations</a></font></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFFFCC\"> <div align=\"center\"><font size=\"4\"><a href=\"avalibiltystatusatstations.htm\">Avalibilty ");
out.println("status at stations</a></font></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFFFCC\"><div align=\"center\"><font size=\"4\"><a href=\"faresoftrains.htm\">Fares ");
out.println("of trains </a> </font></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFCCFF\"> <div align=\"center\"><font size=\"4\"><a href=\"onlinereservation.htm\">Online ");
out.println("Reservation</a></font></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td height=\"25\" bgcolor=\"#FFFFCC\"> <div align=\"center\"><font size=\"4\"><a href=\"http://localhost:8080/hcutravels\timetablet.htm\" target=\"_blank\">Time ");
out.println("Table</a></font></div></td>");
out.println("</tr>");
out.println("</table></td>");
out.println("<td width=\"65%\"><table width=\"100%\" height=\"267\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"airfare_search_bg_big.gif\">");
out.println("<tr bgcolor=\"#FFCCFF\"> ");
out.println("<td height=\"39\" colspan=\"2\"> ");
out.println("<div align=\"center\"><font color=\"#660033\" size=\"5\">Online Railway ");
out.println("Reservation</font></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td width=\"69%\" height=\"228\"> ");
out.println("<div align=\"center\"> ");
out.println("<table width=\"100%\" height=\"224\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
out.println("<tr bgcolor=\"#FFCCFF\"> ");
out.println("<td colspan=\"2\"> ");
out.println("<div align=\"center\"><em><strong><font color=\"#660000\" size=\"5\">Invalid ");
out.println("login id try again!!!</font></strong></em></div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td width=\"41%\" bgcolor=\"#FFCCFF\"> ");
out.println("<div align=\"center\"><strong>Login ID</strong></div></td>");
out.println("<td width=\"59%\" bgcolor=\"#FFCCFF\"> ");
out.println("<div align=\"center\"> ");
out.println("<input name=\"loginid\" type=\"text\" id=\"login\">");
out.println("</div></td>");
out.println("</tr>");
out.println("<tr> ");
out.println("<td bgcolor=\"#FFCCFF\"> ");
out.println("<div align=\"center\"><strong>Password</strong></div></td>");
out.println("<td bgcolor=\"#FFCCFF\"> ");
out.println("<div align=\"center\"> ");
out.println("<input name=\"pswd\" type=\"password\" id=\"password\">");
out.println("</div></td>");
out.println("</tr>");
out.println("<tr bgcolor=\"#FFCCFF\"> ");
out.println("<td height=\"79\" colspan=\"2\"> ");
out.println("<div align=\"center\" > <strong> ");
out.println("<object classid=\"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000\" codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=5,0,0,0\" width=\"147\" height=\"34\">");
out.println("<param name=\"BGCOLOR\" value=\"#FFCCFF\">");
out.println("<param name=\"movie\" value=\"images/oresinvlogin.swf\">");
out.println("<param name=\"quality\" value=\"high\">");
out.println("<embed src=\"images/oresinvlogin.swf\" width=\"147\" height=\"34\" quality=\"high\" pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" bgcolor=\"#FFCCFF\" base=\"\" ></embed> ");
out.println("</object>");
out.println("</strong></div></td>");
out.println("</tr>");
out.println("</table>");
out.println("</div></td>");
out.println("<td width=\"31%\"><img src=\"images/Southern%20GP59.jpg\" width=\"162\" height=\"225\"></td>");
out.println("</tr>");
out.println("</table></td>");
out.println("</tr>");
out.println("</table>");
out.println("<p align=\"center\"><u></u></p>");
out.println("<HR align=center noShade>");
out.println("<p align=\"center\"><FONT face=Arial size=1>|| <A ");
out.println("href=\"http://www.indianrail.gov.in/abir.html\">Indian Railways</A>| <A href=\"http://www.indianrail.gov.in/pnr_stat.html\" target=DispArea>Passenger ");
out.println("Status</A> | <A href=\"http://www.indianrail.gov.in/acc_avl.html\" ");
out.println("target=DispArea>Seat Availability</A> | <A ");
out.println("href=\"http://www.indianrail.gov.in/fare_enq.html\" target=DispArea>Fare</A> |<BR>");
out.println("| <A href=\"http://www.indianrail.gov.in/src_dest_trns.html\" ");
out.println("target=DispArea>TrainsBetween Stations</A> | <A ");
out.println("href=\"http://www.indianrail.gov.in/inet_trn_num.html\" ");
out.println("target=DispArea>Schedule</A> | <A href=\"http://www.indianrail.gov.in/stn_code.html\" ");
out.println("target=DispArea>Know Station Code?</A> |<A ");
out.println("href=\"http://www.indianrail.gov.in/inet_trn_num.html\" target=DispArea>Know Train ");
out.println("Number?</A> | <BR>");
out.println("| <A href=\"http://www.indianrail.gov.in/seatkt.html\" ");
out.println("target=DispArea>Season Tickets</A> | <A ");
out.println("href=\"http://www.indianrail.gov.in/class.html\" target=DispArea>Class Codes</A> ");
out.println("| <A href=\"http://www.indianrail.gov.in/quotas.html\" target=DispArea>Quota Codes</A>| ");
out.println("<A ");
out.println("href=\"http://www.indianrail.gov.in/resrules.html\" target=DispArea>Reservation ");
out.println("Rules</A><BR>");
out.println("| <A href=\"http://www.indianrail.gov.in/refund_rules.html\" ");
out.println("target=DispArea>Refund Rules</A> | <A ");
out.println("href=\"http://www.indianrail.gov.in/break.html\" target=DispArea>Break Journey Rules</A> ");
out.println("| <A ");
out.println("href=\"http://www.indianrail.gov.in/tatkal.html\" target=DispArea>Tatkal Trains&nbsp;</A> ");
out.println("||</FONT> </p>");
out.println("<HR align=center noShade>");
out.println("<p>&nbsp;</p>");
out.println("</body>");
out.println("</html>");


 
              }




             }
catch(Exception e){
                out.println("Exception"+e.getMessage()+e.toString());
            }
            finally{
                try{
                    if(c!=null)
                        c.close();
                }catch(Exception e){
                    out.println("Exception closing the connection"+e.getMessage());
                }
            }
        }
   }
   
